- src/Games/NexusMods.Games.BethesdaGameStudios/Installers/LooseFileInstaller.cs
- src/Games/NexusMods.Games.BethesdaGameStudios/SkyrimSpecialEdition.cs
- src/Games/NexusMods.Games.DarkestDungeon/DarkestDungeonModInstaller.cs
- src/NexusMods.CLI/Verbs/ListModContents.cs
- src/NexusMods.CLI/Verbs/ListMods.cs
- src/NexusMods.DataModel/Abstractions/EntityDictionary.cs
- src/NexusMods.DataModel/Loadouts/AModFile.cs
- src/NexusMods.DataModel/Loadouts/Loadout.cs
- src/NexusMods.DataModel/Loadouts/LoadoutManager.cs
- src/NexusMods.DataModel/Loadouts/Markers/LoadoutMarker.cs
- src/NexusMods.DataModel/Loadouts/Mod.cs
- src/NexusMods.DataModel/Loadouts/ModFileId.cs
- tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/SkyrimSpecialEditionTests.cs
- tests/NexusMods.DataModel.Tests/ApplicationTests.cs
- tests/NexusMods.DataModel.Tests/LMDBDataStoreTests.cs
- tests/NexusMods.DataModel.Tests/ModSortingTests.cs
- tests/NexusMods.DataModel.Tests/ModelTests.cs
- tests/NexusMods.StandardGameLocators.TestHelpers/StubbedGames.cs
Relationships between mods, files, and loadouts are now expressed via Dictionaries. Added helper methods for updating/deleting/adding mods and files to a loadout.
> Refactor loadout mod file relationships

- tests/Games/NexusMods.Games.RedEngine.Tests/NexusMods.Games.RedEngine.Tests.csproj
> Fixed: Incorrect .csproj path in RedEngine Test Project (Fixes #91)

- src/ArchiveManagement/NexusMods.FileExtractor/NexusMods.FileExtractor.csproj
> Fixed: 7z.dll missing on Windows (fixes #96)

- tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/NexusMods.Games.BethesdaGameStudios.Tests.csproj
- tests/Games/NexusMods.Games.RedEngine.Tests/NexusMods.Games.RedEngine.Tests.csproj
- tests/Networking/NexusMods.Networking.HttpDownloader.Tests/NexusMods.Networking.HttpDownloader.Tests.csproj
- tests/Networking/NexusMods.Networking.NexusWebApi.Tests/NexusMods.Networking.NexusWebApi.Tests.csproj
- tests/NexusMods.DataModel.RateLimiting.Tests/NexusMods.DataModel.RateLimiting.Tests.csproj
- tests/NexusMods.DataModel.Tests/NexusMods.DataModel.Tests.csproj
- tests/NexusMods.FileExtractor.Tests/NexusMods.FileExtractor.Tests.csproj
- tests/NexusMods.Hashing.xxHash64.Tests/NexusMods.Hashing.xxHash64.Tests.csproj
- tests/NexusMods.StandardGameLocators.Tests/NexusMods.StandardGameLocators.Tests.csproj
Remainder of https://github.com/Nexus-Mods/NexusMods.App/pull/98 ; seems I missed an item.
[I'm embarrassed...]
> Fixed: XUnit DependencyInjection Related Issues in Remaining Projects

- src/NexusMods.DataModel/Loadouts/LoadoutManager.cs
> Fixed: ModSortingRulesArePreserved Regression (fixes #101)

- src/Games/NexusMods.Games.TestHarness/Verbs/StressTest.cs
- src/Networking/NexusMods.Networking.HttpDownloader/SimpleHttpDownloader.cs
- src/NexusMods.App/Program.cs
I didn't dispose the download job, so the stress tests die after NUM_CPU downloads 🤦
> Fix SimpleHttpDownloader.cs for StressTests

- src/Games/NexusMods.Games.TestHarness/RecentModsTests.cs
- src/Networking/NexusMods.Networking.NexusWebApi/Client.cs
- src/Networking/NexusMods.Networking.NexusWebApi/DTOs/Category.cs
- src/Networking/NexusMods.Networking.NexusWebApi/DTOs/DownloadLink.cs
- src/Networking/NexusMods.Networking.NexusWebApi/DTOs/GameInfo.cs
- src/Networking/NexusMods.Networking.NexusWebApi/DTOs/Interfaces/IJsonSerializable.cs
- src/Networking/NexusMods.Networking.NexusWebApi/DTOs/ModFile.cs
- src/Networking/NexusMods.Networking.NexusWebApi/DTOs/ModFiles.cs
- src/Networking/NexusMods.Networking.NexusWebApi/DTOs/ModUpdate.cs
- src/Networking/NexusMods.Networking.NexusWebApi/DTOs/ValidateInfo.cs
- tests/Networking/NexusMods.Networking.NexusWebApi.Tests/ClientTests.cs
> Added: Source Generation to Web API (fixes #122)

- src/NexusMods.DataModel/Sorting/Sorter.cs
- tests/NexusMods.DataModel.Tests/SortTests.cs
Used for testing.
See https://github.com/Nexus-Mods/NexusMods.App/issues/139 for details.
> Fixed Concurrency Issue in LargeComplexCollectionsCanBeSorted (fixes #139)

- src/NexusMods.DataModel/NexusMods.DataModel.csproj
We no longer use these libraries so let's remove them
> Remove RocksDB and LMDB links in the datamodel project

- src/Networking/NexusMods.Networking.NexusWebApi/LoginManager.cs
- src/NexusMods.CLI/Services.cs
- src/NexusMods.Common/FakeProcessFactory.cs
- src/NexusMods.Common/NexusMods.Common.csproj
- src/NexusMods.Common/ProtocolRegistration/IProtocolRegistration.cs
- src/NexusMods.Common/ProtocolRegistration/ProtocolRegistrationLinux.cs
- src/NexusMods.Common/ProtocolRegistration/ProtocolRegistrationWindows.cs
- src/NexusMods.CommonTests/ProtocolRegistrationTests.Linux.cs
> Protocol Registration for Linux

- src/NexusMods.DataModel/Loadouts/Markers/LoadoutMarker.cs
- tests/NexusMods.DataModel.Tests/ApplicationTests.cs
- tests/NexusMods.DataModel.Tests/ArchiveContentsCacheTests.cs
- tests/NexusMods.DataModel.Tests/DataStoreTests.cs
- tests/NexusMods.DataModel.Tests/Harness/ADataModelTest.cs
- tests/NexusMods.DataModel.Tests/ModSortingTests.cs
- tests/NexusMods.DataModel.Tests/ModelTests.cs
- tests/NexusMods.DataModel.Tests/SerializerTests.cs
- tests/NexusMods.DataModel.Tests/SortTests.cs
- tests/NexusMods.DataModel.Tests/Startup.cs
- tests/NexusMods.DataModel.Tests/ToolTests.cs
This is a quick one-off PR which cleans up warnings [and JetBrains' problems] in the `NexusMods.DataModel.Tests` project as I forgot to do this when doing the cleanups for the DataModel.
Nothing to say here; PR is tiny.
> DataModel Tests: Cleanup Warnings & Problems

- src/NexusMods.Common/OSInterop/OSInteropWindows.cs
- src/NexusMods.CommonTests/OSInteropTests.cs
> Use CliWrap for OpenURL on Windows

- src/NexusMods.Paths/FileSystemAbstraction/BaseFileSystem.cs
- src/NexusMods.Paths/FileSystemAbstraction/IFileSystem.cs
- src/NexusMods.Paths/FileSystemAbstraction/KnownPath.cs
- src/NexusMods.Paths/Utilities/KnownFolders.cs
Move `KnownFolders` functionality to `IFileSystem`, to allow for path mapping.
> Add `IFileSystem.GetKnownPath`

- src/NexusMods.App.UI/Controls/TopBar/ITopBarViewModel.cs
- src/NexusMods.App.UI/Controls/TopBar/TopBarDesignViewModel.cs
- src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml.cs
- src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
- src/NexusMods.App.UI/Windows/MainWindow.axaml.cs
While doing a basic compile & run test, I noticed that the Maximize button was one-way. We can't have that!
I've renamed `MaximizeCommand` to `ToggleMaximizeCommand` and implemented a basic ternary conditional to toggle the window state.
> Convert "Maximize" button to a toggle

- src/NexusMods.Paths/FileSystemAbstraction/BaseFileSystem.cs
- src/NexusMods.Paths/FileSystemAbstraction/IFileSystem.cs
- src/NexusMods.Paths/FileSystemAbstraction/InMemoryFileSystem/InMemoryFileSystem.cs
- src/NexusMods.Paths/FileSystemAbstraction/RealFileSystem/FileSystem.cs
- tests/NexusMods.Paths.Tests/FileSystem/BaseFileSystemTests.cs
- fixes path mappings with `GetKnownPath`
- adds `IFileSystem.EnumerateRootDirectories`
> File system bug fixes

- src/NexusMods.DataModel/Loadouts/LoadoutManager.cs
- tests/NexusMods.DataModel.Tests/ModelTests.cs
> Use / instead of \ for zip entries

- docs/games/00001-SkyrimSE.md
This pull request is a draft aimed at providing basic documentation for Skyrim Special Edition. 
Ideally down the road I'd (personally) like to have a quick reference in place for every game we support. 
This will ensure that:
- Developers can switch between games faster.
- Perform maintenance tasks on games they haven't originally implemented. 
- Make it easier for new contributors to get involved with the project.
- We can clearly identify what we need in NMA to support a specific game.
This is the first document in this series; therefore the overall format, the information it needs to include etc. can be augmented based on feedback.
As Skyrim Special Edition is a complex game, several items are required for comprehensive support.  These will need individual issues; and certain …
> [Feedback Requested] Added: Draft Documentation for SkyrimSE

- src/ArchiveManagement/NexusMods.FileExtractor/IFileExtractorSettings.cs
- src/NexusMods.App/AppConfig.cs
- src/NexusMods.App/Program.cs
- src/NexusMods.DataModel/IDataModelSettings.cs
- src/NexusMods.Paths/ConfigurationPath.cs
- tests/NexusMods.UI.Tests/AppStartupTests.cs
Fixed the config serialization and implemented a test to check for bad startup/DI code in the future.
> Fix config serialization

- src/NexusMods.App.UI/Controls/Spine/Buttons/Download/DownloadButtonDesignerViewModel.cs
- src/NexusMods.App.UI/Controls/Spine/Buttons/Download/DownloadButtonView.axaml
- src/NexusMods.App.UI/Controls/Spine/Buttons/Download/DownloadButtonView.axaml.cs
- src/NexusMods.App.UI/Controls/Spine/Buttons/Download/DownloadButtonViewModel.cs
- src/NexusMods.App.UI/Controls/Spine/Buttons/Download/IDownloadButtonViewModel.cs
- src/NexusMods.App.UI/Controls/Spine/ISpineViewModel.cs
- src/NexusMods.App.UI/Controls/Spine/Spine.axaml
- src/NexusMods.App.UI/Controls/Spine/SpineDesignViewModel.cs
- src/NexusMods.App.UI/Controls/Spine/SpineViewModel.cs
- src/NexusMods.App.UI/Extensions/ReactiveExtensions.cs
- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/NexusMods.App.UI/Palatte/Nexus.xaml
- src/NexusMods.App.UI/Services.cs
- src/NexusMods.App.UI/Theme/ButtonStyles/Index.xaml
- src/NexusMods.App.UI/Theme/ButtonStyles/Spine/DownloadButton.xaml
- src/NexusMods.App.UI/Theme/IconStyles.xaml
- tests/NexusMods.UI.Tests/Controls/Spine/DownloadButtonViewTests.cs
Implements the spine download button as per #252 
The main view model doesn't have any testable code at the moment, but the features of the button are showcased in the design view model, which does have several tests. 
Hooked it into the app, replacing the previous placeholder button:
> Spine Download Button

- scripts/validate-nupkgs.ps1
The script failed in the recent workflow run: https://github.com/Nexus-Mods/NexusMods.App/actions/runs/5258294110/jobs/9502336787
> Fix validate nupkgs script

- .github/workflows/validate-nupkgs.yaml
> Add validate-nupkgs workflow

- src/NexusMods.App.UI/Controls/Spine/SpineViewModel.cs
Fixes #373 
The LeftMenu is initially set to a DesignViewModel, which isn't interactable, that is what was happening before.
This just changes the view model to the correct one and activates the home button inside WhenActivated().
> Select home button on startup

- src/NexusMods.CLI/Verbs/Apply.cs
Fixes #415 
Let me know if this version is good
> Improve Apply cli command help description

- Directory.Packages.props
- src/Games/NexusMods.Games.BethesdaGameStudios/SkyrimLegendaryEdition/SkyrimLegendaryEdition.cs
- src/Games/NexusMods.Games.BethesdaGameStudios/SkyrimSpecialEdition/SkyrimSpecialEdition.cs
- src/Games/NexusMods.Games.DarkestDungeon/DarkestDungeon.cs
- src/Games/NexusMods.Games.RedEngine/Cyberpunk2077.cs
- src/Games/NexusMods.Games.Sifu/Sifu.cs
- src/Games/NexusMods.Games.StardewValley/StardewValley.cs
- src/NexusMods.DataModel/Games/Steam/ISteamGame.cs
- src/NexusMods.DataModel/Games/Steam/SteamLocatorResultMetadata.cs
- src/NexusMods.StandardGameLocators/Services.cs
- src/NexusMods.StandardGameLocators/SteamLocator.cs
- tests/NexusMods.StandardGameLocators.TestHelpers/Services.cs
- tests/NexusMods.StandardGameLocators.TestHelpers/StubbedGames/StubbedGame.cs
resolves #478 
GameFinder 3.2.0 does not yet handle all the debug assert failures of #363
> Update GameFinder version and fix problems from API changes

- tests/NexusMods.CLI.Tests/Startup.cs
Hopefully makes CLI issues easier to debug. Related to #487 and #425.
> Enable logging for CLI

- src/Games/NexusMods.Games.BethesdaGameStudios/RunGameWithScriptExtender.cs
- src/Games/NexusMods.Games.BethesdaGameStudios/Services.cs
- src/Games/NexusMods.Games.BethesdaGameStudios/SkyrimLegendaryEdition/SkyrimLegendaryEditionGameTool.cs
- src/Games/NexusMods.Games.BethesdaGameStudios/SkyrimSpecialEdition/SkyrimSpecialEditionGameTool.cs
- src/Games/NexusMods.Games.RedEngine/RedModDeployTool.cs
- src/NexusMods.DataModel/Games/ITool.cs
- src/NexusMods.DataModel/Games/RunGameTool.cs
- src/NexusMods.DataModel/ToolManager.cs
- tests/NexusMods.StandardGameLocators.TestHelpers/ListFilesTool.cs
Modifies the RunGameTool so that it supports launching SKSE instead of Skyrim. Also waits for the game itself ot exit after running the launcher.
> Support for SKSE launching when running Skyrim

- src/Networking/NexusMods.Networking.HttpDownloader/AdvancedHttpDownloader.cs
Changes:
- Resolves #512 by removing unnecessarily verbose logging statements.
- Minor code cleanup.
> Cleanup `AdvancedHttpDownloader`

- src/Games/NexusMods.Games.BethesdaGameStudios/PluginAnalyzer.cs
> Fix plugin parsing for non-Skyrim files

- Directory.Packages.props
- tests/Directory.Build.props
- tests/Networking/NexusMods.Networking.Downloaders.Tests/Serialization/DownloaderStateTests.cs
- tests/Networking/NexusMods.Networking.Downloaders.Tests/Tasks/DownloadTasksCommon.cs
- tests/Networking/NexusMods.Networking.Downloaders.Tests/Tasks/HttpDownloadTaskTests.cs
- tests/Networking/NexusMods.Networking.Downloaders.Tests/Tasks/NxmDownloadTaskTests.cs
- tests/Networking/NexusMods.Networking.NexusWebApi.Tests/MockHttpMessageHandler.cs
- tests/Networking/NexusMods.Networking.NexusWebApi.Tests/OAuth2MessageFactoryTests.cs
- tests/Networking/NexusMods.Networking.NexusWebApi.Tests/OAuthTests.cs
- tests/Networking/NexusMods.Networking.NexusWebApi.Tests/Startup.cs
- tests/NexusMods.CLI.Tests/VerbTests/ProtocolInvocationTests.cs
- tests/NexusMods.Common.Tests/OSInteropTests.cs
- tests/NexusMods.DataModel.RateLimiting.Tests/JobThroughputTests.cs
- tests/NexusMods.DataModel.Tests/LoadoutSynchronizerTests/ApplyLoadoutTests.cs
- tests/NexusMods.UI.Tests/RightContent/Downloads/ViewModels/DownloadTaskViewModelTests.cs
> Replace Moq with NSubstitute

- src/NexusMods.App/Program.cs
- src/NexusMods.CLI/CommandLineConfigurator.cs
> Fix fomod install not working due to missing console renderer

- Directory.Packages.props
https://github.com/erri120/GameFinder/releases/tag/v3.2.2
> Upgrade GameFinder to 3.2.2

- Directory.Packages.props
- src/NexusMods.DataModel/Games/GamePath.cs
- tests/NexusMods.DataModel.Tests/GamePathTests.cs
> Update Paths library to 0.1.2 and add back GamePath to main repo

- src/NexusMods.App/AppConfig.json
> Fixed: DataModel Default Paths in AppConfig.json

- docs/games/0005-SkyrimLE.md
Fixed typos and changed engine to "Creation (Gamebryo)" like in the SE docs.
> Fixes in Skyrim LE docs

- docs/games/0001-SkyrimSE.md
- docs/games/0005-SkyrimLE.md
* Change SSEEdit to TES5Edit in LE docs
* Fix local appdata path in SE docs
* Use USSEP as example instead of LE-version in SE docs
> More Skyrim docs fixes

- docs/UICodingConventions.md
Add mention to Avalonia extensions for VS and Rider that allow previewing .axaml UIs.
> Add mention to Avalonia extensions for IDEs in docs

- src/Games/NexusMods.Games.FOMOD.UI/Resources/Language.pl.resx
> #600
> 
> `Language.pl.resx.`
> 
> Polish UI for FOMOD.
> Polish for FOMOD UI

- src/NexusMods.App.UI/Overlays/MetricsOptIn/MetricsOptInView.axaml
- src/NexusMods.App.UI/Overlays/Updater/UpdaterView.axaml
- src/NexusMods.App.UI/Theme/TextBlockStyles.xaml
> Fix text negative margins due to outdated TextBox styling class.

- .github/dependabot.yml
> Ignore System.IdentityModel.Tokens.Jwt updates

- .github/workflows/clean_environment_tests.yaml
- .github/workflows/validate-nupkgs.yaml
- Directory.Build.props
- src/NexusMods.App.UI/ViewModels/Helpers/ViewModelSelector/ViewModelSelector.cs
- tests/Games/NexusMods.Games.AdvancedInstaller.Tests/NexusMods.Games.AdvancedInstaller.Tests.csproj
- tests/Games/NexusMods.Games.Generic.Tests/NexusMods.Games.Generic.Tests.csproj
- tests/NexusMods.UI.Tests/Overlays/UpdaterViewModelTests.cs
> Switch to .NET 8.0

- Directory.Packages.props
- src/NexusMods.App.UI/DynamicDataExtensions.cs
- src/NexusMods.App.UI/Extensions/ListAdapter.cs
- src/NexusMods.DataModel/Extensions/ObservableExtensions.cs
Update several deps that were missing recently, most of which have to do with using their 8.0 versions
> Bump a lot of deps to their 8.0 versions

- src/NexusMods.DataModel/ArchiveInstaller.cs
Version was not propagated
I'm not sure whether other properties should be propagated also
> ArchiveInstaller propagate properties

- src/NexusMods.App.UI/Resources/Language.pl.resx
[#756](https://github.com/Nexus-Mods/NexusMods.App/pull/756)
</data>
<data name="LoadoutGridView__Add_Mod_Advanced" xml:space="preserve">
<value>Dodaj Mod (Zaawansowane)</value>
</data>
> adv-install-button-pl

- src/NexusMods.App.UI/WorkspaceSystem/GridUtils.cs
- src/NexusMods.App.UI/WorkspaceSystem/WorkspaceGridState.cs
- tests/NexusMods.UI.Tests/WorkspaceSystem/GridUtilsTests/GetPossibleStatesTests.cs
- tests/NexusMods.UI.Tests/WorkspaceSystem/WorkspaceGridStateTests/ColumnEnumeratorTests.cs
- tests/NexusMods.UI.Tests/WorkspaceSystem/WorkspaceGridStateTests/RowEnumeratorTests.cs
> Add entire column/row

- Directory.Packages.props
- tests/NexusMods.StandardGameLocators.TestHelpers/Services.cs
> Upgrade GameFinder to 4.1.0

- .github/dependabot.yml
- Directory.Packages.props
> Upgrade System.IdentityModel.Tokens.Jwt to 7.2.0

- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/AddPanelButtonView.axaml
- src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/AddPanelDropDownDesignViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/AddPanelDropDownView.axaml
- src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/AddPanelDropDownView.axaml.cs
- src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/AddPanelDropDownViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/IAddPanelDropDownViewModel.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Resources/ThemeBaseResources.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/ComboBox/ComboBoxStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/StylesIndex.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/WorkspaceSystem/AddPanelButtonStyles.axaml
This adds the `AddPanelDropDownView` and styles for it. 
The current basic implementation uses a static `WorkspaceGridState` to populate and does not reflect the actual Active Workspace state.
The buttons also don't currently do anything, but a subscription is already setup where the code to add the panel to the active workspace will go in the future.
> Added AddPanelDropDown button

- docs/FAQ.md
- docs/GettingStarted.md
- docs/decisions/backend/0003-paths.md
- docs/decisions/backend/0009-advanced-installer-design.md
- docs/development-guidelines/AddingAGame.md
- docs/development-guidelines/DependencyInjection.md
- docs/development-guidelines/InstallingMods.md
- docs/development-guidelines/LocalizationAndTranslation.md
- docs/development-guidelines/UICodingGuidelines.md
- docs/development-guidelines/UIStylingGuidelines.md
- docs/misc/DrawbacksOfNexusApproach.md
Updated all references to "The Nexus" and "NexusMods" to say "Nexus Mods".
> Documentation updates

- Directory.Packages.props
- benchmarks/NexusMods.Benchmarks/Benchmarks/XxHash64.cs
- src/Abstractions/NexusMods.Abstractions.Loadouts/Fingerprinter.cs
- src/Extensions/NexusMods.Extensions.DynamicData/EntityDictionaryExtensions.cs
- src/NexusMods.DataModel/SqliteDataStore.cs
- tests/NexusMods.UI.Tests/WorkspaceSystem/IconUtilsTests.cs
> Update deps before 0.4 release

- src/Games/NexusMods.Games.StardewValley/Installers/SMAPIInstaller.cs
- src/Games/NexusMods.Games.StardewValley/StardewValley.cs
> Always override Stardew Valley launch file

- .github/workflows/mod_install_tests.yaml
- Prevents workflow from failing CI
- Removes `sifu`
- Adds `mountandblade2bannerlord`
- Upgrade from .NET 7 to 8
- Remove codecov
> Fix mod install tests

- tests/Games/NexusMods.Games.StardewValley.Tests/Installers/SMAPIModInstallerTests.Test_InstallMod.verified.txt
- tests/Games/NexusMods.Games.StardewValley.Tests/Installers/SMAPIModInstallerTests.Test_MultipleModsOneArchive.verified.txt
- tests/Games/NexusMods.Games.StardewValley.Tests/Installers/SMAPIModInstallerTests.cs
- tests/Games/NexusMods.Games.TestFramework/AModInstallerTest.cs
- tests/Games/NexusMods.Games.TestFramework/NexusMods.Games.TestFramework.csproj
- tests/Games/NexusMods.Games.TestFramework/Verifiers/VerifiableMod.cs
> Use `Verify` for mod installers

- src/Abstractions/NexusMods.Abstractions.Loadouts/ILoadoutRegistry.cs
- src/NexusMods.App.UI/Controls/Spine/SpineViewModel.cs
- src/NexusMods.DataModel/Loadouts/LoadoutRegistry.cs
This also fixes spine buttons losing the selected (`Active`) styling on every loadout change/
> Fix spine buttons getting refreshed on every loadout change

- src/Abstractions/NexusMods.Abstractions.FileStore/Downloads/DownloadAnalysis.cs
- src/Games/NexusMods.Games.StardewValley/Installers/SMAPIInstaller.cs
- src/Games/NexusMods.Games.StardewValley/Models/SMAPIMarker.cs
- tests/Games/NexusMods.Games.StardewValley.Tests/Installers/SMAPIInstallerTests.cs
> Extract SMAPI version

- .gitignore
- NexusMods.App.sln
- NexusMods.App.sln.DotSettings
- docs/development-guidelines/UsingWorkspaces.md
- docs/requirements.txt
- mkdocs.yml
- src/Examples/Examples.csproj
- src/Examples/README.md
- src/Examples/Workspaces/001-querying-windows-and-workspaces.cs
- src/Examples/Workspaces/002-opening-new-pages.cs
- src/Examples/Workspaces/003-creating-new-pages.cs
- src/Examples/Workspaces/README.md
- src/NexusMods.App.UI/WorkspaceSystem/Page/APageViewModel.cs
Resolves #1041.
Adds docs and examples on how to use the workspace system.
> Workspace documentation

- src/NexusMods.App.UI/Resources/Language.pl.resx
- src/NexusMods.App.UI/Resources/Language.resx
> Update 'Mod Not Found' wording to match design

- Directory.Packages.props
Built ran tests, and tested using the app for a bit with no issues detected.
> More dep updates

- tests/Networking/NexusMods.Networking.HttpDownloader.Tests/AdvancedHttpDownloaderTests.cs
> Add `RequiresNetworking` trait

- src/Abstractions/NexusMods.Abstractions.Serialization/IDataStore.cs
- src/NexusMods.DataModel/FileHashCache.cs
- src/NexusMods.DataModel/SqliteDataStore.cs
@erri120 because I was too fast last time.
> Improved: Apply PR Feedback on previous PR

- src/Games/NexusMods.Games.AdvancedInstaller.UI/AdvancedManualInstallerUI.cs
fixes #1094 
This is a temporary solution that uses a normal window rather than a Modal dialog for the Advanced installer, so that it can be used again for testing and debugging
> Temp fix for advanced installer not starting

- Directory.Packages.props
- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/NexusMods.App.UI/Pages/Diagnostics/Details/DiagnosticDetailsDesignViewModel.cs
- src/NexusMods.App.UI/Pages/Diagnostics/Details/DiagnosticDetailsPage.cs
- src/NexusMods.App.UI/Pages/Diagnostics/Details/DiagnosticDetailsView.axaml
- src/NexusMods.App.UI/Pages/Diagnostics/Details/DiagnosticDetailsView.axaml.cs
- src/NexusMods.App.UI/Pages/Diagnostics/Details/DiagnosticDetailsViewModel.cs
- src/NexusMods.App.UI/Pages/Diagnostics/Details/IDiagnosticDetailsViewModel.cs
Fixes #933, part of #327. This isn't styled, that's part of #943.
https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/847d7582-90a0-4e55-9b66-cd5b3ba2e9ab
> Add markdown renderer

- src/Abstractions/NexusMods.Abstractions.Games/RunGameTool.cs
Changed `rungameid//` to `rungameid/`.
> Fix steam launch on Linux

- src/Games/NexusMods.Games.StardewValley/Emitters/MissingSMAPIEmitter.cs
> Don't include disabled SMAPI mods when counting

- src/NexusMods.App.UI/Resources/Language.pl.resx
> Diagnostics UI update in Polish UI

- src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
Part of 
- #1138
- Added the currently managed games to the "Games Added" section (live updates when a new game is managed)
- Excluded the currently managed games from the Detected Games section
> Managed games

- src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
Fixes `Call from invalid thread` for `ManagedGames` and `DetectedGames`.
```
00:00:26.522 [ERROR] (ReactiveUI.PropertyBinderImplementation) view.NoGamesManagedTextBlock.IsVisible Binding received an Exception!|System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.InvalidOperationException: Call from invalid thread
at Avalonia.Threading.Dispatcher.<VerifyAccess>g__ThrowVerifyAccess|16_0()
at Avalonia.AvaloniaObject.SetValue[T](StyledProperty`1 property, T value, BindingPriority priority)
at Avalonia.Visual.set_IsVisible(Boolean value)
at InvokeStub_Visual.set_IsVisible(Object, Span`1)
at System.Reflection.MethodBaseInvoker.InvokePropertySetter(Object obj, BindingFlags invokeAttr, Binder binder, Object parameter, CultureInfo …
```
> Use `OnUI`

- docs/GettingStarted.md
Related to https://github.com/Nexus-Mods/NexusMods.App/issues/761 and [#1162](https://github.com/Nexus-Mods/NexusMods.App/issues/1162)
> Update to the latest SDK in Getting Started

- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuDesignViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuView.axaml
> Left menu fixes

- src/NexusMods.App.UI/Resources/Language.pl.resx
> Polish UI for Apply Diff View

- .github/workflows/validate-changelog-assets.yaml
- docs/changelog-assets/README.md
- scripts/changelog-prepare-assets.sh
Ubuntu 22.04 ships with coreutils 8...
> Use b2sum for coreutils 8

- src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/DiagnosticSettings.cs
- src/Abstractions/NexusMods.Abstractions.Settings/APropertyValueContainer.cs
- src/Abstractions/NexusMods.Abstractions.Settings/BooleanContainer.cs
- src/Abstractions/NexusMods.Abstractions.Settings/ISettingsManager.cs
- src/Abstractions/NexusMods.Abstractions.Settings/ISettingsPropertyUIDescriptor.cs
- src/Abstractions/NexusMods.Abstractions.Settings/IUIProperty.cs
- src/Abstractions/NexusMods.Abstractions.Settings/IUIPropertyData.cs
- src/Abstractions/NexusMods.Abstractions.Settings/NexusMods.Abstractions.Settings.csproj
- src/Abstractions/NexusMods.Abstractions.Settings/SettingsBuilder/IPropertyUIBuilder.cs
- src/Abstractions/NexusMods.Abstractions.Settings/SettingsBuilder/ISettingsBuilder.cs
- src/Abstractions/NexusMods.Abstractions.Settings/SettingsBuilder/ISettingsUIBuilder.cs
- src/Abstractions/NexusMods.Abstractions.Settings/SettingsPropertyValueContainer.cs
- src/Abstractions/NexusMods.Abstractions.Settings/SingleValueMultipleChoiceContainer.cs
- src/Examples/Settings/AddingSettings.cs
- src/NexusMods.App.UI/Settings/LanguageSettings.cs
- src/NexusMods.App.UI/Settings/TelemetrySettings.cs
- src/NexusMods.Settings/PropertyBuilderOutput.cs
- src/NexusMods.Settings/SettingsBuilder.cs
- src/NexusMods.Settings/SettingsManager.Setup.cs
- src/NexusMods.Settings/SettingsManager.cs
- src/NexusMods.Settings/SettingsPropertyUIDescriptor.cs
- src/NexusMods.Settings/SettingsUIBuilder.cs
> Get all properties from `ISettingsManager` that should be exposed to the UI

- src/Games/NexusMods.Games.StardewValley/Emitters/DependencyDiagnosticEmitter.cs
- src/Games/NexusMods.Games.StardewValley/Emitters/SMAPIGameVersionDiagnosticEmitter.cs
- src/Games/NexusMods.Games.StardewValley/Emitters/SMAPIModDatabaseCompatibilityDiagnosticEmitter.cs
- src/Games/NexusMods.Games.StardewValley/Installers/SMAPIInstaller.cs
- src/Games/NexusMods.Games.StardewValley/Models/SMAPIMarker.cs
- src/Games/NexusMods.Games.StardewValley/WebAPI/ISMAPIWebApi.cs
- src/Games/NexusMods.Games.StardewValley/WebAPI/SMAPIWebApi.cs
> Use `ISemanticVersion` instead of `Version`

- src/Games/NexusMods.Games.StardewValley/Installers/SMAPIInstaller.cs
> Use FileVersionString

- src/NexusMods.App.UI/Controls/MarkdownRenderer/IMarkdownRendererViewModel.cs
- src/NexusMods.App.UI/Controls/MarkdownRenderer/MarkdownRendererDesignViewModel.cs
- src/NexusMods.App.UI/Controls/MarkdownRenderer/MarkdownRendererView.axaml
- src/NexusMods.App.UI/Controls/MarkdownRenderer/MarkdownRendererView.axaml.cs
- src/NexusMods.App.UI/Controls/MarkdownRenderer/MarkdownRendererViewModel.cs
- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/NexusMods.App.UI/Pages/Changelog/ChangelogPage.cs
- src/NexusMods.App.UI/Pages/Changelog/ChangelogPageView.axaml
- src/NexusMods.App.UI/Pages/Changelog/ChangelogPageView.cs
- src/NexusMods.App.UI/Pages/Changelog/ChangelogPageViewModel.cs
- src/NexusMods.App.UI/Pages/Changelog/IChangelogPageViewModel.cs
- src/NexusMods.App.UI/Resources/Language.Designer.cs
- src/NexusMods.App.UI/Resources/Language.resx
- src/NexusMods.App.UI/Services.cs
- src/NexusMods.App.UI/TypeFinder.cs
> Render Changelog

- src/NexusMods.App/Startup.cs
> Disable multi-window support

- src/NexusMods.App.BuildInfo/ApplicationConstants.cs
- src/NexusMods.App.UI/Overlays/Updater/IUpdaterViewModel.cs
- src/NexusMods.App.UI/Overlays/Updater/UpdaterViewModel.cs
- src/NexusMods.App.UI/Pages/Changelog/ChangelogPage.cs
> Use current Assembly version

- src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridViewModel.cs
- src/NexusMods.App.UI/Services.cs
- src/NexusMods.App.UI/Settings/LoadoutGridSettings.cs
- src/NexusMods.App.UI/Settings/ServiceExtensions.cs
- tests/NexusMods.UI.Tests/Startup.cs
> Hide game files

- src/Abstractions/NexusMods.Abstractions.Serialization/NexusMods.Abstractions.Serialization.csproj
- src/Abstractions/NexusMods.Abstractions.Serialization/Services.cs
- src/Abstractions/NexusMods.Abstractions.Settings/JsonStorageBackend.cs
- src/Abstractions/NexusMods.Abstractions.Settings/NexusMods.Abstractions.Settings.csproj
- src/Abstractions/NexusMods.Abstractions.Settings/ServiceExtensions.cs
- src/Abstractions/NexusMods.Abstractions.Settings/Types/ConfigurablePath.cs
- src/Abstractions/NexusMods.Abstractions.Telemetry/TelemetrySettings.cs
- src/NexusMods.App/LoggingSettings.cs
- src/NexusMods.App/Program.cs
- src/NexusMods.App/Services.cs
- src/NexusMods.DataModel/DataModelSettings.cs
- src/NexusMods.Settings/SettingsManager.cs
Resolves #1243.
- Adds `JsonStorageBackend` for saving configs to JSON files
- Allows telemetry and logging settings to be loaded before DI is available
- Adds logging settings to the UI
> Add slim settings manager host

- Directory.Packages.props
- src/NexusMods.App.UI/Helpers/StringFormatters.cs
- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/NexusMods.App.UI/Pages/Downloads/IInProgressViewModel.cs
- src/NexusMods.App.UI/Pages/Downloads/InProgressView.axaml
- src/NexusMods.App.UI/Pages/Downloads/InProgressView.axaml.cs
- src/NexusMods.App.UI/Pages/Downloads/InProgressViewModel.cs
Adds a sexy chart.
https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/2c7565cd-6f67-47ab-b0b8-6a5725caefeb
> Download speed chart

- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridViewModel.cs
Regressed in #1302. Same as #1286 for #1195.
> Regression: Hide Game Files

- src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
- src/Abstractions/NexusMods.Abstractions.Loadouts/Sorting/Last.cs
- src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridViewModel.cs
- src/NexusMods.App.UI/Settings/LoadoutGridSettings.cs
- src/NexusMods.DataModel/Sorting/Sorter.cs
- tests/NexusMods.DataModel.Tests/SortTests.cs
- tests/NexusMods.UI.Tests/Startup.cs
> Sort and optionally hide Override

- Directory.Packages.props
- src/NexusMods.App.UI/Controls/ModInfo/ModFiles/IModFilesViewModel.cs
- src/NexusMods.App.UI/Controls/ModInfo/ModFiles/ModFilesDesignViewModel.cs
- src/NexusMods.App.UI/Controls/ModInfo/ModFiles/ModFilesView.axaml
- src/NexusMods.App.UI/Controls/ModInfo/ModFiles/ModFilesView.axaml.cs
- src/NexusMods.App.UI/Controls/ModInfo/ModFiles/ModFilesViewModel.cs
- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/NexusMods.App.UI/Pages/ModInfo/ModInfoViewModel.cs
- src/NexusMods.App.UI/Pages/TextEdit/ITextEditorPageViewModel.cs
- src/NexusMods.App.UI/Pages/TextEdit/TextEditorPage.cs
- src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageView.axaml
- src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageView.axaml.cs
- src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageViewModel.cs
- src/NexusMods.App.UI/Services.cs
- src/NexusMods.App.UI/TypeFinder.cs
- src/NexusMods.App/App.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/NexusFluentDarkTheme.axaml
Resolves #916.
- Adds a Text Editor Page
- Adds a button to the mod contents page to open the text editor
- Saves the changes and updates the original file model
> Edit text files

- src/Abstractions/NexusMods.Abstractions.Loadouts/Ids/FileId.cs
- src/Abstractions/NexusMods.Abstractions.Loadouts/Ids/LoadoutId.cs
- src/Abstractions/NexusMods.Abstractions.Loadouts/Ids/ModId.cs
- src/Abstractions/NexusMods.Abstractions.Serialization/Json/EntityIdConverter.cs
- src/Abstractions/NexusMods.Abstractions.Serialization/NexusMods.Abstractions.Serialization.csproj
- src/Abstractions/NexusMods.Abstractions.Serialization/Services.cs
- src/NexusMods.App.UI/Windows/WindowDataAttributes.cs
- src/NexusMods.App.UI/Windows/WindowManager.cs
> Fix JSON serialization for WorkspaceData

- src/Abstractions/NexusMods.Abstractions.MnemonicDB.Attributes/IRepository.cs
- src/Abstractions/NexusMods.Abstractions.MnemonicDB.Attributes/Repository.cs
- src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageView.axaml
- src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageView.axaml.cs
- src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageViewModel.cs
Fixes #1361
Changes:
- fixes the highlighting issue due to double subscription triggers
- adds the detected language name to the UI
> Fix highlighting issue

- src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
> Fix Apply Diff not considering reified deletions correctly

- src/Games/NexusMods.Games.AdvancedInstaller.UI/Window/AdvancedInstallerWindowView.axaml.cs
- src/NexusMods.App.UI/Controls/Trees/Files/FileTreeNodeView.axaml.cs
- src/NexusMods.App.UI/Controls/Trees/Files/FileTreeNodeViewModel.cs
- src/NexusMods.App.UI/Controls/Trees/Files/IFileTreeNodeViewModel.cs
- src/NexusMods.App.UI/Controls/Trees/ModFileTreeViewModel.cs
- src/NexusMods.App.UI/Pages/ModInfo/ModInfoViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/PanelTabHeader/PanelTabHeaderView.axaml
- src/NexusMods.Icons/UnifiedIcon.cs
- fixes #1323 
- fixes #1340
- fixes #1339
- fixes tab header text and icon vertical alignment
- fixes Advanced installer window missing a title
> Fix mod contents showing deletions as normal files and other fixes

- src/NexusMods.App.UI/Pages/TextEdit/ITextEditorPageViewModel.cs
- src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageView.axaml
- src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageView.axaml.cs
- src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageViewModel.cs
- src/NexusMods.App.UI/Settings/LoadoutGridSettings.cs
- src/NexusMods.App.UI/Settings/ServiceExtensions.cs
- src/NexusMods.App.UI/Settings/TextEditorSettings.cs
- src/NexusMods.Icons/IconValues.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml
- Change themes using drop down menu
- Change font size with the ctrl+scroll wheel
- Adds `TextEditorSettings` containing the Theme and Font Size, latter isn't exposed in the UI yet
- Add toolbar at the top
- Many style improvements
- Adds copy and paste buttons
https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/47a778b8-29fa-4901-8a7f-e185c9f91f02
> Text editor styling

- src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
- src/Games/NexusMods.Games.StardewValley/StardewValley.cs
- src/Games/NexusMods.Games.StardewValley/StardewValleyLoadoutSynchronizer.cs
- src/NexusMods.DataModel/ApplyService.cs
- src/NexusMods.DataModel/Loadouts/DiskStateRegistry.cs
Resolves #1343.
Changes:
- Fixes an issue with the Apply Service and Disk State Registry where they use a default value for the last applied loadout
- Ingests new files into the correct SMAPI mod instead of "Override"
> Ingest mod files

- src/Games/NexusMods.Games.AdvancedInstaller.UI/Resources/Language.pl.resx
- src/NexusMods.App.UI/Resources/Language.pl.resx
> Change to “mod” in Polish UI and minor improvements

- CHANGELOG.md
- src/NexusMods.App.UI/Controls/MarkdownRenderer/MarkdownRendererView.axaml
> Update markdown styling

- src/NexusMods.App.UI/Resources/Language.pl.resx
Related to PR [#1397](https://github.com/Nexus-Mods/NexusMods.App/pull/1397)
> [Polish UI] Update of the download page

- src/NexusMods.App/NexusMods.App.csproj
> Disable the Console on Windows by Default

- .github/workflows/clean_environment_tests.yaml
- .github/workflows/networking_tests.yaml
> Add 20m test timeout

- NexusMods.App.sln
- src/Abstractions/NexusMods.Abstractions.Settings/NexusMods.Abstractions.Settings.csproj
- src/NexusMods.Settings/NexusMods.Settings.csproj
- src/NexusMods.Settings/SettingsManager.cs
- tests/NexusMods.Settings.Tests/NexusMods.Settings.Tests.csproj
- tests/NexusMods.Settings.Tests/SettingsManagerTests.Setup.cs
- tests/NexusMods.Settings.Tests/SettingsManagerTests.cs
- tests/NexusMods.Settings.Tests/Startup.cs
Fixes #1422. Also finally adds tests for the settings manager.
> Fix saving overriden values

- src/Games/NexusMods.Games.StardewValley/Emitters/DependencyDiagnosticEmitter.cs
- src/Games/NexusMods.Games.StardewValley/WebAPI/SMAPIWebApi.cs
> Fix exception for duplicate SMAPI mods

- src/NexusMods.App.UI/Helpers/DoubleClickHelper.cs
- tests/NexusMods.UI.Tests/AUiTest.cs
- tests/NexusMods.UI.Tests/Helpers/DoubleClickHelperTests.cs
> Add double click handler

- src/Games/NexusMods.Games.StardewValley/Emitters/MissingSMAPIEmitter.cs
- src/Games/NexusMods.Games.StardewValley/Emitters/SMAPIGameVersionDiagnosticEmitter.cs
- src/Games/NexusMods.Games.StardewValley/Installers/SMAPIModInstaller.cs
- src/Games/NexusMods.Games.StardewValley/Models/SMAPIMarker.cs
- src/Games/NexusMods.Games.StardewValley/Models/SMAPIModMarker.cs
> Fix SMAPI mod marker

- NexusMods.App.sln.DotSettings
- src/Games/NexusMods.Games.StardewValley/Diagnostics.cs
> Update diagnostic wording

- src/NexusMods.DataModel/ArchiveInstaller.cs
> Change mod name when installation fails

- src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs
- closes #1380
@erri120 I know there must be a better way to run the Async method than what I did, let me know what you think would be best
> Run Ingest on startup if current loadout is the last applied

- .github/workflows/build-linux-pupnet.yaml
- .github/workflows/build-windows-pupnet.yaml
- src/NexusMods.App/Commandline/CleanupVerbs.cs
Fixed: App Uninstallation in Single File Apps & Improve PupNet CI Build Step
This is:
- #1503
But for main branch
> Also Merge this to Main, Because we Can't Push to it Directly

- src/NexusMods.App.UI/Controls/Trees/DiffTreeViewModel.cs
- src/NexusMods.App.UI/Pages/Diff/ApplyDiff/ApplyDiffViewModel.cs
Changed the way the code tries to set the property on the main thread. 
Not sure if this will fix it as I can't reproduce at the moment.
> Apply Diff Preview infinite loading fix

- src/NexusMods.App.UI/Controls/Trees/DiffTreeViewModel.cs
- src/NexusMods.App.UI/Pages/Diff/ApplyDiff/ApplyDiffViewModel.cs
We were doing some UI operations off the UI
> Fix exception on Apply Diff Preview Refresh for 0.5 branch

- src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml
- src/NexusMods.App.UI/LeftMenu/Downloads/DownloadsLeftMenuView.axaml
- src/NexusMods.App.UI/LeftMenu/Home/HomeLeftMenuView.axaml
- src/NexusMods.App.UI/LeftMenu/LeftMenuView.axaml
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuView.axaml
- src/NexusMods.App.UI/Pages/Diagnostics/List/DiagnosticListView.axaml
- src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml
Same as 
- #1516 
but for main branch
> UI fixes main

- src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml
- src/NexusMods.App.UI/LeftMenu/Downloads/DownloadsLeftMenuView.axaml
- src/NexusMods.App.UI/LeftMenu/Home/HomeLeftMenuView.axaml
- src/NexusMods.App.UI/LeftMenu/LeftMenuView.axaml
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuView.axaml
- src/NexusMods.App.UI/Pages/Diagnostics/List/DiagnosticListView.axaml
- src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml
- fix #1505 
- fix #1489 
- fix #1488 
Will create another PR with this stuff rebased for Main
> UI fixes for 0.5 branch

- CHANGELOG.md
[Preview](https://github.com/erri120/NexusMods.App/blob/docs/changelog-0.5.1/CHANGELOG.md)
> Add 0.5.1 to CHANGELOG

- .github/workflows/git-builds.yaml
- scripts/build-linux-x64.sh
- scripts/build-win-x64.ps1
- src/NexusMods.App.BuildInfo/ApplicationConstants.cs
- src/NexusMods.App.UI/Controls/DevelopmentBuildBanner/DevelopmentBuildBannerView.axaml.cs
- src/NexusMods.App/Startup.cs
> Update Git Builds pipeline

- src/NexusMods.App.UI/Extensions/EnumerableExtensions.cs
- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/NexusMods.App.UI/Pages/Diagnostics/Details/DiagnosticDetailsPage.cs
- src/NexusMods.App.UI/WorkspaceSystem/Page/IPageFactoryContext.cs
- src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/PanelTab/IPanelTabViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/PanelTab/PanelTabViewModel.cs
> Add ephemeral page context

- Directory.Build.props
- docs/Contributing.md
- docs/ModWithConfidence.md
- docs/index.md
- mkdocs.yml
- src/NexusMods.App.BuildInfo/CompileConstants.cs
- src/NexusMods.App.UI/Overlays/Updater/UpdaterViewModel.cs
- tests/NexusMods.UI.Tests/Overlays/UpdaterViewTests.cs
Resolves #1006.
I'll probably rework the updater overlay separately.
> Installation docs

- src/NexusMods.App/Program.cs
- src/NexusMods.App/Services.cs
- src/NexusMods.StandardGameLocators/GameLocatorSettings.cs
- src/NexusMods.StandardGameLocators/NexusMods.StandardGameLocators.csproj
- src/NexusMods.StandardGameLocators/Services.cs
> Disable Xbox Game Pass

- src/NexusMods.App.UI/Resources/Language.pl.resx
**## Only for Polish UI.**
**Login dialog on first startup:**
**Authorize:**
> Update Polish translations for login overlays

- docs/index.md
https://repology.org/project/nexusmods-app/history
> Add packaging status badge

- src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml
- src/NexusMods.App.UI/LeftMenu/Items/IconView.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/ButtonStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/ToolTips/ToolTipStyles.axaml
- fix #1485
Couple of more fixes as requested by lausandy
> Fix left menu styling

- src/NexusMods.App.UI/Pages/Downloads/InProgressView.axaml
> Fix "No Downloads" text overlapping DataGrid Header

- src/NexusMods.App.UI/Controls/Banners/BannerSettings.cs
- src/NexusMods.App.UI/Controls/Banners/InfoBanner.cs
- src/NexusMods.App.UI/Resources/Language.Designer.cs
- src/NexusMods.App.UI/Resources/Language.resx
- src/NexusMods.App.UI/Settings/BannerSettings.cs
- src/NexusMods.App.UI/Settings/ServiceExtensions.cs
- src/NexusMods.Icons/IconValues.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Resources/ControlThemes/InfoBannerControlTheme.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Resources/ResourceIndex.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/StylesIndex.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/Banners/InfoBannerStyles.axaml
> Add InfoBanner

- src/NexusMods.App.UI/Controls/Trees/DiffTreeViewModel.cs
- src/NexusMods.App.UI/Controls/Trees/ModFileTreeViewModel.cs
> Auto expand diff view

- src/NexusMods.App.UI/Controls/MarkdownRenderer/MarkdownRendererView.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Resources/Palette/Colors/BrandColors.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Resources/Palette/Colors/ElementColors.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Resources/Palette/Colors/PrimitiveColors.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/HyperlinkStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/StandardButtonStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/ComboBox/ComboBoxStyles.axaml
> primary colors updates

- src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
- src/NexusMods.App.UI/Pages/Settings/SettingsPage.cs
Resolves #1596.
- removes settings from new tab page
- always opens settings in the home workspace
- always opens settings in a new panel
> Update settings behavior

- src/NexusMods.App.UI/Controls/Spine/SpineViewModel.cs
- src/NexusMods.App.UI/LeftMenu/EmptyLeftMenuViewModel.cs
- src/NexusMods.App.UI/LeftMenu/LeftMenuView.axaml.cs
- src/NexusMods.App.UI/TypeFinder.cs
- src/NexusMods.App.UI/Windows/WindowManager.cs
- src/NexusMods.App.UI/WorkspaceSystem/NewTabPage/NewTabPageFactory.cs
- src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/WorkspaceController.cs
> Fix broken data resulting in no panels

- src/NexusMods.App.UI/Overlays/MetricsOptIn/MetricsOptInViewModel.cs
> Fix wording

- src/NexusMods.App.UI/Controls/Spine/Buttons/Icon/IconButton.axaml
- src/NexusMods.App.UI/Controls/Spine/Buttons/Image/ImageButton.axaml
- src/NexusMods.App.UI/Controls/Spine/Spine.axaml
- src/NexusMods.App.UI/Controls/Spine/SpineDesignViewModel.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/SpineButtonStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/SpineDownloadButtonStyles.axaml
As requested by @captainsandypants, fixes #1601
> Sidebar design tweaks

- src/NexusMods.App.UI/Resources/Language.resx
**Resolves** [#1611](https://github.com/Nexus-Mods/NexusMods.App/issues/1611)
> Left menu "Health check" change to "Health Check"

- src/NexusMods.App.UI/Pages/Downloads/InProgressViewModel.cs
As requested by @captainsandypants.
> Hide download speed graph line after 5 ticks

- src/Games/NexusMods.Games.AdvancedInstaller.UI/Resources/Language.pl.resx
- src/Games/NexusMods.Games.FOMOD.UI/Resources/Language.pl.resx
**I tested the fomod UI and Advanced Installer UI from the user's side and updated some texts for better consistency**
> Spelling fix in the Polish UI

- src/NexusMods.App.UI/Resources/Language.pl.resx
**I tested the UI from the user's side and added some text improvements**
> Improvements in the Polish UI

- src/NexusMods.App.UI/Resources/Language.pl.resx
- src/NexusMods.App.UI/Resources/Language.resx
**Fixes [#1625](https://github.com/Nexus-Mods/NexusMods.App/issues/1625)**
> Left menu "In progress" change to "Downloads"

- src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml
- src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/TopBar/TopBarStyles.axaml
- Removed fixed height and set fixed width to match figma Log In button design
- Added a clip to make avatar circular
- Tested with a normal and a premium account login
[Figma Link](https://www.figma.com/design/RGRSmIC4KoVlIosQB5YmQY/%F0%9F%93%B1%F0%9F%A7%B1-App-components?m=auto&node-id=437-2192&t=vTR45Pqi1V8KWQrh-1)
Resolves #1608 and fixes #1552.
> Premium pill in topbar change

- src/NexusMods.App.UI/Pages/LoadoutGrid/ILoadoutGridViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridDesignViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridView.axaml
- src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridView.axaml.cs
- src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridViewModel.cs
- src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPageView.axaml
- src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPageView.axaml.cs
- src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPageViewModel.cs
- src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/IFileOriginsPageViewModel.cs
- src/NexusMods.App.UI/Resources/Language.Designer.cs
- src/NexusMods.App.UI/Resources/Language.resx
- src/NexusMods.Icons/IconValues.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Border/Toolbar.xaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/BareIconStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/ButtonStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/HyperlinkStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/DataGrid/DataGridStyles.axaml
- closes #1591 
- closes #1589 
- Fixed the BareIcon buttons not using IconValues
- Fixed datagrid border shenanigans
- Added Open Library button in Modlist empty state as requested during Desing review:
> Empty Library and Modlist messages

- .github/workflows/build-linux-pupnet.yaml
- .github/workflows/build-windows-pupnet.yaml
- .github/workflows/git-builds.yaml
- .github/workflows/pr-builds.yaml
> Build on PR

- src/NexusMods.App.UI/Controls/ModInfo/ModFiles/ModFilesView.axaml
- src/NexusMods.App.UI/Controls/ModInfo/ModFiles/ModFilesView.axaml.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/ComboBox/ComboBoxStyles.axaml
> Update edit file button design

- src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
> Fix duplicated game widgets for multiple loadouts

- src/Games/NexusMods.Games.StardewValley/Diagnostics.cs
- src/Games/NexusMods.Games.StardewValley/Emitters/DependencyDiagnosticEmitter.cs
- src/Games/NexusMods.Games.StardewValley/Emitters/SMAPIModDatabaseCompatibilityDiagnosticEmitter.cs
- src/Games/NexusMods.Games.StardewValley/Emitters/VersionDiagnosticEmitter.cs
- src/Games/NexusMods.Games.StardewValley/WebAPI/ISMAPIWebApi.cs
- src/Games/NexusMods.Games.StardewValley/WebAPI/SMAPIWebApi.cs
- src/NexusMods.App.UI/DiagnosticSystem/ModReferenceFormatter.cs
> Use mod name from SMAPI API

- src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs
> Remove Activate & Apply text

- src/NexusMods.App.UI/LeftMenu/Items/ApplyControlView.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/StandardButtonStyles.axaml
> Update Standard Primary foreground color

- src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageView.axaml
- src/NexusMods.Icons/IconValues.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Border/Toolbar.xaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/ComboBox/ComboBoxStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml
> Editor page: theme dropdown style

- src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/AddPanelButtonView.axaml
- src/NexusMods.App.UI/WorkspaceSystem/NewTabPage/NewTabPageView.axaml
> Add plus icon to banner

- src/Games/NexusMods.Games.StardewValley/Emitters/MissingSMAPIEmitter.cs
> Fix SMAPI not enabled diagnostic

- src/NexusMods.Icons/IconValue.cs
Suggestion from last PR that wound up being 05b0ab53613b6c71950be16fb8d88e2029b080f2 borked build.
> Undoes 05b0ab53613b6c71950be16fb8d88e2029b080f2

- src/NexusMods.App/StartupMode.cs
- src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationLinux.cs
- src/NexusMods.SingleProcess/CommandLineConfigurator.cs
- src/NexusMods.SingleProcess/NexusMods.SingleProcess.csproj
I highjacked the `CommandLineConfigurator` to handle the case where we get a single URI argument that we can handle.
Resolves #1677.
> Simpler NXM link handling

- src/Examples/Workspaces/001-querying-windows-and-workspaces.cs
- src/Examples/Workspaces/002-opening-new-pages.cs
- src/NexusMods.App.UI/Controls/ModInfo/ModFiles/ModFilesViewModel.cs
- src/NexusMods.App.UI/Controls/Spine/SpineViewModel.cs
- src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs
- src/NexusMods.App.UI/Overlays/AlphaWarning/AlphaWarningViewModel.cs
- src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPageViewModel.cs
- src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
- src/NexusMods.App.UI/Windows/DesignWindowManager.cs
- src/NexusMods.App.UI/Windows/IWindowManager.cs
- src/NexusMods.App.UI/Windows/MainWindowViewModel.cs
- src/NexusMods.App.UI/Windows/WindowManager.cs
- src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/AddPanelDropDownViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/NewTabPage/NewTabPageViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/IWorkspaceController.cs
- src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/WorkspaceController.cs
Makes it much easier to get the currently active Window or Workspace.
> Simplify Window and Workspace API

- src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
> Unmanage Game: Only delete loadouts of the selected game installation

- src/Games/NexusMods.Games.RedEngine/Cyberpunk2077Settings.cs
- src/Games/NexusMods.Games.RedEngine/Cyberpunk2077Synchronizer.cs
- src/Games/NexusMods.Games.StardewValley/StardewValleyLoadoutSynchronizer.cs
- src/Games/NexusMods.Games.StardewValley/StardewValleySettings.cs
- tests/Games/NexusMods.Games.RedEngine.Tests/Cyberpunk2077SynchronizerTests.cs
- tests/Games/NexusMods.Games.StardewValley.Tests/StardewValleySynchronizerTests.cs
> Update Backup setting wording

- src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/WorkspaceController.cs
> Fix lookup exception restorign panel without tabs

- src/NexusMods.App.UI/WorkspaceSystem/Panel/IPanelViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml
- src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml.cs
- src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/Workspace/IWorkspaceViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceViewModel.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/WorkspaceSystem/PanelViewStyles.axaml
Part of #1685. This includes the styles and the concept of a "selected panel". This is still missing the behavior, that'll come in part 2.
https://github.com/user-attachments/assets/5e55808f-f916-46c9-b546-c5d92df24922
> Selected Panel Part #1

- src/Examples/Workspaces/002-opening-new-pages.cs
- src/NexusMods.App.UI/Controls/ModInfo/ModFiles/ModFilesViewModel.cs
- src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Downloads/DownloadsLeftMenuViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Home/HomeLeftMenuViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
- src/NexusMods.App.UI/Overlays/AlphaWarning/AlphaWarningViewModel.cs
- src/NexusMods.App.UI/Pages/Diagnostics/List/DiagnosticListViewModel.cs
- src/NexusMods.App.UI/Pages/Downloads/InProgressViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridViewModel.cs
- src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPageViewModel.cs
- src/NexusMods.App.UI/Pages/Settings/SettingsPage.cs
- src/NexusMods.App.UI/WorkspaceSystem/NewTabPage/NewTabPageViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/Page/IPageFactory.cs
- src/NexusMods.App.UI/WorkspaceSystem/Panel/IPanelViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/IWorkspaceController.cs
- src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/OpenPageBehaviorSettings.cs
- src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/WorkspaceController.cs
Part of #1685. Missing is the left menu updates.
> Selected panel behavior

- src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/References/LoadoutItemGroupReference.cs
- src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/References/ReferenceExtensions.cs
- src/Abstractions/NexusMods.Abstractions.Loadouts/Extensions/LoadoutGroupExtensions.cs
- src/Abstractions/NexusMods.Abstractions.Loadouts/Extensions/LoadoutItemExtensions.cs
- src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/Diagnostics.cs
- src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/Emitters/APathBasedDependencyEmitter.cs
- src/NexusMods.DataModel/Diagnostics/DiagnosticManager.cs
- tests/Games/NexusMods.Games.RedEngine.Tests/Cyberpunk2077DiagnosticTests.cs
- tests/Games/NexusMods.Games.TestFramework/AGameTest.cs
Part of #1763.
Not much to say here, pretty much a straight forward switch to the new format.
> Convert Cyberpunk Diagnostics to Loadout Items

- src/Games/NexusMods.Games.StardewValley/Emitters/ModOverwritesGameFilesEmitter.cs
Forgot to filter out game files.
> Fix diagnostic emitter

- src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
- src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridViewModel.cs
* Fixes a missng boolean negation on the mod enabled check
* Re-enables the "show games/overrides" settings for the mod grid
> Fix apply bugs

- NexusMods.App.sln.DotSettings
- src/Abstractions/NexusMods.Abstractions.Loadouts/Extensions/LoadoutExtensions.cs
> Fix GetEnabledGroups

- src/NexusMods.App.UI/Controls/TopBar/ITopBarViewModel.cs
- src/NexusMods.App.UI/Controls/TopBar/TopBarDesignViewModel.cs
- src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml
- src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml.cs
- src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/PanelTab/IPanelTabViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/PanelTab/PanelTabViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/PanelTab/TabHistory.cs
- src/NexusMods.App.UI/WorkspaceSystem/Workspace/IWorkspaceViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceViewModel.cs
> Add tab history

- src/NexusMods.App.UI/WorkspaceSystem/PanelTab/PanelTabViewModel.cs
- src/NexusMods.App.UI/WorkspaceSystem/PanelTab/TabHistory.cs
- fixes null exception
- fixes forward button being enabled for new panels
- fixes ephemeral pages messing with the history
Part of #1686.
> Tab history fixes

- src/NexusMods.App.UI/Pages/LoadoutGrid/ILoadoutGridViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridViewModel.cs
Part of #1763. I think using `tx.Delete(id, recursive: true)` is what we want here, seems to work.
> Re-add deletion

- Directory.Packages.props
- src/Abstractions/NexusMods.Abstractions.Loadouts/LibraryLinkedLoadoutItem.cs
- src/Abstractions/NexusMods.Abstractions.Loadouts/Loadout.cs
- src/Abstractions/NexusMods.Abstractions.Loadouts/LoadoutItemGroup.cs
- src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/NexusModsLibraryFile.cs
- src/Networking/NexusMods.Networking.NexusWebApi/NexusModsDownloadJob.cs
- src/NexusMods.App.UI/Filters/LoadoutUserFilters.cs
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/NexusMods.App.UI/Pages/ILoadoutDataProvider.cs
- src/NexusMods.App.UI/Pages/LibraryPage/ILibraryViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryItemModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryPage.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/FakeParentLoadoutItemModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/ILoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutItemModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutPage.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LocalFileDataProvider.cs
- src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
- src/NexusMods.App.UI/Services.cs
- src/NexusMods.App.UI/Settings/ExperimentalViewSettings.cs
- src/NexusMods.App.UI/Settings/ServiceExtensions.cs
- src/NexusMods.Library/InstallLoadoutItemJobWorker.cs
Part of #1864, resolves #1911.
> New Library and Loadout pages

- src/NexusMods.App.UI/Pages/LibraryPage/LibraryItemModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutItemModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/DataGrid/DataGridStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/ToggleSwitch/ToggleSwitchStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridStyles.axaml
This isn't complete but has the view elements to then bind commands and stuff to
> Library and Loadout view styling 

- src/Games/NexusMods.Games.AdvancedInstaller/Services.cs
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/ILibraryViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryItemModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/FakeParentLoadoutItemModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/ILoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutItemModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
- src/NexusMods.Library/InstallLoadoutItemJobWorker.cs
Binds the buttons of the toolbar to commands. Almost all commands have been implemented.
Part of #1864.
> Update Library and Loadout functionality

- src/NexusMods.CrossPlatform/Process/ProcessFactory.cs
Please see:
- https://github.com/Nexus-Mods/NexusMods.App/issues/1905#issuecomment-2302503110
and
- https://github.com/Nexus-Mods/NexusMods.App/issues/1905#issuecomment-2302486535
For more details.
fixes #1905
> Fixed: Start all processes with valid stdout/stdin/stderr

- src/NexusMods.App.UI/Controls/ReactiveR3Object.cs
- src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridAdapter.cs
- src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridItemModel.cs
- src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridViewHelper.cs
- src/NexusMods.App.UI/Extensions/R3Extensions.cs
- src/NexusMods.App.UI/Pages/LibraryPage/ILibraryViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/ILoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
Consolidation and cleanup of pages with `TreeDataGrid` related functionality. This keeps the pages focused and slim.
Part of #1864.
> Add `TreeDataGridAdapter`

- src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
- tests/Games/NexusMods.Games.TestFramework/AGameTest.cs
- tests/Games/NexusMods.Games.TestFramework/AIsolatedGameTest.cs
- tests/NexusMods.DataModel.Synchronizer.Tests/GeneralLoadoutManagementTests.SynchronizerIntegrationTests.verified.md
- tests/NexusMods.DataModel.Synchronizer.Tests/GeneralLoadoutManagementTests.cs
- tests/NexusMods.DataModel.Synchronizer.Tests/GeneralModManagementTests.SynchronizerAddAndDisableMods.verified.md
- tests/NexusMods.DataModel.Synchronizer.Tests/GeneralModManagementTests.cs
Follow-up on 
- #1926
since it was already merged.
Added a test for adding and removing mods, using verify. 
Plan would be to add more tests in the future, like adding, removing and changing files, after #1924 is fixed for example.
> Add Synchronizer GeneralModManagementTests

- src/Themes/NexusMods.Themes.NexusFluentDark/Resources/Palette/Colors/PrimitiveColors.axaml
> Design: Update Primitive Colours to Tailwind Defaults

- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/ToggleSwitch/ToggleSwitchStyles.axaml
> Add toggle style for indeterminate state

- docs/developers/decisions/backend/0018-running-tools-on-linux.md
This fixes the PyInstaller issue mentioned in the docs.
> Fix PyInstaller instructions

- NexusMods.App.sln.DotSettings
- src/NexusMods.CrossPlatform/NexusMods.CrossPlatform.csproj
- src/NexusMods.CrossPlatform/Process/AOSInterop.cs
- src/NexusMods.CrossPlatform/Process/ExecutableRuntimeDependency.cs
- src/NexusMods.CrossPlatform/Process/IRuntimeDependency.cs
- src/NexusMods.CrossPlatform/Process/OSInteropLinux.cs
- src/NexusMods.CrossPlatform/Process/OSInteropOSX.cs
- src/NexusMods.CrossPlatform/Process/OSInteropWindows.cs
- src/NexusMods.CrossPlatform/Process/ProcessFactory.cs
- src/NexusMods.CrossPlatform/Process/RuntimeDependencyChecker.cs
- src/NexusMods.CrossPlatform/Process/UpdateDesktopDatabaseDependency.cs
- src/NexusMods.CrossPlatform/Process/XDGOpenDependency.cs
- src/NexusMods.CrossPlatform/Process/XDGSettingsDependency.cs
- src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationLinux.cs
- src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationOSX.cs
- src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationWindows.cs
- src/NexusMods.CrossPlatform/Services.cs
- tests/NexusMods.CrossPlatform.Tests/UpdateDesktopDatabaseDependencyTests.cs
- tests/NexusMods.CrossPlatform.Tests/XDGOpenDependencyTests.cs
- tests/NexusMods.CrossPlatform.Tests/XDGSettingsDependencyTests.cs
Checks whether certain dependencies are installed. The data could be exposed in the UI, but for now this is just being logged.
> Runtime dependency checker

- src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/NexusMods.Abstractions.NexusModsLibrary.csproj
- src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/NexusModsModPageMetadata.cs
- src/Abstractions/NexusMods.Abstractions.Telemetry/NexusMods.Abstractions.Telemetry.csproj
- src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.cs
- src/NexusMods.App.UI/Controls/Trees/LoadoutItemGroupFileTreeViewModel.cs
- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/NexusMods.App.UI/Pages/ILoadoutDataProvider.cs
- src/NexusMods.App.UI/Pages/LibraryPage/FakeParentLibraryItemModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryItemModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/NexusModsModPageLibraryItemModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/FakeParentLoadoutItemModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutItemModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LocalFileDataProvider.cs
- src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
- formatted dates with ticker
- indeterminate state in loadout page (currently broken)
- implements #1971
- can install multiple loadout items at once
> More Library and Loadout page fixes

- src/NexusMods.App.UI/Resources/Language.fr.resx
It's a pretty bare-bone french translation, but it works!
It's complete for now and I will update it with time, making sure it's perfect.
> Added french language

- Directory.Packages.props
- src/Abstractions/NexusMods.Abstractions.Loadouts/Loadout.cs
- src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridAdapter.cs
- src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridItemModel.cs
- src/NexusMods.App.UI/Pages/ILibraryDataProvider.cs
- src/NexusMods.App.UI/Pages/ILoadoutDataProvider.cs
- src/NexusMods.App.UI/Pages/Library/LibraryItemRemover.cs
- src/NexusMods.App.UI/Pages/LibraryPage/ILibraryViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryItemModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/NexusModsModPageLibraryItemModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LocalFileDataProvider.cs
- src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
- adds the remove button to the new library page
- adds a filter to the new library and loadout pages
- fixed an issue with row selection
TODO:
> Remaining functionality for new library and loadout pages

- src/Games/NexusMods.Games.FOMOD.UI/Resources/Language.fr.resx
Sorry, wasn't able to put the 2 files I added into 1 pull request, I'll try to not do this again in the future
> Added french language (NM.GAMES.FOMOD.UI)

- src/NexusMods.App.UI/Pages/LibraryPage/LibraryItemModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutItemModel.cs
> Fix future dates

- src/Networking/NexusMods.Networking.HttpDownloader/HttpDownloadJob.cs
Instead of throwing an exception, we'll just log and reset.
> Fix server not supporting valid range requests

- CHANGELOG.md
Added a surprise bug that was found just before the release to the known issues. (This is already fixed, but won't be in the public version yet!)
> Changelog tweak 0.6.1

- Directory.Packages.props
- src/Abstractions/NexusMods.Abstractions.GameLocators/Stores/GOG/GOGLocatorResultMetadata.cs
- src/Abstractions/NexusMods.Abstractions.Games/RunGameTool.cs
- src/NexusMods.StandardGameLocators/HeroicGogLocator.cs
- src/NexusMods.StandardGameLocators/NexusMods.StandardGameLocators.csproj
- src/NexusMods.StandardGameLocators/Services.cs
- tests/NexusMods.StandardGameLocators.TestHelpers/Services.cs
Part of #1695.
There is an issue with running the game through heroic, as heroic never exists. We'll probably want to track WINE.
> Find GOG games installed with the Heroic launcher

- src/NexusMods.App/Services.cs
> Enable BG3 as supported game

- src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml
I didn't expect this to work, but here we are...
Closes #1822
> Moved tooltip out of border

- Directory.Packages.props
- src/Abstractions/NexusMods.Abstractions.Loadouts/NexusMods.Abstractions.Loadouts.csproj
- src/NexusMods.App.UI/Overlays/Generic/MessageBox/Ok/MessageBoxOkView.axaml.cs
Some of these were bugged or needed testing after Dependabot pointed to them
> Update most of our core deps

- Directory.Packages.props
- src/NexusMods.DataModel/GameRegistry/GameRegistry.cs
- src/NexusMods.StandardGameLocators/HeroicGogLocator.cs
> Resilient game locators and heroic fix

- src/NexusMods.App.UI/LeftMenu/Items/IconDesignViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Items/IconView.axaml
Part of #1733 
- Removed badge fixed width
- Added quick design view model
> Fix for badge width with larger numbers

- src/NexusMods.App.UI/Controls/ReactiveR3Object.cs
- src/NexusMods.App.UI/Controls/TreeDataGrid/IColumnDefinition.cs
- src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridItemModel.cs
- src/NexusMods.App.UI/Extensions/R3Extensions.cs
- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/NexusMods.App.UI/Pages/LibraryPage/ILibraryItemModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/ILibraryItemWithAction.cs
- src/NexusMods.App.UI/Pages/LibraryPage/ILibraryItemWithDownloadedDate.cs
- src/NexusMods.App.UI/Pages/LibraryPage/ILibraryItemWithInstalledDate.cs
- src/NexusMods.App.UI/Pages/LibraryPage/ILibraryItemWithName.cs
- src/NexusMods.App.UI/Pages/LibraryPage/ILibraryItemWithSize.cs
- src/NexusMods.App.UI/Pages/LibraryPage/ILibraryItemWithVersion.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml
Adds a new system for defining columns using `IColumnDefinition`. This PR isn't changing any existing code yet, but it shows how the system would be used.
> TreeDataGrid column definitions

- src/NexusMods.App.UI/Controls/TopBar/ITopBarViewModel.cs
- src/NexusMods.App.UI/Controls/TopBar/TopBarDesignViewModel.cs
- src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml
- src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml.cs
- src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
- src/NexusMods.App.UI/Resources/Language.Designer.cs
- src/NexusMods.App.UI/Resources/Language.resx
Closes #1535 
Premium still working:
Free:
> Free Pill UI Banner

- src/Abstractions/NexusMods.Abstractions.Activities/Percent.cs
> Fix TryParse method in Percent.cs

- src/NexusMods.DataModel/JsonConverters/OptionalConverter.cs
- src/NexusMods.DataModel/Services.cs
Fixes window data serialization.
> Add `Optional<T>` JSON converter

- src/Games/NexusMods.Games.StardewValley/Pipelines.cs
> Use StreamReader

- .github/workflows/build-linux-pupnet.yaml
- .github/workflows/build-windows-pupnet.yaml
- .github/workflows/release.yaml
- **Bump gh-releases action in release CI**
- **Set `target_commitish` in release CI**
- **Simplify `rawVersion` logic in release CI**
I've played around a little in powershell to ensure my syntax is valid, but I haven't tested the workflow as the only way I know to do that is to setup my fork with the required env/secrets/etc and run that. Which I'm far too lazy to do I'm afraid!
If you'd rather work on this internally, I'm happy for you to reference, copy, modify (etc) my PR and/or close this and create your own. No attribution needed.
Fixes #2087
> Set `target_commitish` in release CI

- src/NexusMods.App.UI/Overlays/AlphaWarning/AlphaWarningView.axaml
- src/NexusMods.App.UI/Overlays/AlphaWarning/AlphaWarningView.axaml.cs
- src/NexusMods.App.UI/Overlays/AlphaWarning/AlphaWarningViewModel.cs
- src/NexusMods.App.UI/Overlays/AlphaWarning/IAlphaWarningViewModel.cs
Closes #2200 
Some quick updating of the Alpha warning message to make it simpler and to use styled components
> Alpha warning update

- src/NexusMods.App.UI/Controls/Alerts/Alert.axaml.cs
- src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Resources/ControlThemes/AlertControlTheme.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/EmptyState/EmptyStateStyles.axaml
Fixes Back and Forward buttons being in wrong order
Fixes TextBlock theme in EmptyState
Fixes Alert dismiss button Fill property
> Quick bug fixes while the site is down

- src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionCategory.cs
- src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionMetadata.cs
- src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionRevisionMetadata.cs
- src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Services.cs
- src/Networking/NexusMods.Networking.NexusWebApi/Extensions/FragmentExtensions.cs
- src/Networking/NexusMods.Networking.NexusWebApi/GraphQL/CollectionRevisionInfo.graphql
- src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.Collections.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardViewModel.cs
- tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=SDV.4_11_2024.rocksdb.zip.verified.txt
- tests/NexusMods.DataModel.SchemaVersions.Tests/Schema.verified.md
- Removes deprecated tags
- Adds collection category
- Adds collection revision adult status
- Adds collection total downloads
Part of #2254.
> Add missing collection metadata

- src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionRevisionMetadata.cs
- src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.Collections.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadDesignViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/ICollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardDesignViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardView.axaml
- src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardView.axaml.cs
- src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/Collections/ICollectionCardViewModel.cs
- tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=SDV.4_11_2024.rocksdb.zip.verified.txt
- tests/NexusMods.DataModel.SchemaVersions.Tests/Schema.verified.md
Adds missing metadata and wires up values. No styling.
Part of #2254.
> Collection UI update

- src/Abstractions/NexusMods.Abstractions.Library.Models/LocalFile.cs
- src/NexusMods.Library/AddLocalFileJob.cs
- tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=SDV.4_11_2024.rocksdb.zip.verified.txt
- tests/NexusMods.DataModel.SchemaVersions.Tests/Schema.verified.md
Performance can be improved later, this just puts the data in the DB so we have it.
> MD5 hash every locally added file

- src/Examples/README.md
- src/Examples/TreeDataGrid/README.md
Commit 60cb48066236b5d229eba08c32aa10f3fd2ba106 moved the `UICodingGuidelines.md` file. This PR adjusts sources to changes.
> Update `UICodingGuidelines.md` reference

- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/ILoadOrderItemModel.cs
- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/ILoadOrderViewModel.cs
- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderItemModel.cs
- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderViewModel.cs
- part of #2275 
This should add most of the properties needed in the by the UI to the VM interfaces.
They are stubbed out for now, but should allow creating DesingViewModels in the meantime.
> Load Order: add stub properties to ViewModel interfaces 

- src/Abstractions/NexusMods.Abstractions.Library.Models/LocalFile.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadDesignViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/ICollectionDownloadViewModel.cs
- src/NexusMods.Collections/CollectionDownloader.cs
- tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=SDV.4_11_2024.rocksdb.zip.verified.txt
- tests/NexusMods.DataModel.SchemaVersions.Tests/Schema.verified.md
> Collection download all button

- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadDesignViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/ICollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/ILibraryItemWithAction.cs
- src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionDownloadPage/CollectionDownloadPageStyles.axaml
> Working Required/Optional tabs

- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionDownloadPage/CollectionDownloadPageStyles.axaml
Swapped from StackPanel to using DockPanel
> Fixed scrolling in collection download view

- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderView.axaml
- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderView.axaml.cs
- src/NexusMods.Icons/IconValues.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Border/Toolbar.xaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TabControl/TabControlStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/SortOrderStyles.axaml
Added placeholder toolbar, empty state, working trophy bar and extra icons
Part of #2277
> Load order styling part 2

- src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/SortOrder/RedMod/RedModSortableItemProvider.cs
- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/ILoadOrderItemModel.cs
- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderItemModel.cs
- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderViewModel.cs
- part of #2275 
- Implement sort direction switching functionality
- Setup IsWinnerTop and update based on sorting changes
- Temp populate of IsActive and ModName
> Loadorder v2 tree data grid backend part 5

- src/NexusMods.StandardGameLocators/GameLocatorSettings.cs
> Require restart for toggling Xbox Game Pass support

- src/Abstractions/NexusMods.Abstractions.UI/Extensions/R3Extensions.cs
- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderItemModel.cs
Append items at the end if the indices are negative rather than clamping.
Also ensure updates happen on ui thread
> Loadorder ApplyChanges fixes

- docs/developers/Contributing.md
Some other notes to potentially mention: 
-In my experience, running `git submodule update --init --recursive` didn't fix my build error in Visual Studio, even when I tried running it after deleting the contents of the SMAPI folder
-After I ran the project using Git Bash as well as Command Prompt I would run into the same build error after trying to run the same project in Visual Studio
Other people may have different experiences, which I wanted to be considerate of.
> Added instructions to the developer docs for running the project.

- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridStyles.axaml
Quick fix for the IsActive state showing the 'Is not active' styles
> Fix for IsActive styles

- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderViewModel.cs
Observable wasn't always firing when the count changed
> Fix CanExecute on Up/Down buttons in case of items being removed

- Directory.Packages.props
- NexusMods.App.sln
- src/Abstractions/NexusMods.Abstractions.NexusWebApi/ILoginManager.cs
- src/Networking/NexusMods.Networking.NexusWebApi/LoginManager.cs
- src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
- src/NexusMods.App/Services.cs
- src/NexusMods.Telemetry/Constants.cs
- src/NexusMods.Telemetry/EventDefinition.cs
- src/NexusMods.Telemetry/EventMetadata.cs
- src/NexusMods.Telemetry/EventSender.cs
- src/NexusMods.Telemetry/Events.cs
- src/NexusMods.Telemetry/NexusMods.Telemetry.csproj
- src/NexusMods.Telemetry/Tracking.cs
- src/NexusMods.Telemetry/TrackingService.cs
- tests/NexusMods.Telemetry.Tests/EventSenderTests.cs
- tests/NexusMods.Telemetry.Tests/NexusMods.Telemetry.Tests.csproj
- tests/NexusMods.Telemetry.Tests/Startup.cs
> Implement event tracking

- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.Collections/CollectionDownloader.cs
> Delete collection from Loadouts

- src/NexusMods.App.UI/Controls/MiniGameWidget/MiniGameWidget.axaml.cs
- src/NexusMods.App.UI/Pages/MyGames/MyGamesView.axaml
- src/NexusMods.App.UI/Pages/MyGames/MyGamesView.axaml.cs
Quick bug fix so we show some text when no games are discovered
> Added empty text when no game installs found

- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.Collections/CollectionDownloader.cs
- src/NexusMods.Collections/InstallCollectionDownloadJob.cs
- src/NexusMods.Collections/InstallCollectionJob.cs
- src/NexusMods.Collections/Verbs.cs
- tests/NexusMods.Collections.Tests/CollectionInstallTests.cs
Part of #2254.
- Adds an install job for a single item
- Main job accepts an array of jobs
> Restructure collection install jobs

- src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/WorkspaceSystem/PanelViewStyles.axaml
Fixes a visual bug of main panels. Corners look weird due to square border of header not having corner radius to match parent panel
Fixes #2373
> Fixes panel corner styling

- src/Games/NexusMods.Games.StardewValley/Diagnostics.cs
Small text change so Title and Summary aren't pretty much identical
> Updated title and summary for SMAPI health check

- src/NexusMods.App/Program.cs
Keeps those annoying log statements out of the logs.
> Update logging filters

- src/NexusMods.App.UI/Resources/Language.de.resx
Suggested edit by Taija on Discord.
> German Locale update by Taija

- src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
- src/NexusMods.App.UI/Pages/MyLoadouts/MyLoadoutsPage.cs
- src/NexusMods.App.UI/Pages/MyLoadouts/MyLoadoutsViewModel.cs
Fix for MyGames and MyLoadouts Panel Tab icons not matching the left hand menu
> Updated icons in tab headers

- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/MyLoadoutsView/MyLoadoutsViewStyles.axaml
> Fixed Loadout EmptyState icon

- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/NexusModsFileMetadataLibraryItemModel.cs
- src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
- src/NexusMods.Collections/CollectionDownloader.cs
- src/NexusMods.Collections/InstallCollectionDownloadJob.cs
Resolves #2432, part of #2254.
Allows users to install individual optional downloads. Also makes it so that installed required downloads now show up as installed.
> Installing optional downloads

- src/Abstractions/NexusMods.Abstractions.Telemetry/NexusModsURLBuilder.cs
- src/NexusMods.App.UI/NexusMods.App.UI.csproj.DotSettings
- src/NexusMods.App.UI/Overlays/UpgradeToPremium/UpgradeToPremiumView.axaml
- src/NexusMods.App.UI/Overlays/UpgradeToPremium/UpgradeToPremiumView.axaml.cs
- src/NexusMods.App.UI/Overlays/UpgradeToPremium/UpgradeToPremiumViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadDesignViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/ICollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Services.cs
- src/NexusMods.Icons/IconValues.cs
Resolves #2444, part of #2254.
> Add "Upgrade to Premium"-modal

- src/NexusMods.Library/AddLibraryFileJob.cs
Fixes https://github.com/Nexus-Mods/NexusMods.App/issues/2452
> Fix SMAPI install

- src/NexusMods.App.UI/Controls/Diagnostics/DiagnosticEntryView.axaml
- src/NexusMods.App.UI/Controls/Diagnostics/DiagnosticEntryView.axaml.cs
- src/NexusMods.App.UI/Pages/Diagnostics/Details/DiagnosticDetailsView.axaml
- src/NexusMods.Icons/IconValues.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml
Fixes some UI bugs in Health Check that Laurence found
- Correct severity icons
- Line spacing between Diagnostic Entry text
- Removed unnecessary scrollviewer
> Fixes Health Check UI bugs

- Directory.Packages.props
- src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
- src/NexusMods.CrossPlatform/DesktopPortalConnectionManagerWrapper.cs
- src/NexusMods.CrossPlatform/NexusMods.CrossPlatform.csproj
- src/NexusMods.CrossPlatform/Process/AOSInterop.cs
- src/NexusMods.CrossPlatform/Process/IOSInterop.cs
- src/NexusMods.CrossPlatform/Process/OSInteropLinux.cs
- src/NexusMods.CrossPlatform/Process/OSInteropWindows.cs
- src/NexusMods.CrossPlatform/Services.cs
Resolves https://github.com/Nexus-Mods/NexusMods.App/issues/1676 and related to https://github.com/Nexus-Mods/NexusMods.App/issues/2436.
> Use XDG Desktop Portal to open URIs and files

- src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Expander/ExpanderStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/StylesIndex.axaml
First pass at Expander styling
> Expander styling

- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
- src/NexusMods.Collections/CollectionDownloader.cs
- src/NexusMods.Collections/DownloadCollectionJob.cs
- src/NexusMods.Collections/InstallCollectionDownloadJob.cs
- src/NexusMods.Collections/InstallCollectionJob.cs
- src/NexusMods.Collections/NexusCollectionBundledLoadoutGroup.cs
- src/NexusMods.Collections/Verbs.cs
- src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs
- tests/NexusMods.Collections.Tests/CollectionInstallTests.cs
- tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=SDV.4_11_2024.rocksdb.zip.verified.txt
- tests/NexusMods.DataModel.SchemaVersions.Tests/Schema.verified.md
A collection is now considered "installed" when all required mods have been installed. This PR also allows users to retry an installation.
Part of #2254.
> Rework collection installation status

- src/NexusMods.App.UI/LeftMenu/Items/CollectionLeftMenuItemViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Items/ILeftMenuItemViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Items/ILeftMenuItemWithToggleViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Items/LeftMenuItemDesignViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Items/LeftMenuItemView.axaml
- src/NexusMods.App.UI/LeftMenu/Items/LeftMenuItemView.axaml.cs
- src/NexusMods.App.UI/LeftMenu/Items/LeftMenuItemViewModel.cs
- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- part of #2433 
Collection toggle for now, will add Health check badges in future PR
> Use type based view selection based on `DataTemplates` for `LeftMenuItems`

- src/NexusMods.App.UI/LeftMenu/Items/HealthCheckLeftMenuItemViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Items/LeftMenuItemView.axaml
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuDesignViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml
- part of #2433 
- Closes #1733
I really like how easy it was to add this now
> Add HealthCheck version of LeftMenuItem with badges

- src/NexusMods.App.UI/LeftMenu/Items/CollectionLeftMenuItemViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Items/LeftMenuItemView.axaml
- src/NexusMods.App.UI/LeftMenu/Items/LeftMenuItemViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Items/LeftMenuItemWithCountBadgeViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- part of #2433 
Also did some minor cleanup and fixed a bug with the collection toggle introduced when switching to Compiled two way binding.
> Add new download count badge to Library left menu item

- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutDesignViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutPage.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutView.axaml
- src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutView.axaml.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/ICollectionLoadoutViewModel.cs
- src/NexusMods.App.UI/Services.cs
- src/NexusMods.App.UI/TypeFinder.cs
- src/NexusMods.Icons/IconValues.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Border/Toolbar.xaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionLoadoutPage/CollectionLoadoutPageStyles.axaml
> Add custom collection loadout page

- src/NexusMods.App.UI/LeftMenu/Home/HomeLeftMenuView.axaml
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuDesignViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuView.axaml
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutPage.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
- src/NexusMods.Icons/IconValues.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/LeftMenu/LeftMenuStyles.axaml
Small fixes and tweaks following a click around with @captainsandypants 
- New icons
- Home Menu spacing
- EmptyState change for Library
- Refactored style file
> Small left menu fixes

- src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutView.axaml
- src/NexusMods.App.UI/Pages/LoadoutPage/ILoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
> Add toggle bar to LoadoutView when it is filtered by a collection

- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadDesignViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/ICollectionDownloadViewModel.cs
- src/NexusMods.Collections/CollectionDownloader.cs
- closes #2550 
I think ticket above wasn't quite correct, what was missing was the Install button, not the downloads button.
> Collections: implement Install Optional mods button

- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Menu/MenuItemStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TabControl/TabControlStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionDownloadPage/CollectionDownloadPageStyles.axaml
Quick style update for the toolbar and menu items on the collection download page
Part of #2254
> Collection Toolbar and Menu Item styles

- src/Abstractions/NexusMods.Abstractions.NexusWebApi/ILoginManager.cs
- src/Networking/NexusMods.Networking.NexusWebApi/LoginManager.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
> Fix Collection "install all" button behaviour when logged out

- src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardDesignViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardView.axaml
- src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardView.axaml.cs
- src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/Collections/ICollectionCardViewModel.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionCards/CollectionCardStyles.axaml
Also fixed a style that wasn't selecting properly
> Add revision number to Collection Card

- src/Abstractions/NexusMods.Abstractions.Games/AGame.cs
- src/Abstractions/NexusMods.Abstractions.Games/IGame.cs
- src/Abstractions/NexusMods.Abstractions.Library/ILibraryService.cs
- src/Games/NexusMods.Games.StardewValley/StardewValley.cs
- src/NexusMods.Collections/FallbackCollectionDownloadInstaller.cs
- src/NexusMods.Collections/InstallCollectionDownloadJob.cs
- src/NexusMods.Collections/InstallCollectionJob.cs
- src/NexusMods.Library/InstallLoadoutItemJob.cs
- src/NexusMods.Library/LibraryService.cs
> Use custom fallback installer for collection installs

- src/Abstractions/NexusMods.Abstractions.Collections/Json/Mod.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadDesignViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/ICollectionDownloadViewModel.cs
> Show instructions of required and optional mods

- src/NexusMods.App.UI/Extensions/OptionalExtensions.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryComponents.cs
> Fix crash when sorting by Action

- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadDesignViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TabControl/TabControlStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionDownloadPage/CollectionDownloadPageStyles.axaml
Styling of Additional Instructions tab on the Collection Download page.
[Figma link
](https://www.figma.com/design/5LmVL8YpgDHFSFA76fgCZA/%F0%9F%93%B1-Mod-library?node-id=284-1336&m=dev)
Please note that this won't show the last minute tweaks from @captainsandypants
Part of https://github.com/Nexus-Mods/NexusMods.App/issues/2341.
> Collection instruction styling

- src/NexusMods.DataModel.SchemaVersions/ITransactionalMigration.cs
- src/NexusMods.DataModel.SchemaVersions/MigrationService.cs
For simpler migrations we can use this vs the scanning migrations
> Add ITransactionalMigration.cs

- src/NexusMods.Telemetry/EventSender.cs
- tests/NexusMods.Telemetry.Tests/EventSenderTests.cs
Adds OS information to events.
> Provider user-agent

- src/Abstractions/NexusMods.Abstractions.Collections/NexusCollectionBundledLoadoutGroup.cs
- src/Abstractions/NexusMods.Abstractions.Collections/NexusCollectionItemLoadoutGroup.cs
- src/Abstractions/NexusMods.Abstractions.Collections/NexusCollectionReplicatedLoadoutGroup.cs
- src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/NexusMods.Abstractions.NexusModsLibrary.csproj
- src/NexusMods.Collections/InstallCollectionDownloadJob.cs
- src/NexusMods.Collections/Services.cs
- src/NexusMods.DataModel.SchemaVersions/MigrationService.cs
- src/NexusMods.DataModel.SchemaVersions/Migrations/_0002_NexusCollectionItem.cs
- src/NexusMods.DataModel.SchemaVersions/NexusMods.DataModel.SchemaVersions.csproj
- src/NexusMods.DataModel.SchemaVersions/Services.cs
- tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=SDV.4_11_2024.rocksdb.zip.verified.txt
- tests/NexusMods.DataModel.SchemaVersions.Tests/Schema.verified.md
- Added missing library link for mods installed with predefined FOMOD choices
- Adds new model for replicated items
- Updates model for bundled items
- Adds new model for all items containing a reference to the original download and whether the item is required or optional
Required for #2598.
> Add missing attributes and models for collections

- src/Abstractions/NexusMods.Abstractions.Resources.DB/IdentifierLoader.cs
- src/Abstractions/NexusMods.Abstractions.Resources/NexusMods.Abstractions.Resources.csproj
- src/NexusMods.App.UI/ImagePipelines.cs
> Provide fallback value for optional attributes

- src/NexusMods.App.UI/Controls/TreeDataGrid/ColumnContentControl.cs
- src/NexusMods.App.UI/Pages/ILoadoutDataProvider.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutComponents.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/TreeDataGridLoadoutResources.axaml
Part of #2598.
Shows a lock icon for required mods of collections in the loadout views for now.
> Add locked component for loadout items

- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Menu/MenuItemStyles.axaml
Small tweaks so that correct font themes are used in MenuItem
> Menu restyling

- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridBaseStyles.axaml
> Fixes Mod files no longer having darker row colors

- src/NexusMods.App.UI/Controls/GameWidget/GameWidget.axaml
- src/NexusMods.App.UI/Pages/Diagnostics/Details/DiagnosticDetailsView.axaml
- src/NexusMods.App.UI/Pages/TreeDataGridSharedResources.axaml
- src/NexusMods.App.UI/Resources/Language.Designer.cs
- src/NexusMods.App.UI/Resources/Language.resx
- src/NexusMods.App.UI/WorkspaceSystem/PanelTabHeader/PanelTabHeaderView.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Border/Toolbar.xaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/LeftMenuNavButtonStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Separator/SeparatorStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/SharedStyles.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/StylesIndex.axaml
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/LeftMenu/LeftMenuStyles.axaml
- Adds a tooltip to the removing a game button on my games page
- Changes mod file icon to outlined version
- Changes lefthand menu seperator color
- Removes lefthand menu active and selected state text theme
- Left align buttons in toolbars
- Changes panel tab titles text theme
- Remove unused buttons on health check details view
All checked with @captainsandypants
Part of #2652
> Various UI tweaks

- src/Abstractions/NexusMods.Abstractions.Games.FileHashes/IFileHashesService.cs
- src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
- src/NexusMods.Games.FileHashes/FileHashesService.cs
- tests/NexusMods.StandardGameLocators.TestHelpers/StubbedFileHasherService.cs
> Allow games with no version data

- src/NexusMods.Games.FileHashes/FileHashesService.cs
This adds a guid to the folder names in the filehashes databases directory. This reduces the chances that race conditions can cause strange IO errors. 
Fixes #2651
> Use guids in the FileHashesService to reduce IO collisions

- src/NexusMods.App.UI/Controls/Navigation/NavigationControl.cs
> Prevent rare exception on Navigation buttons presses

- src/Games/NexusMods.Games.StardewValley/Emitters/SMAPIGameVersionDiagnosticEmitter.cs
> Recommend latest supported SMAPI version for game version

- src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
> Open Library when managing game

- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/ItemContentsFileTree/ItemContentsFileTreePage.cs
- src/NexusMods.App.UI/Pages/ItemContentsFileTree/ItemContentsFileTreeViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/Sorting/LoadOrdersWIPPage.cs
- src/NexusMods.App.UI/Pages/TextEdit/TextEditorPage.cs
- src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageView.axaml.cs
- src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageViewModel.cs
- Closes #2694
- Also removes Load Order WIP entry from New Tab Page (part of #2620 )
> Add readonly mode for View Mod Contents Filetree view

- src/Games/NexusMods.Games.StardewValley/Emitters/Helpers.cs
> Allow non standard versions

- src/Abstractions/NexusMods.Abstractions.Resources/Resource.cs
- src/NexusMods.App.UI/Controls/MarkdownRenderer/MarkdownRendererViewModel.cs
- src/NexusMods.App.UI/ImagePipelines.cs
- src/NexusMods.Media/SvgLoader.cs
> Fix SVG loading in markdown image pipeline

- src/NexusMods.App.UI/Pages/ILibraryDataProvider.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
- src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
They were never used and just added unnecessary observables.
> Remove observables from LibraryFilter

- src/NexusMods.App.UI/ExperimentalSettings.cs
- src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
- src/NexusMods.App/Services.cs
Resolves #2313.
Before:
After:
> Hide unsupported games from My Games

- src/NexusMods.Games.FileHashes/Emitters/NoWayToSourceFilesOnDisk.cs
> Hide "Game Files are not backed up" diagnostic for now

- src/NexusMods.App.UI/Pages/ObservableInfo/ObservableInfoPageView.axaml
- src/NexusMods.App.UI/Pages/ObservableInfo/ObservableInfoPageView.axaml.cs
- src/NexusMods.App.UI/Pages/ObservableInfo/ObservableInfoPageViewModel.cs
Adds selection and detailed information about the selected item with both a slim and a full stack trace.
Also added a pie chart for the top 10 most used types.
> Improve observable tracker page

- src/NexusMods.Collections/InstallCollectionJob.cs
> Use collection name

- Directory.Packages.props
- src/Games/NexusMods.Games.StardewValley.SMAPI/NexusMods.Games.StardewValley.SMAPI.csproj
- Avalonia from `11.2.3` to `11.2.4`
- DynamicData from `9.0.4` to `9.1.2`
- SMAPI from `4.1.7` to `4.1.10`
> Upgrade important dependencies

- src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
- tests/NexusMods.DataModel.Synchronizer.Tests/GeneralFileManagementTests.SynchronizerFileManagementTest.verified.md
> Synchronizer: Put file modifications in override instead of replacing

- src/Abstractions/NexusMods.Abstractions.MnemonicDB.Analyzers/TreeAnalyzer.cs
Avoid pushing already seen entity references onto the remaining stack
> TreeAnalyzer perf

- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
- src/NexusMods.App.UI/Pages/ILibraryDataProvider.cs
- src/NexusMods.App.UI/Pages/LocalFileDataProvider.cs
- src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
Fixes #2728. This doesn't deal with #2750.
> Fix library count

- src/NexusMods.CrossPlatform/Process/OSInteropWindows.cs
> Fix exception when opening logs folder on windows

- src/NexusMods.App/Startup.cs
Fixes #2799. See #2799 for details.
> Disable DBus menu for X11

- src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridItemModel.cs
- src/NexusMods.App.UI/Pages/BundledDataProvider.cs
- src/NexusMods.App.UI/Pages/LocalFileDataProvider.cs
> Fix object disposed exceptions when expanding bundled and local mods

- src/Games/NexusMods.Games.StardewValley/Emitters/DependencyDiagnosticEmitter.cs
> Select highest installed version for SDV dependency diagnostics

- src/Abstractions/NexusMods.Abstractions.Logging/NexusMods.Abstractions.Logging.csproj
- src/NexusMods.App.UI/Windows/MainWindowViewModel.cs
- src/NexusMods.App/Program.cs
- src/NexusMods.Telemetry/ExceptionData.cs
- src/NexusMods.Telemetry/ITrackingDataSender.cs
- src/NexusMods.Telemetry/NexusMods.Telemetry.csproj
- src/NexusMods.Telemetry/RedactUtils.cs
- src/NexusMods.Telemetry/Tracking.cs
- src/NexusMods.Telemetry/TrackingData.cs
- src/NexusMods.Telemetry/TrackingDataSender.cs
- src/NexusMods.Telemetry/TrackingService.cs
- tests/NexusMods.Telemetry.Tests/TrackingDataSenderTests.cs
Sends exceptions via telemetry.
> Track exceptions

- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionComponents.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutComponents.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/TreeDataGridLoadoutResources.axaml
- Resolves #2838
Parent items open the first child id they have.
Also made some changes to address ObjectDisposedExceptions
> Support opening Collection page from collection EnabledStates buttons

- src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridAdapter.cs
- src/NexusMods.App.UI/Windows/MainWindow.axaml
- src/NexusMods.App.UI/Windows/MainWindow.axaml.cs
- src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceView.axaml.cs
- src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceViewModel.cs
Properly deactivates VMs when switching workspaces instead of keeping them alive all the time.
> Deactive VMs when switching workspaces

- src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
> Make View button open last applied loadout in My Games page

- src/NexusMods.App.UI/LeftMenu/Items/CollectionLeftMenuItemViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Items/LeftMenuItemView.axaml
- src/NexusMods.App.UI/LeftMenu/Items/LeftMenuItemViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionComponents.cs
> Show collections in left menu that haven't been installed yet

- src/NexusMods.App.UI/Controls/TopBar/ITopBarViewModel.cs
- src/NexusMods.App.UI/Controls/TopBar/TopBarDesignViewModel.cs
- src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
- src/NexusMods.App.UI/Overlays/Login/NexusLoginOverlayService.cs
Allows the user to re-try logging in without having to wait for the previous job to timeout.
Fixes #2062.
> Reset login requests

- src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
Related to #2765. Sometimes the app doesn't close properly after closing the main window. Using the debugger I could see that the main thread was waiting for the host to be disposed. A long-running task fetching the user avatar was also blocked on something.
I couldn't get more information out of my debugging session, but my guess is that something is blocking the host from being disposed properly.
> Prevent long-running task from keeping app alive

- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/NexusMods.App.UI/Overlays/ManageGameWarning/IManageGameWarningViewModel.cs
- src/NexusMods.App.UI/Overlays/ManageGameWarning/ManageGameWarningView.axaml
- src/NexusMods.App.UI/Overlays/ManageGameWarning/ManageGameWarningView.axaml.cs
- src/NexusMods.App.UI/Overlays/ManageGameWarning/ManageGameWarningViewModel.cs
- src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
- src/NexusMods.App.UI/Resources/Language.Designer.cs
- src/NexusMods.App.UI/Resources/Language.resx
- src/NexusMods.App.UI/Services.cs
- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/MessageBox/MessageBoxStyles.axaml
Draft because I'm still checking the code.
fixes #2910
- https://github.com/Nexus-Mods/NexusMods.App/issues/2910
> Added: 'Warning' Dialog for Managing Game

- src/NexusMods.App.UI/Overlays/ManageGameWarning/ManageGameWarningView.axaml
Swapped to using `StandardButton` and `StaticResource`
> UI tweaks to fix the manage game warning overlay

- src/Games/NexusMods.Games.AdvancedInstaller.UI/AdvancedManualInstallerUI.cs
- src/Games/NexusMods.Games.AdvancedInstaller.UI/Window/AdvancedInstallerWindowViewModel.cs
- src/Games/NexusMods.Games.AdvancedInstaller/AdvancedManualInstaller.cs
- src/Games/NexusMods.Games.AdvancedInstaller/IAdvancedInstallerHandler.cs
- src/Games/NexusMods.Games.AdvancedInstaller/Services.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
> Don't show unsupported step when opening advanced installer directly

- src/NexusMods.CrossPlatform/Process/RuntimeDependencyChecker.cs
Fixes #2865.
Updates the runtime dependency checker to be a `BackgroundService` that doesn't run on the main thread.
> Make the runtime dependency checker non-blocking

- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
> Hide optional tab if there are no optional downloads

- src/NexusMods.App.UI/Controls/TreeDataGrid/AValueComponent.cs
- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGrid/ILoadOrderDataProvider.cs
- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGrid/LoadOrderComponents.cs
- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGrid/LoadOrderDataProvider.cs
- src/NexusMods.App.UI/Services.cs
> `LoadOrderDataProvider`: provide canExecute observables for Up/Down commands

- src/Abstractions/NexusMods.Abstractions.Resources.IO/FileStoreLoader.cs
- src/Games/NexusMods.Games.FOMOD.UI/Step/GuidedInstallerStepViewModel.cs
> Fix `FileStoreLoader` not reading until end of Stream

- src/Abstractions/NexusMods.Abstractions.Games/ILoadoutSortableItemProvider.cs
- src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/SortOrder/RedMod/RedModSortableItemProvider.cs
- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderViewModel.cs
- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGrid/LoadOrderDataProvider.cs
> Add ref counted observable changeset for SortableItems to SortableItemsProvider

- src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
While investigating #2935 I noticed some stuff wasn't used in the `CleanDirectories` method and did a pass to clean it up a bit.
In particular it used to take in an `IEnumerable<(GamePath GamePath, AbsolutePath ResolvedPath)>`, which has been simplified to just `IEnumerable<GamePath>`.
Also the `foldersWithDeletedFiles` hash sets were getting filled with file paths of the deleted entries, rather than their parent folder paths, meaning that there was no deduplication on that hash set.
> CleanupDirectories improvements

- src/Games/NexusMods.Games.StardewValley/Emitters/DependencyDiagnosticEmitter.cs
> Create diagnostic even if the API doesn't return data

- src/NexusMods.App.UI/Overlays/Updater/UpdaterView.axaml.cs
> Display only 3 version fields

- docs/users/games/index.md
Thanks for the reminder in https://github.com/Nexus-Mods/NexusMods.App/issues/2994
> Uncommented warning for unsupported games.

- src/NexusMods.StandardGameLocators/GameLocatorSettings.cs
Resolves #2962.
Related to #1477, #1476, #1540, #2961.
> Remove Xbox Game Pass toggle from settings in release builds

- src/NexusMods.App/Services.cs
Accidentally broke our CLI because of DI.
> Fix CLI services

- .github/workflows/stale.yaml
Closes #3022.
- Issues: Stale after 7 days and then auto-closed after 14 days.
- PRs: Stale after 7 days and never auto-closed.
> Add workflow for stale issues and PRs

- src/Games/NexusMods.Games.StardewValley/Installers/GenericInstaller.cs
- tests/Games/NexusMods.Games.StardewValley.Tests/GenericInstallerTests.Test_Mods_modId=1536_fileId=98230.verified.txt
- tests/Games/NexusMods.Games.StardewValley.Tests/GenericInstallerTests.cs
> Skip manifest files in nested SMAPI mods

- src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/Toolbar/ToolbarStyles.axaml
Fix an error in the logs about this binding not working.
> Fix binding error

- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
Resolves #2913, verify with [High-Res Graphics Pack - MAXIMUM](https://next.nexusmods.com/cyberpunk2077/collections/g0tcm4) or [High-Res Graphics Pack - PERFORMANCE Revision 38](https://www.nexusmods.com/games/cyberpunk2077/collections/devnx1/revisions/38)
> Add empty state for when collection has no required downloads

- src/NexusMods.App.UI/Windows/MainWindowViewModel.cs
> Fix opening collection download page in the wrong workspace

- src/Networking/NexusMods.Networking.NexusWebApi/Auth/ApiKeyMessageFactory.cs
- src/Networking/NexusMods.Networking.NexusWebApi/Auth/OAuth2MessageFactory.cs
- src/Networking/NexusMods.Networking.NexusWebApi/BaseHttpMessageFactory.cs
- src/NexusMods.App.BuildInfo/ApplicationConstants.cs
> Provide Nexus Mods API headers

- src/Games/NexusMods.Games.FOMOD.UI/Step/GuidedInstallerStepView.axaml.cs
- src/Games/NexusMods.Games.FOMOD.UI/Step/GuidedInstallerStepViewModel.cs
Another PR to fix the crash where the image gets disposed and then Avalonia tries to access it.
> Fix image getting disposed

- docs/developers/development-guidelines/Projects.md
- mkdocs.yml
Adds documentation for project organization and naming.
> Add C# project guidelines

- src/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionMetadata.cs
- src/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionRevisionMetadata.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardViewModel.cs
- src/NexusMods.Networking.NexusWebApi/GraphQL/CollectionRevisionInfo.graphql
- src/NexusMods.Networking.NexusWebApi/NexusModsLibrary.Collections.cs
- tests/NexusMods.DataModel.SchemaVersions.Tests/Schema.verified.md
> Use recent collection ratings

- docs/users/SystemRequirements.md
- docs/users/faq/LinuxProtocolRegistration.md
- mkdocs.yml
- src/NexusMods.Abstractions.NexusWebApi/Types/NXMProtocolRegistrationCheck.cs
- src/NexusMods.Abstractions.NexusWebApi/Types/NXMProtocolRegistrationTest.cs
- src/NexusMods.Abstractions.NexusWebApi/Types/NXMUrl.cs
- src/NexusMods.App.Cli/CliMessages.cs
- src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs
- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/NexusMods.App.UI/NexusMods.App.UI.csproj.DotSettings
- src/NexusMods.App.UI/Pages/ProtocolRegistration/IProtocolRegistrationTestPageViewModel.cs
- src/NexusMods.App.UI/Pages/ProtocolRegistration/ProtocolRegistrationTestPage.cs
- src/NexusMods.App.UI/Pages/ProtocolRegistration/ProtocolRegistrationTestPageView.axaml
- src/NexusMods.App.UI/Pages/ProtocolRegistration/ProtocolRegistrationTestPageView.axaml.cs
- src/NexusMods.App.UI/Pages/ProtocolRegistration/ProtocolRegistrationTestPageViewModel.cs
- src/NexusMods.App.UI/Services.cs
- src/NexusMods.App.UI/TypeFinder.cs
- src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationLinux.cs
> Remove automatic protocol registration on Linux

- src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGridLoadOrderResources.axaml
- src/NexusMods.Themes.NexusFluentDark/Styles/UserControls/Sorting/LoadOrderStyles.axaml
Reworked the markup so translucent borders can be used correctly
> Adds translucent borders to Load Order thumbnails

- src/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
- src/NexusMods.Abstractions.Loadouts/LoadoutKind.cs
Resolves #2972 by simply hiding loadouts that are being deleted.
> Hide loadouts when unmanaging the game

- src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
> Direct users to missing games issue template

- src/NexusMods.App.UI/WorkspaceSystem/PanelTabHeader/PanelTabHeaderView.axaml.cs
> Fix tabs getting closed with normal clicks instead of middle clicks

- src/NexusMods.Abstractions.Collections/Json/CollectionInfo.cs
- src/NexusMods.Abstractions.Library/ILibraryService.cs
- src/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionMetadata.cs
- src/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionRevisionMetadata.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutViewModel.cs
- src/NexusMods.Collections/CollectionCreator.cs
- src/NexusMods.Collections/Verbs.cs
- src/NexusMods.Library/AddDownloadJob.cs
- src/NexusMods.Library/AddLibraryFileJob.cs
- src/NexusMods.Library/AddLocalFileJob.cs
- src/NexusMods.Library/LibraryService.cs
Only available in release, no tests yet or anything special. This is just for testing the limitations and an initial implementation.
This PR updates a bunch of models but only for marking attributes as optional.
> Simple collection creation from CLI

- Directory.Packages.props
- src/NexusMods.App.UI/NexusMods.App.UI.csproj
- src/NexusMods.Icons/NexusMods.Icons.csproj
- tests/NexusMods.UI.Tests/Framework/AvaloniaApp.cs
- Closes #3146 
Tested running the app, didn't notice anything strange. 
Ran the tests, some of the network tests failed the first run, but the API is under maintenance at the moment so that might be expected. Running the tests again made them pass fine.
> Update Avalonia and Microsoft dependencies

- src/NexusMods.Abstractions.Resources.DB/PersistedDbResourceLoader.cs
- src/NexusMods.App.UI/ImagePipelines.cs
> Expire persisted resources

- src/NexusMods.App.UI/WorkspaceSystem/PanelResizer/PanelResizerView.axaml
- src/NexusMods.App.UI/WorkspaceSystem/PanelResizer/PanelResizerView.axaml.cs
Updated drag handles for panel resizing. Been approved by @captainsandypants.
> Panel resizing improvements

- src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationLinux.cs
Re-adds automatic protocol registration on Linux until we don't need it anymore.
> Revert parts of #3088

- src/NexusMods.Abstractions.GameLocators/WineParser.cs
- src/NexusMods.StandardGameLocators/SteamLocator.cs
- tests/NexusMods.StandardGameLocators.Tests/WineParserTests.cs
> Fix `WINEDLLOVERRIDES` parsing for Steam launch options

- src/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
- src/NexusMods.Games.RedEngine/Cyberpunk2077/Cyberpunk2077Synchronizer.cs
- src/NexusMods.Games.RedEngine/Cyberpunk2077/Emitters/MissingRedModEmitter.cs
Both should now report the same results. Fixes #3111.
> Run missing red mods emitter and synchronizer off same data

- NexusMods.App.sln.DotSettings
- src/NexusMods.Abstractions.NexusWebApi/IHttpMessageFactory.cs
- src/NexusMods.Collections/CollectionCreator.cs
- src/NexusMods.Collections/Verbs.cs
- src/NexusMods.Networking.NexusWebApi/Auth/OAuth2MessageFactory.cs
- src/NexusMods.Networking.NexusWebApi/BaseHttpMessageFactory.cs
- src/NexusMods.Networking.NexusWebApi/Extensions/FragmentExtensions.cs
- src/NexusMods.Networking.NexusWebApi/GraphQL/CollectionRevisionInfo.graphql
- src/NexusMods.Networking.NexusWebApi/GraphQL/CommonFragments.graphql
- src/NexusMods.Networking.NexusWebApi/GraphQL/CreateCollection.graphql
- src/NexusMods.Networking.NexusWebApi/NexusApiClient.cs
- src/NexusMods.Networking.NexusWebApi/NexusModsLibrary.Collections.cs
- src/NexusMods.Networking.NexusWebApi/NexusModsLibrary.cs
- src/NexusMods.Networking.NexusWebApi/PresignedUploadUrl.cs
- src/NexusMods.Networking.NexusWebApi/Services.cs
Adds functionality to upload collection archives and upload new collections with the GraphQL API. It also turns out that we never authenticated when using GraphQL...
> Upload new collections to Nexus Mods

- src/NexusMods.Games.MountAndBlade2Bannerlord/Bannerlord.cs
- src/NexusMods.Games.RedEngine/Cyberpunk2077/Cyberpunk2077Game.cs
This does not work without game hashing/backup strategy in place.
https://github.com/Nexus-Mods/NexusMods.App/issues/3117
> Commented out Epic Games detection for CP2077 and Bannerlord

- src/NexusMods.Abstractions.NexusWebApi/ILoginManager.cs
- src/NexusMods.Collections/CollectionDownloader.cs
- src/NexusMods.Networking.NexusWebApi/LoginManager.cs
Makes sure we have up-to-date information on the premium status.
> Fetch user info for collection downloads

- CHANGELOG.md
Updated date and added summary line for changelog
> Changelog 0.11.1

- src/NexusMods.Abstractions.Games/RunGameTool.cs
- src/NexusMods.Abstractions.Loadouts/Models/DiskStateExtensions.cs
- src/NexusMods.Games.RedEngine/Cyberpunk2077/RunCyberpunk2077Game.cs
- src/NexusMods.Games.RedEngine/RedModDeployTool.cs
- src/NexusMods.Games.RedEngine/Resources/Cyberpunk2077/deploy_redmod.bat
- src/NexusMods.Games.RedEngine/Services.cs
> Backport redmod fixes

- Directory.Packages.props
- src/NexusMods.Abstractions.GameLocators/Stores/GOG/GOGLocatorResultMetadata.cs
- src/NexusMods.Abstractions.Jobs/NexusMods.Abstractions.Jobs.csproj
- src/NexusMods.Abstractions.Loadouts/NexusMods.Abstractions.Loadouts.csproj
- src/NexusMods.Abstractions.MnemonicDB.Attributes/NexusMods.Abstractions.MnemonicDB.Attributes.csproj
- src/NexusMods.Abstractions.Settings/NexusMods.Abstractions.Settings.csproj
- src/NexusMods.Sdk/NexusMods.Sdk.csproj
- tests/NexusMods.StandardGameLocators.TestHelpers/Services.cs
- Update `NexusMods.Paths` from `0.19.0` to `0.19.1`
- Update `NexusMods.MnemonicDB` from `0.13.0` to `0.13.1`
- Update `NexusMods.Hashing.xxHash3` from `3.0.3` to `3.0.4`
- Update `GameFinder` from `4.7.0` to `4.7.2`, fixes #3211
- Update `TransparentValueObjects` from `1.0.2` to `1.1.0` and fixed references so no more warnings
> Upgrade dependencies

- tests/Games/NexusMods.Games.RedEngine.Tests/RedModDeployToolTests.cs
They seem to be passing CI so I'd merge them in for now
> Re-enable load order tests 

- src/NexusMods.Telemetry/TrackingDataSender.cs
- tests/NexusMods.Telemetry.Tests/TrackingDataSenderTests.cs
> Use application version as error category

- src/NexusMods.App.UI/LeftMenu/Items/LeftMenuItemView.axaml
- src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutView.axaml
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml
- src/NexusMods.App.UI/Pages/LoadoutPage/TreeDataGridLoadoutResources.axaml
- src/NexusMods.App.UI/Resources/Language.Designer.cs
- src/NexusMods.App.UI/Resources/Language.resx
Closes https://github.com/Nexus-Mods/NexusMods.App/issues/3273
> Add Tooltips to Toggles

- src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationLinux.cs
- tests/NexusMods.CrossPlatform.Tests/ProtocolRegistrationLinuxTests.cs
Workaround for 
-  #3293
Need urgent merge before next release.
> Added: Workaround around xdg-utils 'generic' fallback in protocol handlers

- src/NexusMods.App.UI/LeftMenu/Items/LeftMenuItemViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Items/NewCollectionViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Loadout/ILoadoutLeftMenuViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuDesignViewModel.cs
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuView.axaml
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuView.axaml.cs
- src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
- src/NexusMods.Collections/CollectionCreator.cs
- src/NexusMods.Networking.NexusWebApi/GraphQL/CommonFragments.graphql
- src/NexusMods.Networking.NexusWebApi/GraphQL/CreateCollection.graphql
- src/NexusMods.Networking.NexusWebApi/NexusModsLibrary.Collections.cs
- src/NexusMods.Networking.NexusWebApi/PresignedUploadUrl.cs
Part of #3118.
This adds a new left menu item to the loadout left menu for creating a new collection.
> Add new-collection left menu item

- src/NexusMods.Abstractions.Settings/APropertyValueContainer.cs
- src/NexusMods.Abstractions.Settings/ISettingsPropertyUIDescriptor.cs
- src/NexusMods.Abstractions.Settings/IValueContainer.cs
- src/NexusMods.Abstractions.Settings/SettingsBuilder/IPropertyUIBuilder.cs
- src/NexusMods.App.UI/Controls/Settings/SettingEntries/SettingEntryDesignViewModel.cs
- src/NexusMods.App.UI/Controls/Settings/SettingEntries/SettingEntryView.axaml.cs
- src/NexusMods.Settings/PropertyBuilderOutput.cs
- src/NexusMods.Settings/SettingsPropertyUIDescriptor.cs
- src/NexusMods.Settings/SettingsUIBuilder.cs
Adds a new API for having dynamic setting descriptions:
> Add dynamic setting descriptions

- Directory.Packages.props
- Fixes #3393
- Fixes #3390
- Fixes #3368
> Upgrade GameFinder to 4.7.3

- src/NexusMods.Networking.NexusWebApi/ClientConfig.cs
> Fix endpoints

- src/NexusMods.App.UI/Pages/LoadoutPage/ILoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
Part of #3118.
Button on the toolbar was previously not bind to anything.
> Open collection page

- src/NexusMods.Abstractions.NexusWebApi/IGameDomainToGameIdMappingCache.cs
- src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/ManualDownloadRequiredOverlay.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
- src/NexusMods.Collections/CollectionCreator.cs
- src/NexusMods.Collections/CollectionDownloader.cs
- src/NexusMods.Games.TestHarness/Verbs/StressTest.cs
- src/NexusMods.Networking.NexusWebApi/NexusMods.Networking.NexusWebApi.csproj
- src/NexusMods.Networking.NexusWebApi/NexusModsLibrary.Collections.cs
- src/NexusMods.Networking.NexusWebApi/NexusModsLibrary.cs
- src/NexusMods.Networking.NexusWebApi/RunUpdateCheck.cs
- src/NexusMods.Networking.NexusWebApi/Services.cs
- src/NexusMods.Networking.NexusWebApi/V1Interop/GameDomainToGameIdMappingCache.cs
- src/NexusMods.Networking.NexusWebApi/V1Interop/GameMetadata.cs
- src/NexusMods.Networking.NexusWebApi/V1Interop/LocalMappingCache.cs
- tests/Networking/NexusMods.Networking.NexusWebApi.Tests/LocalMappingCacheTests.cs
Downloads [games.json](https://data.nexusmods.com/file/nexus-data/games.json) at build time for a local mapping cache that uses `FrozenDictionary` to provide the best performance at runtime.
We'll fallback to the mapping cache that does API queries if we can't find the data in the local cache.
> Add local mapping cache

- src/Examples/R3/MovingToR3ViewModels.cs
- src/Examples/R3/R3Binds.cs
- src/NexusMods.UI.Sdk/Extensions/R3Extensions.cs
- src/NexusMods.UI.Sdk/IR3View.cs
- src/NexusMods.UI.Sdk/NexusMods.UI.Sdk.csproj
- src/NexusMods.UI.Sdk/NexusMods.UI.Sdk.csproj.DotSettings
- src/NexusMods.UI.Sdk/R3UserControl.cs
- src/NexusMods.UI.Sdk/R3Window.cs
Also includes examples on how to move from ReactiveUI to R3.
> Add R3 view helpers and extension methods

- src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridAdapter.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml.cs
- src/NexusMods.Telemetry/Events.cs
- Part of #3206 
- Improve Ctrl + F focus behaviour
- Add Esc support to clear and close search panel
- Always show the Clear button, even if no text
- Add tracking events to opening the search panel
- Add tooltip
> Search fixes

- src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridAdapter.cs
- Fixes the type issue, used to check for only `CompositeItemModel<EntityId>` instead of `CompositeItemModel<TKey>`.
- Returns early if there is no filter.
- Better exception when used for unsupported models.
> Fix exception when filtering for unsupported models

- src/NexusMods.Games.RedEngine/Cyberpunk2077/Cyberpunk2077Game.cs
> Disable Epic (for now)

- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
> Fix invalid thread exception

- src/NexusMods.Networking.NexusWebApi/Services.cs
- src/NexusMods.Networking.NexusWebApi/V1Interop/LocalMappingCache.cs
- tests/Networking/NexusMods.Networking.NexusWebApi.Tests/LocalMappingCacheTests.cs
> Add logging for local mapping cache

- src/NexusMods.Collections/CollectionCreator.cs
- src/NexusMods.Networking.NexusWebApi/NexusModsLibrary.Collections.cs
> Include vanity version in the collection manifest

- src/NexusMods.App.UI/LeftMenu/Items/ApplyControl/LaunchButtonViewModel.cs
- src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
- src/NexusMods.Telemetry/Events.cs
Event name now includes game name and store name. Adds two new events for game start and exit events.
> Update game events

- src/NexusMods.DataModel/Diagnostics/DiagnosticManager.cs
- src/NexusMods.Games.FileHashes/Emitters/UndeployableLoadoutDueToMissingGameFiles.cs
> Pass sync tree directly to the diagnostic emitter

- src/NexusMods.App.UI/Assets/Pictograms/download.svg
- src/NexusMods.App.UI/Pages/DebugControls/DebugControlsPageView.axaml
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml
- src/NexusMods.Themes.NexusFluentDark/Resources/ControlThemes/StandardButton.axaml
- src/NexusMods.Themes.NexusFluentDark/Resources/ControlThemes/Toolbar.axaml
- src/NexusMods.Themes.NexusFluentDark/Resources/Palette/Colors/ElementGradients.axaml
- src/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml
- src/NexusMods.Themes.NexusFluentDark/Styles/Controls/ProgressBar/ProgressBarStyles.axaml
- src/NexusMods.Themes.NexusFluentDark/Styles/UserControls/Toolbar/ToolbarStyles.axaml
- src/NexusMods.UI.Sdk/Icons/IconValues.cs
Fixed some bugs in StandardButton and Toolbar along the way
> Pause/Cancel UI Assets for Seweryn

- src/NexusMods.App.UI/Pages/ILibraryDataProvider.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryComponents.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/TreeDataGridLibraryResources.axaml
- src/NexusMods.App.UI/Pages/LocalFileDataProvider.cs
- src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
- src/NexusMods.App.UI/Resources/Language.Designer.cs
- src/NexusMods.App.UI/Resources/Language.resx
- tests/NexusMods.UI.Tests/Controls/TreeDataGrid/Filters/FilterTests.cs
- Part of #3743
Added a dedicated `LibraryItemIds` `CompositItemModel` component that could be used to get the Ids of the current item, decoupling that from the `InstallAction` component.
> Add delete option to Library mods kebab menu

- src/NexusMods.App.Cli/CliMessages.cs
- src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs
- src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
- src/NexusMods.App.UI/Dialog/Dialog.cs
- src/NexusMods.App.UI/LeftMenu/Items/ApplyControl/ApplyControlViewModel.cs
- src/NexusMods.App.UI/Notifications/WindowNotificationService.cs
- src/NexusMods.App.UI/Overlays/Welcome/WelcomeOverlayViewModel.cs
- src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
- src/NexusMods.App.UI/Pages/DebugControls/DebugControlsPageViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/Settings/SettingsPageViewModel.cs
- src/NexusMods.App.UI/Resources/Language.Designer.cs
- src/NexusMods.App.UI/Resources/Language.resx
- src/NexusMods.App.UI/Windows/MainWindowViewModel.cs
- src/NexusMods.Collections/CollectionDownloader.cs
- src/NexusMods.Networking.NexusWebApi/NexusModsLibrary.cs
- src/NexusMods.UI.Sdk/Extensions/DispatcherHelper.cs
- src/NexusMods.UI.Sdk/IWindowNotificationService.cs
- Closes #3747 
- Ensure that Toasts are spawned from UI thread
- Ensure that Dialogs are spawned from the UI thread
> Add Toast Notifications for many operations

- src/NexusMods.DataModel/NxFileStore.cs
The new shortcut for 0 size files to bypass access to the `FileStore` was also bypassing the creation of the parent directory, causing exceptions if the directory didn't already exist.
> Fix "Could not find part of path" errors when extracting 0 size files

- src/NexusMods.App.UI/Helpers/TreeDataGrid/New/FolderGenerator/TreeFolderGenerator.cs
- src/NexusMods.App.UI/Helpers/TreeDataGrid/New/FolderGenerator/TreeFolderGeneratorForLocationId.cs
- src/NexusMods.App.UI/Pages/LoadoutGroupFilesPage/LoadoutGroupFilesProvider.cs
- Fixes #3791 
Use dedicated display name property rather than injecting entries with fake paths
> Fix exception on deleting root item in External Changes

- src/NexusMods.App.UI/Controls/TreeDataGrid/SharedComponents.cs
- src/NexusMods.App.UI/Pages/BundledDataProvider.cs
- src/NexusMods.App.UI/Pages/ILibraryDataProvider.cs
- src/NexusMods.App.UI/Pages/ILoadoutDataProvider.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryComponents.cs
- src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
- src/NexusMods.App.UI/Pages/LibraryPage/TreeDataGridLibraryResources.axaml
- src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutComponents.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutTreeDataGridAdapter.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/TreeDataGridLoadoutResources.axaml
- src/NexusMods.App.UI/Pages/LocalFileDataProvider.cs
- src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
- src/NexusMods.App.UI/Resources/Language.Designer.cs
- src/NexusMods.App.UI/Resources/Language.pl.resx
- src/NexusMods.App.UI/Resources/Language.pt-BR.resx
- src/NexusMods.App.UI/Resources/Language.resx
- src/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridActionsColumnStyles.axaml
- part of #3743 
- Closes #3244
> Add "View Mod Page" menu option to items in Collection/Loadout pages 

- src/NexusMods.App.UI/Controls/TreeDataGrid/SharedComponents.cs
- src/NexusMods.App.UI/Pages/BundledDataProvider.cs
- src/NexusMods.App.UI/Pages/ILoadoutDataProvider.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutComponents.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutTreeDataGridAdapter.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
- src/NexusMods.App.UI/Pages/LoadoutPage/TreeDataGridLoadoutResources.axaml
- src/NexusMods.App.UI/Pages/LocalFileDataProvider.cs
- src/NexusMods.App.UI/Pages/ManuallyCreatedArchiveDataProvider.cs
- src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
- src/NexusMods.App.UI/Resources/Language.Designer.cs
- src/NexusMods.App.UI/Resources/Language.resx
- Part of #3743
Details:
- Added option to loadout page
- Added option to Collection loadout page
- Show confirmation dialog
- Fix list of collections in the confirmation dialog
> Add kebab uninstall option to Loadout/Collection loadout pages items

- src/NexusMods.DataModel/NxFileStore.cs
- tests/NexusMods.DataModel.Tests/FileStoreTests.cs
> Add archive validation

- src/NexusMods.DataModel/JsonConverters/RelativePathConverter.cs
> Fix `RelativePath` `JsonConverter` for null values

- src/NexusMods.Games.FileHashes/FileHashesService.cs
> Fix date comparison

- src/NexusMods.Abstractions.GameLocators/IGameLocator.cs
- src/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
- src/NexusMods.StandardGameLocators/AGameLocator.cs
- src/NexusMods.StandardGameLocators/AWineGameLocator.cs
- src/NexusMods.StandardGameLocators/HeroicGogLocator.cs
- src/NexusMods.StandardGameLocators/ManuallyAddedLocator.cs
- tests/NexusMods.StandardGameLocators.TestHelpers/UniversalStubbedGameLocator.cs
> Refresh `LocatorId` game store data during Synchronize to detect game version changes
