benchmarks/NexusMods.DataModel.Benchmarks/Program.cs
benchmarks/NexusMods.DataModel.Benchmarks/Sorting.cs
src/Games/NexusMods.Games.BethesdaGameStudios/PluginFile.cs
src/NexusMods.DataModel/Loadouts/LoadoutManager.cs
src/NexusMods.DataModel/Loadouts/Markers/LoadoutMarker.cs
src/NexusMods.DataModel/Loadouts/Mod.cs
src/NexusMods.DataModel/Sorting/Sorter.cs
tests/NexusMods.DataModel.Tests/SortTests.cs

```csharp
| Method | NumItems |         Mean |       Error |      StdDev |      Gen0 |      Gen1 |   Allocated |
|------- |--------- |-------------:|------------:|------------:|----------:|----------:|------------:|
|   Sort |      100 |     232.5 us |     0.76 us |     0.71 us |   13.6719 |    1.9531 |   218.35 KB |
|   Sort |     1000 |   9,651.1 us |    24.59 us |    20.54 us |   46.8750 |   15.6250 |   833.33 KB |
|   Sort |     2000 |  40,248.5 us |   319.33 us |   298.70 us |   76.9231 |         - |  1696.25 KB |
|   Sort |     5000 | 197,204.1 us | 3,727.65 us | 3,661.05 us | 1000.0000 |  500.0000 | 17553.82 KB |
|   Sort |    10000 | 825,593.6 us | 6,677.17 us | 6,245.83 us | 2000.0000 | 1000.0000 | 50161.87 KB |
```
Fixes …

Perf: Improve Sorting Algorithm Performance, Improve Sorting Benchmark

---

tests/NexusMods.CLI.Tests/NexusMods.CLI.Tests.csproj
tests/NexusMods.Paths.Tests/NexusMods.Paths.Tests.csproj

Fixes an accidental regression in aedce098b04e2140cf83d3c27538aeb2cc3f98b3  ( part of #94  ) ; that can happen while running tests from IDE and wasn't noticed in CI or review.
For our intent and purposes this is just part of the other PR.

Fixed: Startup for Projects that Depend(ed) on XUnit DependencyInjection

---

src/ArchiveManagement/NexusMods.FileExtractor/FileSignatures/Definitions/magic_sigs.txt
src/ArchiveManagement/NexusMods.FileExtractor/FileSignatures/Definitions/mundane_sigs.txt
src/ArchiveManagement/NexusMods.FileExtractor/FileSignatures/Signatures.cs
src/Games/NexusMods.Games.RedEngine/FileAnalyzers/RedModInfoAnalyzer.cs
src/Games/NexusMods.Games.RedEngine/ModInstallers/AppearancePreset.cs
src/Games/NexusMods.Games.RedEngine/ModInstallers/FolderlessModInstaller.cs
src/Games/NexusMods.Games.RedEngine/ModInstallers/Helpers.cs
src/Games/NexusMods.Games.RedEngine/ModInstallers/RedModInstaller.cs
src/Games/NexusMods.Games.RedEngine/ModInstallers/SimpleOverlayModInstaller.cs
src/Games/NexusMods.Games.RedEngine/Services.cs
src/Games/NexusMods.Games.RedEngine/TypeFinder.cs
src/Games/NexusMods.Games.TestHarness/Verbs/StressTest.cs
src/NexusMods.DataModel/Games/GameInstallation.cs
src/NexusMods.Paths/RelativePath.cs
src/NexusMods.Paths/Utilities/KnownExtensions.cs
tests/Games/NexusMods.Games.RedEngine.Tests/ModInstallerTests.cs

This PR adds support for Cyberpunk for the following mod types:
* .archive files scattered in various non-standard archive locations
* RedMod mods with `info.json` files
* Appearance presets

Fix Cyberpunk Stress Tests

---

src/Games/NexusMods.Games.RedEngine/FileAnalyzers/RedModInfoAnalyzer.cs
src/Games/NexusMods.Games.RedEngine/ModInstallers/FolderlessModInstaller.cs
src/Games/NexusMods.Games.RedEngine/ModInstallers/SimpleOverlayModInstaller.cs
src/Games/NexusMods.Games.TestHarness/Verbs/StressTest.cs
src/NexusMods.App/Program.cs
src/NexusMods.DataModel/FileAnalyzer.cs
src/NexusMods.DataModel/Loadouts/LoadoutManager.cs
src/NexusMods.Paths/AbsolutePath_IO.cs
src/NexusMods.Paths/RelativePath.cs
tests/Games/NexusMods.Games.RedEngine.Tests/ModInstallerTests.cs

Fixes for mods that put files under a top level folder, but under that have well defined patterns of `bin/x64/plugins` or something like that

Support non-rooted Cyberpunk mods

---

NexusMods.App.sln.DotSettings
src/Networking/NexusMods.Networking.NexusWebApi/ApiKeyMessageFactory.cs
src/Networking/NexusMods.Networking.NexusWebApi/Client.cs
src/Networking/NexusMods.Networking.NexusWebApi/DTOs/Category.cs
src/Networking/NexusMods.Networking.NexusWebApi/DTOs/DownloadLink.cs
src/Networking/NexusMods.Networking.NexusWebApi/DTOs/GameInfo.cs
src/Networking/NexusMods.Networking.NexusWebApi/DTOs/ModFile.cs
src/Networking/NexusMods.Networking.NexusWebApi/DTOs/ModFiles.cs
src/Networking/NexusMods.Networking.NexusWebApi/DTOs/ModUpdate.cs
src/Networking/NexusMods.Networking.NexusWebApi/DTOs/Response.cs
src/Networking/NexusMods.Networking.NexusWebApi/DTOs/ResponseMetadata.cs
src/Networking/NexusMods.Networking.NexusWebApi/DTOs/ValidateInfo.cs
src/Networking/NexusMods.Networking.NexusWebApi/IHttpMessageFactory.cs
src/Networking/NexusMods.Networking.NexusWebApi/Services.cs
src/Networking/NexusMods.Networking.NexusWebApi/Types/CDNName.cs
src/Networking/NexusMods.Networking.NexusWebApi/Types/FileId.cs
src/Networking/NexusMods.Networking.NexusWebApi/Types/GameId.cs
src/Networking/NexusMods.Networking.NexusWebApi/Types/ModId.cs
src/Networking/NexusMods.Networking.NexusWebApi/Types/UserId.cs
src/Networking/NexusMods.Networking.NexusWebApi/Verbs/DownloadLinks.cs
src/Networking/NexusMods.Networking.NexusWebApi/Verbs/NexusApiVerify.cs
src/Networking/NexusMods.Networking.NexusWebApi/Verbs/NexusGames.cs
src/Networking/NexusMods.Networking.NexusWebApi/Verbs/SetNexusAPIKey.cs

This PR performs the following actions:  
- Fully adds XML Documentation to existing API.  
- Adds TODO(s) for items of interest related to cleaning up the API.  
- Adds an additional Vogen `ValueObject` where appropriate.  
- Fixes a minor bug where a field was incorrectly defined.
Something we still need to do is make unit tests for this library; that said, I'm not yet sure if this is in our best interest because ideally we should be moving to the GraphQL based V2 API that's in development. 
Until V2 is fully complete; it might just be better to mix the two; using V1 where V2 doesn't yet have what we need.

Added: XML Documentation for Nexus Web Api & Moved Header Parsing to 

---

benchmarks/NexusMods.Benchmarks/Benchmarks/DataModel.cs
src/NexusMods.CLI/Verbs/ChangeTracking.cs
src/NexusMods.DataModel/Abstractions/IDataStore.cs
src/NexusMods.DataModel/Interprocess/IMessage.cs
src/NexusMods.DataModel/Interprocess/IMessageConsumer.cs
src/NexusMods.DataModel/Interprocess/IMessageProducer.cs
src/NexusMods.DataModel/Interprocess/InterprocessConsumer.cs
src/NexusMods.DataModel/Interprocess/InterprocessProducer.cs
src/NexusMods.DataModel/NexusMods.DataModel.csproj
src/NexusMods.DataModel/Services.cs
src/NexusMods.DataModel/SqliteDataStore.cs
tests/NexusMods.DataModel.Tests/DataStoreTests.cs
tests/NexusMods.DataModel.Tests/InterprocessTests.cs
tests/NexusMods.DataModel.Tests/ModelTests.cs

Implements a simple but effective IPC system into the app. 
* Can create a Producer/Consumer by requesting a `IMessageProducer<T>` or `IMessageConsumer<T>` from the DI system. `T` must be an instance of `IMessage`.
* Tests include basic sanity checks for sending integers. 
* The Default Datastore now properly tracks and publishes changes to roots. Calls to `PutRoot` publish on the `IMessageConsumer<RootChange>`, this can be leveraged later on to update the UI when a CLI operation finishes modifying a loadout.
* `nexusmods.app.exe change-tracking` can be used to visualize changes to the roots. It subscribes to `RootChange` notices and prints them to the console.

Adds an IPC subsystem to the DataModel

---

src/NexusMods.DataModel/Abstractions/IDataStore.cs
src/NexusMods.DataModel/NexusMods.DataModel.csproj

We use a zero-allocation BitStream library for quick encoding of IPC messages.  
The library was originally optimised for writing/reading packed messages at the bit level; however we currently only use it as a byte stream. As such; to avoid any potential future bottlenecks where we might want to send a large amount of data; the  `BitStream` library could do with some optimistaions.
This PR adds a variety of improvements to the `BitStream` library to support our needs and use cases.  
- Byte Level Reads i.e. `ReadAligned`.  
- Extensions for Streams for Optimised Multi-byte Read/Write Implementations i.e. `IStreamWithReadBasicPrimitives` & `ReadAlignedFast` APIs.  
- Extensions for Streams in `Read(Span<byte>)` and `Write(Span<byte>)` to use direct `memcpy` where possible. i.e. …

Improved: Read & Write Performance of IPC by ~3x

---

src/Games/NexusMods.Games.BethesdaGameStudios/SkyrimSpecialEdition.cs
src/NexusMods.DataModel/Games/AGame.cs

Without the `virtual` keyword, the overridden `GetGameFiles` method won't be used when the game is used as `AGame` type

Fixed: Missing virtual keyword

---

.gitattributes
NexusMods.App.sln

The [`.gitattributes`](https://www.git-scm.com/docs/gitattributes) file can be used to tell git how to handle certain files. It can also be used to influence the [GitHub language detection](https://github.com/open-papyrus/docs/blob/master/.gitattributes).
The important changes here are the LF normalization and EOL specification for certain text files to prevent any cross-platform issues.

Add `.gitattributes` file

---

.github/workflows/validate-codecov.yaml
codecov.yaml

- adds a [validation](https://api.codecov.io/validate) workflow for `codecov.yaml`
- updates `codecov.yaml` to only post a comment after 2 builds. This prevents codecov from posting a comment when only 1 build finishes, as the comment often contains incomplete information. This value should be updated when more builds are added.

Small codecov fixes

---

.editorconfig
NexusMods.App.sln

- forces UTF-8 (not utf-8-bom, which VS likes to use)
- forces final new line and trims trailing whitespace for better git compatibility and less diff clutter
- changes warning severities:
- [CS1591](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591): "Missing XML comment for publicly visible type or member" from _warning_ to _suggestion_. This reduces clutter in the build log while keeping the suggestions visible in the IDE.
- [CS4014](https://learn.microsoft.com/en-US/dotnet/csharp/language-reference/compiler-messages/cs4014): "Task not awaited" from _warning_ to **error**. This is just a precaution as nothing in the codebase currently triggers this warning. I changed this to be an error, as an issue related to a not awaited task is very hard to …

Add `.editorconfig` file

---

src/Networking/NexusMods.Networking.NexusWebApi/OAuth.cs
tests/Networking/NexusMods.Networking.NexusWebApi.Tests/OAuthTests.cs

I didn't see it in the initial code review, but I was a little unhappy with the callback interactions in the original OAuth2 code. We were using a Dictionary to store callbacks (which technically isn't threadsafe), and using TaskCompletetionSource in cases where we already have `IObservable` interfaces. Turns out it cleaned up quite nicely.

Cleanup OAuth2 callback code

---

src/NexusMods.StandardGameLocators/Services.cs

Previously, NMA would look for hardcoded Steam paths instead of letting GameFinder look for Steam. Using environment variables, we can rely on GameFinder for sane installation paths and let the user set the path manually.

Fix Steam locator on Linux

---

benchmarks/NexusMods.Benchmarks/Benchmarks/DataModel.cs
src/Networking/NexusMods.Networking.NexusWebApi/Services.cs
src/NexusMods.App/Program.cs
src/NexusMods.CLI/Services.cs
src/NexusMods.Common/Services.cs
tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/Startup.cs
tests/Games/NexusMods.Games.RedEngine.Tests/Startup.cs
tests/Networking/NexusMods.Networking.HttpDownloader.Tests/Startup.cs
tests/Networking/NexusMods.Networking.NexusWebApi.Tests/Startup.cs
tests/NexusMods.CLI.Tests/Startup.cs
tests/NexusMods.DataModel.Tests/Startup.cs
tests/NexusMods.StandardGameLocators.Tests/Startup.cs
tests/NexusMods.UI.Tests/Startup.cs

Adds a `IServiceCollection.Validate` method for making sanity checks on service collections. Fixed several duplicate registrations, cleaned up the service registration code a bit.

Cleanup service registration code and validate IServiceCollections

---

.editorconfig
NexusMods.App.sln
NullableErrors.Build.props
src/ArchiveManagement/NexusMods.FileExtractor/NexusMods.FileExtractor.csproj
src/Games/NexusMods.Games.BethesdaGameStudios/NexusMods.Games.BethesdaGameStudios.csproj
src/Games/NexusMods.Games.DarkestDungeon/NexusMods.Games.DarkestDungeon.csproj
src/Games/NexusMods.Games.Generic/NexusMods.Games.Generic.csproj
src/Games/NexusMods.Games.RedEngine/NexusMods.Games.RedEngine.csproj
src/Games/NexusMods.Games.Reshade/NexusMods.Games.Reshade.csproj
src/Games/NexusMods.Games.Reshade/ReshadePresetInstaller.cs
src/Networking/NexusMods.Networking.HttpDownloader/NexusMods.Networking.HttpDownloader.csproj
src/Networking/NexusMods.Networking.NexusWebApi/DTOs/DownloadLink.cs
src/Networking/NexusMods.Networking.NexusWebApi/NexusMods.Networking.NexusWebApi.csproj
src/Networking/NexusMods.Networking.NexusWebApi/Types/UserInfo.cs
src/NexusMods.App/NexusMods.App.csproj
src/NexusMods.App/Program.cs
src/NexusMods.CLI/NexusMods.CLI.csproj
src/NexusMods.Common/NexusMods.Common.csproj
src/NexusMods.DataModel.RateLimiting/NexusMods.DataModel.RateLimiting.csproj
src/NexusMods.DataModel/Abstractions/EntityDictionary.cs
src/NexusMods.DataModel/Games/RunGameTool.cs
src/NexusMods.DataModel/JsonConverters/AExpressionConverterGenerator.cs
src/NexusMods.DataModel/JsonConverters/ConcreteConverterGenerator.cs
src/NexusMods.DataModel/Loadouts/Loadout.cs
src/NexusMods.DataModel/Loadouts/Markers/LoadoutMarker.cs
src/NexusMods.DataModel/NexusMods.DataModel.csproj
src/NexusMods.DataModel/Sorting/Sorter.cs
src/NexusMods.Hashing.xxHash64/NexusMods.Hashing.xxHash64.csproj
src/NexusMods.Paths/NexusMods.Paths.csproj

This adds `NullableErrors.Build.props` which changes the nullable warnings to error:
```xml
<WarningsAsErrors>Nullable</WarningsAsErrors>
```
I imported this file in almost all projects, the only projects that are not using this are:
- all test projects
- `NexusMods.App.UI`
Working with nullability in UI projects is very tedious and would require a lot of changes, which I consider outside the scope of this PR.

Nullable warnings as errors

---

src/NexusMods.Paths/AbsolutePath.cs
tests/NexusMods.Paths.Tests/New/AbsolutePathTests/ConstructorTests.cs
tests/NexusMods.Paths.Tests/New/AbsolutePathTests/FromFullPathTests.cs

- `/` is now a valid directory
- fixes `FromFullPath` to use `/` as a directory instead of `""`
- fixes the constructor not to remove `/` from the directory, if the directory is `/`
- fixes `GetFullPath` to not return `//foo` instead of `/foo`

Fix Linux path issues

---

benchmarks/NexusMods.Benchmarks/Benchmarks/DataModel.cs
src/Games/NexusMods.Games.BethesdaGameStudios/Installers/LooseFileInstaller.cs
src/Games/NexusMods.Games.BethesdaGameStudios/SkyrimSpecialEdition.cs
src/Games/NexusMods.Games.DarkestDungeon/DarkestDungeonModInstaller.cs
src/Games/NexusMods.Games.RedEngine/ModInstallers/AppearancePreset.cs
src/Games/NexusMods.Games.RedEngine/ModInstallers/FolderlessModInstaller.cs
src/Games/NexusMods.Games.RedEngine/ModInstallers/RedModInstaller.cs
src/Games/NexusMods.Games.RedEngine/ModInstallers/SimpleOverlayModInstaller.cs
src/Games/NexusMods.Games.Reshade/ReshadePresetInstaller.cs
src/Games/NexusMods.Games.TestHarness/NexusModFile.cs
src/Games/NexusMods.Games.TestHarness/RecentModsTests.cs
src/Networking/NexusMods.Networking.NexusWebApi/LoginManager.cs
src/Networking/NexusMods.Networking.NexusWebApi/OAuth2MessageFactory.cs
src/NexusMods.DataModel/Abstractions/Entity.cs
src/NexusMods.DataModel/Abstractions/EntityDictionary.cs
src/NexusMods.DataModel/Abstractions/EntityExtensions.cs
src/NexusMods.DataModel/Abstractions/EntityLink.cs
src/NexusMods.DataModel/Abstractions/Root.cs
src/NexusMods.DataModel/ArchiveContents/AnalyzedFile.cs
src/NexusMods.DataModel/ArchiveContents/FileContainedIn.cs
src/NexusMods.DataModel/Exceptions/UnpersistedEntity.cs
src/NexusMods.DataModel/FileAnalyzer.cs
src/NexusMods.DataModel/Loadouts/Loadout.cs
src/NexusMods.DataModel/Loadouts/LoadoutManager.cs
src/NexusMods.DataModel/Loadouts/LoadoutRegistry.cs
src/NexusMods.DataModel/Loadouts/Markers/LoadoutMarker.cs
tests/Networking/NexusMods.Networking.NexusWebApi.Tests/OAuth2MessageFactoryTests.cs
tests/NexusMods.DataModel.Tests/DataStoreTests.cs
tests/NexusMods.DataModel.Tests/ModelTests.cs
tests/NexusMods.StandardGameLocators.TestHelpers/StubbedGames.cs

This refactors the Entities so they no longer implicitly persist themselves to the IDataStore. As a side-effect we then have no reason for them to contain a `IDataStore` so I yanked that as well. Collections will still auto-persist any object inserted into them, but that feels natural as we're calling things like `.Add`. If we don't like these semantics we might be able to yank that as well, but for now, having collections write-on-add is nice for code simplicity.

Explicit Persistence and removing the Datastore on entities

---

src/NexusMods.DataModel/Interprocess/InterprocessConsumer.cs
src/NexusMods.DataModel/Interprocess/InterprocessProducer.cs
src/NexusMods.DataModel/Interprocess/SqliteIPC.cs
src/NexusMods.DataModel/NexusMods.DataModel.csproj
src/NexusMods.DataModel/Services.cs
tests/NexusMods.DataModel.Tests/InterprocessTests.cs
tests/NexusMods.DataModel.Tests/Startup.cs
tests/NexusMods.Paths.Tests/NexusMods.Paths.Tests.csproj

This reworks the IPC code for the App. 
* Used a 3rd party socket/shared memory system
* Project hasn't been updated in a few months
* Has some rather concerning GitHub issues about leaking resources
* Is a bit overkill for our project, we're likely to only ever insert a message every few seconds, not thousands per second
* Uses Sqlite as the log store
* Data is stored in a separate file from the main DataStore so we don't fragment the old data store
* Messages are deleted after 10 seconds
* Every ~10 minutes a running process will run a "delete old messages" command
* The size/last modified file stats for the .sqlite file are used to trigger a new polling
* Every 10 seconds the file is polled by doing a `SELECT WHERE` just in case some race condition blocked up the cheaper approach.

Rework the IPC system

---

.editorconfig
src/NexusMods.Paths/AbsolutePath.cs
src/NexusMods.Paths/FileSystemAbstraction/BaseFileSystem.cs
src/NexusMods.Paths/FileSystemAbstraction/IFileSystem.cs
src/NexusMods.Paths/FileSystemAbstraction/InMemoryFileSystem/InMemoryFileSystem.cs
src/NexusMods.Paths/FileSystemAbstraction/KnownPath.cs
src/NexusMods.Paths/FileSystemAbstraction/RealFileSystem/FileSystem.cs
tests/NexusMods.Paths.Tests/FileSystem/BaseFileSystemTests.cs

`BaseFileSystem` will can now convert a Windows path to a Linux path when configured to do so. This is only useful for Wine mappings and is disabled by default.

More FileSystem changes for Wine

---

src/NexusMods.Paths/AbsolutePath.cs
src/NexusMods.Paths/FileSystemAbstraction/BaseFileSystem.cs
src/NexusMods.Paths/FileSystemAbstraction/IFileSystem.cs
src/NexusMods.Paths/FileSystemAbstraction/KnownPath.cs

I originally had `CreateWinePathMappings` in GameFinder, however it would be hard to update, so I decided to put it inside `BaseFileSystem` instead.

More KnownPaths and Wine mappings

---

src/ArchiveManagement/NexusMods.FileExtractor/TemporaryFileManagerEx.cs
src/NexusMods.Paths/AbsolutePath.cs

This forces API consumers to use the methods provided by `IFileSystem` to create new paths.

Make AbsolutePath factory functions internal

---

NexusMods.App.sln
tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/NexusMods.Games.BethesdaGameStudios.Tests.csproj
tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/Startup.cs
tests/Games/NexusMods.Games.DarkestDungeon.Tests/DarkestDungeonModInstallerTests.cs
tests/Games/NexusMods.Games.DarkestDungeon.Tests/NexusMods.Games.DarkestDungeon.Tests.csproj
tests/Games/NexusMods.Games.DarkestDungeon.Tests/Startup.cs
tests/Games/NexusMods.Games.DarkestDungeon.Tests/Usings.cs
tests/Games/NexusMods.Games.FOMOD.Tests/NexusMods.Games.FOMOD.Tests.csproj
tests/Games/NexusMods.Games.FOMOD.Tests/Startup.cs
tests/Games/NexusMods.Games.RedEngine.Tests/NexusMods.Games.RedEngine.Tests.csproj
tests/Games/NexusMods.Games.RedEngine.Tests/RedModInfoAnalyzerTests.cs
tests/Games/NexusMods.Games.RedEngine.Tests/Startup.cs
tests/Games/NexusMods.Games.TestFramework/AFileAnalyzerTest.cs
tests/Games/NexusMods.Games.TestFramework/AGameTest.cs
tests/Games/NexusMods.Games.TestFramework/AModInstallerTest.cs
tests/Games/NexusMods.Games.TestFramework/DependencyInjectionHelper.cs
tests/Games/NexusMods.Games.TestFramework/NexusMods.Games.TestFramework.csproj

Resolves #247
Adds `NexusMods.Games.TestFramework` which simplifies the following aspects:
- `AddDefaultServicesForTesting` is an extension method on `IServiceCollection` which reduces the amount of code duplication in the `Startup.ConfigureServies` methods of the test projects
- `AGameTest<TGame>` is a new abstract class that provides helper methods for creating test archives and files, creating loadouts, as well as downloading and installing mods into loadouts
- `AModInstallerTest<TGame, TModInstaller>` is a new abstract class for testing `IModInstaller` implementations.
- `AFileAnalyzerTest<TGame, TFileAnalyzer>` is a new abstract class for testing `IFileAnalyzer` implementations.
Both `AModInstallerTest` and `AFileAnalyzerTest` inherit from `AGameTest` and provide helper methods that …

Add helpers for game testing

---

tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/NexusMods.Games.BethesdaGameStudios.Tests.csproj
tests/Games/NexusMods.Games.DarkestDungeon.Tests/NexusMods.Games.DarkestDungeon.Tests.csproj
tests/Games/NexusMods.Games.FOMOD.Tests/NexusMods.Games.FOMOD.Tests.csproj
tests/Games/NexusMods.Games.RedEngine.Tests/NexusMods.Games.RedEngine.Tests.csproj

(Description copied from #260)
PR https://github.com/Nexus-Mods/NexusMods.App/pull/253 introduced a warning to our build logs, because some of the test projects were modified to include the following line.
```
<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
```
This is redundant [because](https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-by-directory?view=vs-2022):
> When MSBuild runs, Microsoft.Common.props searches your directory structure for the Directory.Build.props file. If it finds one, it imports the file and reads the properties defined within it. Directory.Build.props is a user-defined file that provides customizations to projects under a directory.
And as a result our CI builds have been reporting …

Fixed: Double Import of Directory.Build.props (fixes #260)

---

src/ArchiveManagement/NexusMods.FileExtractor/FileSignatures/Definitions/magic_sigs.txt
src/ArchiveManagement/NexusMods.FileExtractor/FileSignatures/Signatures.cs
src/Games/NexusMods.Games.BethesdaGameStudios/PluginAnalyzer.cs
src/Games/NexusMods.Games.FOMOD/FomodAnalyzer.cs
src/Games/NexusMods.Games.Generic/FileAnalyzers/IniAnalzyer.cs
src/Games/NexusMods.Games.RedEngine/FileAnalyzers/RedModInfoAnalyzer.cs
src/NexusMods.DataModel/Abstractions/IFileAnalyzer.cs
src/NexusMods.DataModel/Abstractions/Ids/FileAnalyzerId.cs
src/NexusMods.DataModel/ArchiveContents/AnalyzedFile.cs
src/NexusMods.DataModel/FileAnalyzer.cs
tests/NexusMods.DataModel.Tests/ArchiveContentsCacheTests.cs
tests/NexusMods.DataModel.Tests/Harness/ADataModelTest.cs
tests/NexusMods.DataModel.Tests/NexusMods.DataModel.Tests.csproj
tests/NexusMods.DataModel.Tests/Resources/data.test
tests/NexusMods.DataModel.Tests/Startup.cs

Adds a Id and Revision pair to every `IFileAnalyzer`, changing the Revision number of an Analyzer will trigger a re-analysis of a file once it opens the next time. 
Unfortunately, because files can contain other files, we have to invalidate everything in the cache whenever a single IFileAnalyzer is updated. This shouldn't be too bad though as right now analysis data is only ever used during mod installation. More complex code could likely improve the user experience here, but at least for now we don't get bad analysis data whenever the code updates.

Archive Content Cache Invalidation

---

src/NexusMods.App/CLI/Renderers/Spectre.cs

The overload `ot.AddRow()` that accepts strings converts those strings into [`Markup`](https://spectreconsole.net/markup), which can cause issues depending on the text. Using [`Text`](https://spectreconsole.net/api/spectre.console/text/) directly is safer.

Fix table rendering with Sepctre

---

src/NexusMods.App/Program.cs

- fixes NLog overwriting log filters
- sets minimum level depending on compile constants:
- `DEBUG` will enable debug logging
- `TRACE` will enable trace logging (only for debug builds)
- else: informational logging

Fix trace logging

---

benchmarks/NexusMods.Benchmarks/Benchmarks/HighPerformanceLogging.cs
benchmarks/NexusMods.Benchmarks/Benchmarks/IdToString.cs
src/NexusMods.App.UI/HighPerformanceLogging.cs
src/NexusMods.App.UI/InjectedViewLocator.cs
src/NexusMods.DataModel/Abstractions/EntityCategory.cs
src/NexusMods.DataModel/Abstractions/Ids/AId.cs
src/NexusMods.DataModel/HighPerformanceLogging.cs
src/NexusMods.DataModel/Interprocess/SqliteIPC.cs
src/NexusMods.DataModel/NexusMods.DataModel.csproj
src/NexusMods.DataModel/SqliteDataStore.cs

We're using `Microsoft.Extensions.Abstractions.Logging` for all of our logging. We're also producing a lot of _trace_ logs in hot paths of our app. I fixed the issue of always logging traces in #280, which indirectly helped with performance (because the code no longer writes to console), however there is still performance to be gained.
The `ILogger` extension methods `LogTrace`, `LogDebug` and so on, all use `param object[]`, which **always** allocates a new array, even if we disabled trace logging. Furthermore, value types, which we use everywhere, get boxed to `object`.
Microsoft provides [guidelines](https://learn.microsoft.com/en-us/dotnet/core/extensions/high-performance-logging) for high performance logging using the [`LoggerMessage`](https://learn.microsoft.com/en-us/dotnet/api/micr …

High performance logging

---

.github/workflows/clean_environment_tests.yaml
.github/workflows/networking_tests.yaml

VSTest integration is [preferred](https://github.com/coverlet-coverage/coverlet#vstest-integration-preferred-due-to-known-issue) over MSBuild. This might help stabilize the CI tests a bit.

Use VSTest integration instead of MSBuild

---

.github/workflows/clean_environment_tests.yaml
.github/workflows/publish-nuget-packages.yaml
Directory.Build.props
NuGet.Build.props
scripts/validate-nupkgs.ps1
src/Networking/NexusMods.Networking.NexusWebApi/NexusMods.Networking.NexusWebApi.csproj
src/NexusMods.App.UI/RightContent/LoadoutGrid/Columns/IDataGridColumnFactory.cs
src/NexusMods.App.UI/RightContent/LoadoutGrid/Columns/ModInstalledViewModel.cs
src/NexusMods.App/NexusMods.App.csproj
src/NexusMods.CLI/NexusMods.CLI.csproj

Resolves #104 
- adds a GitHub workflow for pushing packages to NuGet when a new tag is pushed to the repository
- uses a whitelist to manage which projects are being packaged
- fixes some dependencies
- adds a validation script that makes sure we're exporting every required local project
- adds a build step to the CI, this cleans up the logs and allows for better debugging

Push to NuGet

---

src/NexusMods.App.UI/Windows/MainWindow.axaml
tests/NexusMods.UI.Tests/AEndToEndTest.cs
tests/NexusMods.UI.Tests/EndToEndSanityTest.cs
tests/NexusMods.UI.Tests/Framework/AvaloniaApp.cs
tests/NexusMods.UI.Tests/Framework/WindowHost.cs
tests/NexusMods.UI.Tests/Startup.cs

For #221, implements a full-app testing system for end to end testing. The created window uses a real MainWindow, real MainWindowViewModel and all the associated services. Routes the datamodel folders to a temporary location so tests start clean every time, and also implements a way to save screenshots of the headless renderer the window runs in. 
In the future we may want to upload these screenshots as part of the tests so we can verify that the code looks as expected. But this is beyond the scope of this ticket.

End-to-End testing framework

---

.github/workflows/clean_environment_tests.yaml
tests/Directory.Build.props

This is a custom test logger that outputs to GitHub and creates summaries and annotations: https://github.com/Nexus-Mods/NexusMods.App/actions/runs/4989909959?pr=322

Use GitHubActionsTestLogger

---

tests/Directory.Build.props

Floating versions are very useful for test dependencies, which frequent releases with almost no breaking changes.

Upgrade dependencies and use floating versions

---

src/Games/NexusMods.Games.FOMOD/FomodAnalyzer.cs

fix #413 
The FomodAnalyzer was closing a stream that was still in use causing an exception later.

Fix crash when adding mods from cli

---

src/NexusMods.CLI/Verbs/Apply.cs

The missing case would generate an exception when running the `apply -run` command.
The switch is used to populate a summary of the apply steps, just visual data.

Add missing GenerateFile case in apply table summary

---

src/Games/NexusMods.Games.BethesdaGameStudios/PluginFile.cs
tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/SkyrimSpecialEditionTests/SkyrimSpecialEditionTests.cs

Plugins.txt was missing '*' in front of plugins to enable. 
This is required for Skyrim SE and FO4 for example, while SLE and older games only had enabled files in plugins.txt and loadorder.txt was created by modders to keep track of position of disabled plugins.
fix #412

SSE: Add `*` in front of entries of plugins.txt to make them enabled

---

src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs
src/NexusMods.Paths/AbsolutePath.cs
src/NexusMods.Paths/RelativePath.cs
src/NexusMods.Paths/Utilities/PathHelpers.cs
tests/NexusMods.FileExtractor.Tests/SevenZipExtractionTests.cs
tests/NexusMods.Paths.Tests/AbsolutePathTests.cs
tests/NexusMods.Paths.Tests/PathHelperTests.cs
tests/NexusMods.Paths.Tests/RelativePathTests.cs

fixes #429 
This implements a workaround for a 7z.exe problem on windows in cases where the path is very long and uses forward slashes.
We normally always use forward slashes internally as windows file systems should support it, but apparently in this particular case 7z requires backwards slashes on windows.
To obtain the proper slashes, the ToNativeSeparators functions were added to the paths library.

Fix crash on 7z file extraction to long paths on windows

---

src/ArchiveManagement/NexusMods.FileExtractor/NexusMods.FileExtractor.csproj
src/NexusMods.Common/NexusMods.Common.csproj
src/NexusMods.DataModel/NexusMods.DataModel.csproj
src/NexusMods.DataModel/NxArchiveManager.cs
src/NexusMods.DataModel/Services.cs
src/NexusMods.DataModel/ZipArchiveManager.cs

- Multiple bug fixes in .nx Archive library (updated to `0.3.3-preview`).  
- Removed unnecessary `.nx` dependencies in projects that don't depend on it.  
- Reduced `stackalloc` from 64-bytes to just needed amount in `UpdateIndexes`.  
- Changed to using `V1` instead of `V0` file entry format.
- This will allow for 4GB+ files to be used in stored mods.
- Delete your DataStore after merging, due to incompatibility of changed format.
- We could potentially save some space, here,

Added: A bunch of .nx related fixes. (fixes #410)

---

src/NexusMods.DataModel/Interprocess/Jobs/InterprocessJob.cs
src/NexusMods.DataModel/Interprocess/SqliteIPC.cs

Part 1 of #372.
Inside the `SqliteIPC.ReaderLoop` method, we're calling [`ProcessJobs`](https://github.com/Nexus-Mods/NexusMods.App/blob/e1455ec7aaef2faf3c8225cdbd3c158052496524/src/NexusMods.DataModel/Interprocess/SqliteIPC.cs#L239) which gets every job from the IPC DB and then updates or inserts the jobs into the `_jobs` `SourceCache`. The issue is this section:
https://github.com/Nexus-Mods/NexusMods.App/blob/e1455ec7aaef2faf3c8225cdbd3c158052496524/src/NexusMods.DataModel/Interprocess/SqliteIPC.cs#L263-L271
While reading from the database, we're updating the progress of the job, which will try to update the progress in the database:
https://github.com/Nexus-Mods/NexusMods.App/blob/e1455ec7aaef2faf3c8225cdbd3c158052496524/src/NexusMods.DataModel/Interprocess/Jobs/InterprocessJob.cs#L72- …

Prevent database locking in reader loop

---

src/Games/NexusMods.Games.StardewValley/Analyzers/SMAPIManifestAnalyzer.cs
src/NexusMods.DataModel/Abstractions/IFileAnalyzer.cs
tests/Games/NexusMods.Games.StardewValley.Tests/Analyzers/SMAPIManifestAnalyzerTests.cs

Fixes #435.
Changes:
- adds exception logging when JSON Serialization fails
- allows trailing commas in `manifest.json` files

Allow trailing comma in SMAPI Manifest

---

src/Games/NexusMods.Games.StardewValley/Analyzers/SMAPIManifestAnalyzer.cs
src/Games/NexusMods.Games.StardewValley/Emitters/001_MissingDependencies.cs
src/Games/NexusMods.Games.StardewValley/Installers/SMAPIModInstaller.cs
src/Games/NexusMods.Games.StardewValley/Models/SMAPIManifest.cs
src/Games/NexusMods.Games.StardewValley/Models/SMAPIManifestDependency.cs
src/Games/NexusMods.Games.StardewValley/Models/SMAPIVersion.cs
src/Games/NexusMods.Games.StardewValley/NexusMods.Games.StardewValley.csproj
src/Games/NexusMods.Games.StardewValley/TypeFinder.cs
tests/Games/NexusMods.Games.StardewValley.Tests/Analyzers/SMAPIManifestAnalyzerTests.cs
tests/Games/NexusMods.Games.StardewValley.Tests/Emitters/001_MissingDependencyTests.cs
tests/Games/NexusMods.Games.StardewValley.Tests/Models/SMAPIVersionTests.cs
tests/Games/NexusMods.Games.StardewValley.Tests/TestHelper.cs

Changes:
- fixes comments breaking JSON serialization for SMAPI manifests
- adds `SMAPIVersion` that correctly parses version numbers in SMAPI manifests

Fix broken version parsing for SMAPI Manifests

---

src/NexusMods.DataModel/ArchiveAnalyzer.cs

This is to avoid retries at analyzing the Archive failing after finding existing AnalyzedFile data in datastore instead of expected AnalyzedArchive.
Fixes #450

Only persist Analized data for archives if the analysis was successfull

---

Directory.Packages.props

This release only contains bug fixes: https://github.com/AvaloniaUI/Avalonia/releases/tag/11.0.1

Upgrade Avalonia to 11.0.1

---

.github/workflows/clean_environment_tests.yaml
src/Networking/NexusMods.Networking.HttpDownloader/AdvancedHttpDownloader.cs
src/NexusMods.CLI/Services.cs
tests/Games/NexusMods.Games.TestFramework/DependencyInjectionHelper.cs
tests/Games/NexusMods.Games.TestFramework/TestModDownloader.cs
tests/Networking/NexusMods.Networking.HttpDownloader.Tests/AdvancedHttpDownloaderTests.cs
tests/Networking/NexusMods.Networking.HttpDownloader.Tests/LocalHttpServer.cs
tests/Networking/NexusMods.Networking.HttpDownloader.Tests/Startup.cs
tests/NexusMods.DataModel.Tests/Startup.cs

The content sending logic has been refactored into a separate method called "SendContent" for better maintainability. This simplifies the HTTP response handling section in the "LocalHttpServer.cs" file, as the responsibility to position the stream, create a buffer, and write to the response output stream has been moved to this new helper method. The range of data to be sent is now calculated within this method itself.  Also, included Debug.Assert statement in "AdvancedHttpDownloader.cs" for debugging purpose.

Refactored content sending method and updated tests

---

src/NexusMods.App.UI/RightContent/LoadoutGrid/Columns/ModEnabled/ModEnabledViewModel.cs
src/NexusMods.DataModel/Loadouts/LoadoutSyncronizer.cs
tests/NexusMods.DataModel.Tests/Harness/ALoadoutSynrconizerTest.cs
tests/NexusMods.DataModel.Tests/LoadoutSynchronizerTests/IngestChangesTest.cs
tests/NexusMods.DataModel.Tests/LoadoutSynchronizerTests/MakeApplyPlanTests.cs
tests/NexusMods.DataModel.Tests/LoadoutSynchronizerTests/MakeIngestPlanTests.cs

Fixes #427 
There were two separate issues: 
- The UI wasn't actually updating the sate of the mod as intended.
- The LoadoutSynchronizer wasn't excluding disabled mods during Apply step computations.

Fix mod Enabling / Disabling functionality

---

.github/workflows/build-linux-pupnet.yaml
.github/workflows/build-windows-pupnet.yaml
.github/workflows/release.yaml
src/NexusMods.App/app.desktop
src/NexusMods.App/app.metainfo.xml
src/NexusMods.App/app.pupnet.conf
src/NexusMods.Common/CompileConstants.cs

Resolves #376 
Resolves #454 
Resolves #444
**Features**:
- Release on GitHub:
- "normal" release
- prerelease
- draft release (essentially a private release)
- Notify on Discord (requires `DISCORD_WEBHOOK_ID` and `DISCORD_WEBHOOK_TOKEN` secrets)
- Windows:
- Archive
- Inno Setup
- Linux:
- Archive
- AppImage
**Missing**:
- Signing (#455) waiting on https://github.com/kuiperzone/PupNet-Deploy/issues/25
- Assets (icons, logos)
- Slack notifications
- Release on Nexus Mods

Add release pipeline

---

src/NexusMods.DataModel/Loadouts/LoadoutSyncronizer.cs

Fixes #411 - in a somewhat temporary way. Fixes how we get metadata for generated files. This fixes how generated files work during applying but not during ingesting. Ingesting generated files is part of a future task

Fix how we handle generated file metadata during applying. 

---

.github/workflows/build-windows-pupnet.yaml
.github/workflows/release.yaml
scripts/sign.ps1
src/NexusMods.App/NexusMods.App.csproj
src/NexusMods.App/app.pupnet.conf
src/NexusMods.App/sign.bat

Resolves #455
Signing requires the secrets `PFX_BASE64` and `PFX_KEY`. Signing can be disabled completely by setting `SignExecutable` to `false`.

Add code signing

---

src/NexusMods.DataModel/Interprocess/SqliteIPC.cs
tests/NexusMods.DataModel.Tests/InterprocessTests.cs

Related to #372.
Job updates via the IPC were never published. We only added new jobs or removed completed ones. This PR allows job updates to be observed. I've added some tests for a single-thread and multi-thread scenario. These tests have a high enough timeout for the IPC reader loop to pick up the changes and notify the subscribers.

Publish Job updates via the IPC

---

src/NexusMods.CLI/Types/IpcHandlers/NxmIpcProtocolHandler.cs
src/NexusMods.DataModel/Interprocess/IMessageProducer.cs
src/NexusMods.DataModel/Interprocess/InterprocessProducer.cs
src/NexusMods.DataModel/Interprocess/SemaphoreSlimWaiter.cs
src/NexusMods.DataModel/Interprocess/SqliteIPC.cs
tests/NexusMods.DataModel.Tests/InterprocessTests.cs

Fixes #372. This is a follow-up to #501.
**Important Changes**:
- Use in-built connection pool, instead of our custom one for the IPC.
- Add `WriterLoop` and batching.
- Notify subscribers in-process about immediate changes of in-process jobs and messages.
- Optimize the hell out of the IPC.
Previously, sending a message, creating, update or deleting a job would always write to the database immediately. This caused a lot of lock contention in the database and slowed things down, as threads had to wait for the database to be available again.
This PR changes how we write to the IPC database. Instead of writing to it immediately, the job/message will be put into a queue. The `WriterLoop` will run periodically and batch insert/update/delete the items from the queue into the database. This …

Sqlite IPC Rework

---

src/Games/NexusMods.Games.TestHarness/Verbs/StressTest.cs
src/NexusMods.CLI/CliOptionSelector.cs

Two small fixes for the stress test code:
* Auto fail any mods that include fomods. This can be extended in the future to support a auto-select, but for now just error
* Don't download any mods > 512MB in size to avoid out of disk space issues on test runners

Two small stress test fixes

---

src/Networking/NexusMods.Networking.HttpDownloader/AdvancedHttpDownloader.cs
tests/Games/NexusMods.Games.TestFramework/AGameTest.cs

Two fixes
* Flush .ZIP files before returning from a test function, this might help with cases were we get ".zip is not an archive"
* Move the number of socket retries from 4 -> 16, because the network for the test runners on GH seem super flakey at times

Try and fix flakey tests

---

tests/Games/NexusMods.Games.TestFramework/AGameTest.cs
xunit.runner.json

Resolves #436 for the Darkest dungeon tests and likely others. We were creating zip archives in Create mode which for some reason was resulting in bad ZIP data. Added a comment and fixed the behavior. We could also pull in sharp compress, but this seems to do the trick just as well.

Fix "File is not an archive"

---

src/NexusMods.App/Program.cs
src/NexusMods.Common/ProtocolRegistration/IProtocolRegistration.cs
src/NexusMods.Common/ProtocolRegistration/ProtocolRegistrationLinux.cs
src/NexusMods.Common/ProtocolRegistration/ProtocolRegistrationWindows.cs
tests/NexusMods.DataModel.Tests/Harness/ADataModelTest.cs

On Linux, this involved setting the `Path=` field inside the `.desktop` file as specified in the original PR.  
On Windows, it was a matter of adding an additional value named `WorkingDirectory`, under the same registry key as the default commandline itself. 
Original issue (#513) mentions, that the Default Host Builder is scanning the current working directory recursively.
I had a look into its code; and found out that it was searching for `appconfig.json` and its possible variants (e.g. `appconfig.Development.json`; which are part of the default MSFT configuration system.
It was searching up from what it set as the default `Content Root`, which defaults to current working directory in `Host.CreateDefaultBuilder`. It is possible to replace this after the fact before calling `Build()`, …

Add Working Directory to .nxm Handler & Remove Default Host Builder (fixes #513)

---

.github/workflows/clean_environment_tests.yaml
tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/SkyrimLegendaryEditionTests/SkyrimLegendaryEditionTests.cs
tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/SkyrimSpecialEditionTests/SkyrimSpecialEditionTests.cs
tests/Networking/NexusMods.Networking.HttpDownloader.Tests/AdvancedHttpDownloaderTests.cs
tests/NexusMods.UI.Tests/Localization/BasicLocalizedTests.cs
tests/NexusMods.UI.Tests/Localization/BasicLocalizerTests.cs

Disabling flakey tests, don't merge yet, I'm going to be working on this a ton

Disable flakey tests in CI

---

src/NexusMods.App.UI/RightContent/Downloads/InProgressCommonViewModel.cs
src/NexusMods.App.UI/RightContent/Downloads/InProgressView.axaml.cs
tests/NexusMods.UI.Tests/RightContent/Downloads/InProgressViewModelTests.cs

closes #510 
Hides the UI element text for time remaining when throughput is effectively zero (paused)
Thought it was better hidden rather than saying "0 seconds remaining" which might be a bit misleading.
Normal:
Paused:

Hide remaining time in UI when paused

---

src/NexusMods.App.UI/Controls/DevelopmentBuildBanner/DevelopmentBuildBannerView.axaml.cs

In PR #574 I forgot to change `FileVersion` to `ProductVersion`. In the design in #567 the product version is shown, so this PR fixes that. The difference is shown here ("v0.1" instead of "v0.1.0.0"):

Show product version instead of file version in development build banner

---

docs/games/0001-SkyrimSE.md

`loadorder.txt` is only used in Skyrim LE. MO2 still uses it internally for SSE, but it's not loaded by the game.

Remove loadorder.txt section from SSE docs

---

src/Games/NexusMods.Games.FOMOD/FomodXmlInstaller.cs
src/NexusMods.CLI/CliGuidedInstaller.cs
src/NexusMods.Common/GuidedInstaller/GuidedInstallationStepValidator.cs
tests/NexusMods.Common.Tests/GuidedInstaller/GuidedInstallationStepValidatorTests.cs

- Added static GuidedInstallerValidation class containing two static validation methods, one for a single group, one for an entire step.
- Adds checks before proceeding with steps to make sure each group selection respects the requirements of the group (At least one, at most one, exactly one).
- Fixed Fomod installer creating GamePaths using unsanitized paths.

FOMOD validation for CLI

---

src/Games/NexusMods.Games.FOMOD/FomodAnalyzer.cs
src/NexusMods.CLI/CliGuidedInstaller.cs
src/NexusMods.Common/GuidedInstaller/GuidedInstallationStepValidator.cs

- Fix Fomod analyzer failing if directory of the referenced images is missing.
- Fix Fomod CLI installer clearing selections of other groups when dealing with "At most one" cases.
- Fix broken validation check on back operation due to missing Required options at that stage.
- Fix SkipAll wrongly adding selections for AtLeastOne groups that already had preselected stuff.

Fomod install fixes

---

NexusMods.App.sln
docs/decisions/backend/0009-advanced-installer-design.md
src/Games/NexusMods.Games.AdvancedInstaller/AdvancedInstaller.cs
src/Games/NexusMods.Games.AdvancedInstaller/DeploymentData.cs
src/Games/NexusMods.Games.AdvancedInstaller/DeploymentDataExtensions.cs
src/Games/NexusMods.Games.AdvancedInstaller/Exceptions/MappingAlreadyExists.cs
src/Games/NexusMods.Games.AdvancedInstaller/NexusMods.Games.AdvancedInstaller.csproj
src/Games/NexusMods.Games.AdvancedInstaller/ThrowHelpers.cs
tests/Games/NexusMods.Games.AdvancedInstaller.Tests/DeploymentDataEmitTests.cs
tests/Games/NexusMods.Games.AdvancedInstaller.Tests/DeploymentDataExtensionTests.cs
tests/Games/NexusMods.Games.AdvancedInstaller.Tests/DeploymentDataTests.cs
tests/Games/NexusMods.Games.AdvancedInstaller.Tests/NexusMods.Games.AdvancedInstaller.Tests.csproj
tests/Games/NexusMods.Games.AdvancedInstaller.Tests/Startup.cs
tests/Games/NexusMods.Games.AdvancedInstaller.Tests/Usings.cs

This PR implements the core/base of AdvancedInstaller; checklist and more details available here:
- https://github.com/Nexus-Mods/NexusMods.App/issues/635
The only thing not done is the mechanism that causes `AdvancedInstaller` to be invoked. 
The `AdvancedInstaller` IModInstaller is currently a stub. We decided that we still need to discuss with design how the Advanced Installer is to be invoked (e.g. should it be invoked if all other installers don't perform an operation? Should we prompt the user? etc.). 
Thus the activation logic is not included in this PR.

Added: Base Implementation of AdvancedInstaller Core

---

Directory.Packages.props
NexusMods.App.sln.DotSettings
src/NexusMods.App/AppConfig.cs
src/NexusMods.App/NexusMods.App.csproj
src/NexusMods.App/Program.cs
src/NexusMods.App/Services.cs
src/NexusMods.App/Telemetry.cs
src/NexusMods.DataModel/GlobalSettings/GlobalSettingsManager.cs
src/NexusMods.DataModel/GlobalSettings/Ids.cs

Resolves #432
~~**Note:** there are currently some issues with the backend. The PR can be reviewed but shouldn't be merged until the backend issues are resolved.~~

Add telemetry

---

docs/decisions/backend/0010-basic-advanced-installer-suggestions.md
src/Games/NexusMods.Games.BethesdaGameStudios/ABethesdaGame.cs
src/Games/NexusMods.Games.DarkestDungeon/DarkestDungeon.cs
src/Games/NexusMods.Games.RedEngine/Cyberpunk2077.cs
src/Games/NexusMods.Games.Sifu/Sifu.cs
src/Games/NexusMods.Games.StardewValley/StardewValley.cs
src/NexusMods.DataModel/Games/AGame.cs
src/NexusMods.DataModel/Games/GameCapabilities/FolderMatchInstallerCapability/IModInstallDestination.cs
src/NexusMods.DataModel/Games/GameCapabilities/FolderMatchInstallerCapability/InstallFolderTarget.cs
src/NexusMods.DataModel/Games/GameInstallation.cs
src/NexusMods.DataModel/Games/IGame.cs
src/NexusMods.DataModel/Games/Unknown/UnknownGame.cs
tests/Games/NexusMods.Games.AdvancedInstaller.Tests/ModInstallDestinationTests.cs
tests/NexusMods.StandardGameLocators.TestHelpers/StubbedGames/StubbedGame.cs

PR'ing the remaining work from last week.
All details available in:
- https://github.com/Nexus-Mods/NexusMods.App/issues/633
ADR has been updated accordingly for this PR.

Added: Basic Suggesions for AdvancedInstaller

---

Directory.Packages.props
src/Games/NexusMods.Games.BethesdaGameStudios/RunGameWithScriptExtender.cs
src/Games/NexusMods.Games.BethesdaGameStudios/SkyrimLegendaryEdition/SkyrimLegendaryEditionGameTool.cs
src/Games/NexusMods.Games.BethesdaGameStudios/SkyrimSpecialEdition/SkyrimSpecialEditionGameTool.cs
src/Networking/NexusMods.Networking.NexusWebApi.NMA/JWTTokenEntity.cs
src/Networking/NexusMods.Networking.NexusWebApi.NMA/LoginManager.cs
src/Networking/NexusMods.Networking.NexusWebApi.NMA/OAuth.cs
src/Networking/NexusMods.Networking.NexusWebApi.NMA/OAuth2MessageFactory.cs
src/Networking/NexusMods.Networking.NexusWebApi/DTOs/OAuth/JwtTokenReply.cs
src/NexusMods.App.UI/LeftMenu/Items/LaunchButtonViewModel.cs
src/NexusMods.DataModel/Games/AGame.cs
src/NexusMods.DataModel/Games/GameInstallation.cs
src/NexusMods.DataModel/Games/RunGameTool.cs

Run games through Steam

---

src/NexusMods.DataModel/Games/AGame.cs

To have the same functionality, you have to override `AGame.Installations` with copying the `AGame.GetInstallations()` method

Ability to set your own game version in AGame

---

src/NexusMods.App.UI/Initializers.cs
src/NexusMods.App.UI/NexusMods.App.UI.csproj
src/NexusMods.App.UI/NexusMods.App.UI.csproj.DotSettings
src/NexusMods.App.UI/Services.cs
src/NexusMods.App.UI/WorkspaceSystem/MathUtils.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/IPanelViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelComparer.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelDesignViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelId.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/AddPanelInput.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/IWorkspaceViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/RemovePanelInput.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceDesignViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspacePlaygroundView.axaml
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspacePlaygroundView.axaml.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspacePlaygroundViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceView.axaml
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceView.axaml.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceViewModel.cs
tests/NexusMods.UI.Tests/WorkspaceSystem/MathUtilsTests.cs

Part of #674.
- Adds a design-only playground for testing. This is currently the only place where the system is used, so the feature is completely isolated. The code for the playground is in constant change, so don't read into it too much.
- Adds a `Workspace` and `Panel` component:
- Panels can be added (split) and removed (join).
- Math is outside the VM and fully tested.

Initial support for Workspaces and Panels (split and join)

---

src/NexusMods.App.UI/NexusMods.App.UI.csproj
src/NexusMods.App.UI/NexusMods.App.UI.csproj.DotSettings
src/NexusMods.App.UI/Services.cs
src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/AddPanelButtonDesignViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/AddPanelButtonView.axaml
src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/AddPanelButtonView.axaml.cs
src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/AddPanelButtonViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/IAddPanelButtonViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/GridUtils.cs
src/NexusMods.App.UI/WorkspaceSystem/IconUtils.cs
src/NexusMods.App.UI/WorkspaceSystem/MathUtils.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/IPanelViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelId.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/PanelCreationInfo.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/AddPanelInput.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/IWorkspaceViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/RemovePanelInput.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspacePlaygroundView.axaml
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspacePlaygroundView.axaml.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspacePlaygroundViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceView.axaml.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceViewModel.cs
tests/NexusMods.UI.Tests/WorkspaceSystem/GridUtilsTests.cs
tests/NexusMods.UI.Tests/WorkspaceSystem/IconUtilsTests.cs
tests/NexusMods.UI.Tests/WorkspaceSystem/MathUtilsTests.cs

Part of #674 (after #688) and #676.
Changes:
- Adds `GridUtils`
- generate every possible layout state when layout changes
- generate new state when a panel should close
- Adds `IconUtils`
- generate icons for states on the fly (#676)
https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/a03ab29a-d139-4bf2-9a9c-e9702f1b90b0

Workspace Layout State and Image Generation

---

codecov.yaml

To make codecov better reflect our testing methodologies; update the codecov.yaml file to ignore .axaml and .g.cs files.

Tell codecov to ignore axaml and .g.cs

---

src/NexusMods.App.UI/App.axaml
src/NexusMods.App.UI/Controls/Buttons/StandardButton.cs
src/NexusMods.App.UI/Controls/Buttons/StandardButtonTheme.axaml
src/NexusMods.App.UI/Converters/TextCaseConverter.cs
src/NexusMods.App.UI/Icons/IconType.cs
src/NexusMods.App.UI/Icons/IconTypeConverter.cs
src/NexusMods.App.UI/Palatte/Nexus.xaml

This was mostly an experiment to see how well the new [Control Themes](https://docs.avaloniaui.net/docs/next/basics/user-interface/styling/control-themes) work in Avalonia.
Part of #735

Implement "Standard Button" using Control Themes

---

src/NexusMods.App.UI/App.axaml
src/NexusMods.App.UI/Palatte/Colors.axaml
src/NexusMods.App.UI/Palatte/Fonts.axaml

Add Colors and Fonts resources

---

docs/UICodingConventions.md
src/NexusMods.App.UI/ReactiveUIExtensions.cs

- Adds more context to OAPH
- Adds a section about design view models

More UI coding conventions

---

src/NexusMods.App.UI/LeftMenu/Items/LaunchButtonViewModel.cs
src/NexusMods.App.UI/RightContent/FoundGamesViewModel.cs
src/NexusMods.CLI/Services.cs
src/NexusMods.CLI/Verbs/Ingest.cs
src/NexusMods.DataModel/LoadoutSynchronizer/ALoadoutSynchronizer.cs
src/NexusMods.DataModel/Loadouts/LoadoutRegistry.cs

While prepping for the close of Milestone 2 actually used the app for once and discovered several issues:
* fixes #747 - (game files weren't ingested when managed)
* fixes #603 - manage game was running on the UI thread
* Fixes game freeze when launching app (game launching was on the UI thread)
* Fixed a massive performance regression caused by #626, resulting in the entire loadout being re-extracted on every launch of the game
* Added an Ingest cli command so we can fix loadouts when they break sometimes

Fix tons of little issues found while running the app through the UI

---

src/NexusMods.App.UI/Controls/Spine/SpineViewModel.cs
src/NexusMods.App.UI/RightContent/FoundGamesViewModel.cs
src/NexusMods.DataModel/LoadoutSynchronizer/ALoadoutSynchronizer.cs
src/NexusMods.DataModel/LoadoutSynchronizer/Exceptions/NeedsIngestException.cs
src/NexusMods.DataModel/ToolManager.cs

* When running a tool, if a ingest is required, the app now performs that ingest
* No longer tries to navigate to a new page on whatever thread requested the route (the router always uses the UI thread now)
* Loadout Syncronizer's "Needs Ingest" error now throws a specific error for better catching upstream
* Added logging to the ToolManager's Run process

Fixes for various crashes while managing and running games

---

src/Games/NexusMods.Games.BethesdaGameStudios/PluginSorter.cs
src/NexusMods.DataModel/Sorting/Rules/Before.cs
tests/NexusMods.DataModel.Tests/Harness/ALoadoutSynrconizerTest.cs
tests/NexusMods.DataModel.Tests/SortTests.cs

> the variant that After uses is what we want because it works better with our serializer

Made Before<,>.Other a required property

---

src/NexusMods.DataModel/ArchiveInstaller.cs
src/NexusMods.DataModel/LoadoutSynchronizer/ALoadoutSynchronizer.cs

Currently, only the built-in sort rules will be considered by `ALoadoutSynchronizer`. Since we have a special interface `IGeneratedSortRule`, it should be used by default, I think would be a better default behaviour from an extension developer point of view!  
I've also added SortRules propagation in ArchiveInstaller

Use IGeneratedSortRule rules by default

---

NexusMods.App.sln.DotSettings
src/NexusMods.App.UI/NexusMods.App.UI.csproj
src/NexusMods.App.UI/NexusMods.App.UI.csproj.DotSettings
src/NexusMods.App.UI/Theme/IconStyles.xaml
src/NexusMods.App.UI/WorkspaceSystem/GridUtils.cs
src/NexusMods.App.UI/WorkspaceSystem/MathUtils.cs
src/NexusMods.App.UI/WorkspaceSystem/Page/PageFactoryId.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml.cs
src/NexusMods.App.UI/WorkspaceSystem/PanelResizer/IPanelResizerViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/PanelResizer/PanelResizerView.axaml
src/NexusMods.App.UI/WorkspaceSystem/PanelResizer/PanelResizerView.axaml.cs
src/NexusMods.App.UI/WorkspaceSystem/PanelResizer/PanelResizerViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/IWorkspaceViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceView.axaml.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceViewModel.cs
tests/NexusMods.UI.Tests/WorkspaceSystem/GridUtilsTests.cs
tests/NexusMods.UI.Tests/WorkspaceSystem/MathUtilsTests.cs

Panel resizing

---

Directory.Packages.props

Dependabot failed to update this correctly and there are some fixes here that are relevat for us.

Bump TreeDataGrid package version 11.0.2

---

src/NexusMods.App/Services.cs

Small change to move the sync file into its correct directory.

Update SyncFile path

---

src/Networking/NexusMods.Networking.Downloaders/Tasks/NxmDownloadTask.cs
src/Networking/NexusMods.Networking.HttpDownloader/AdvancedHttpDownloader.cs

Fixes download getting double the progress value
Fixes #834

Use separate activity to report Chunk dl reading progress.

---

src/NexusMods.App.UI/WorkspaceSystem/NewTabPage/NewTabPageView.axaml
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/PanelTabHeader/IPanelTabHeaderViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/PanelTabHeader/PanelTabHeaderView.axaml
src/NexusMods.App.UI/WorkspaceSystem/PanelTabHeader/PanelTabHeaderView.axaml.cs
src/NexusMods.App.UI/WorkspaceSystem/PanelTabHeader/PanelTabHeaderViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspacePlaygroundView.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Resources/Palette/Colors/ElementColors.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/StylesIndex.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/WorkspaceSystem/PanelTabHeaderStyles.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/WorkspaceSystem/PanelViewStyles.axaml

Resolves #674.
- Tab header and tabs now have correct borders
- Fixes alignments and paddings

Workspace styling

---

src/NexusMods.App.UI/Controls/Spine/Buttons/Download/SpineDownloadButtonViewModel.cs
src/NexusMods.App.UI/RightContent/Downloads/InProgressViewModel.cs

Uses Observable.Defer to only start ticking when there is a subscription.
There should not be more than one subscription at a time, so there should not be multiple ticks generated from this.

Avoid download progress poll ticking while there are no active subscriptions

---

src/Abstractions/NexusMods.Abstractions.GuidedInstallers/GuidedInstallationStep.cs
src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs
src/Games/NexusMods.Games.FOMOD.UI/Group/GuidedInstallerGroupViewModel.cs
src/Games/NexusMods.Games.FOMOD.UI/Resources/Language.Designer.cs
src/Games/NexusMods.Games.FOMOD.UI/Resources/Language.resx
src/Games/NexusMods.Games.FOMOD.UI/Step/GuidedInstallerStepView.axaml
src/Games/NexusMods.Games.FOMOD.UI/Step/GuidedInstallerStepView.axaml.cs
src/Games/NexusMods.Games.FOMOD.UI/Step/GuidedInstallerStepViewModel.cs
src/Games/NexusMods.Games.FOMOD.UI/Window/GuidedInstallerWindow.axaml
src/Games/NexusMods.Games.FOMOD/CoreDelegates/UiDelegate.cs
src/Games/NexusMods.Games.FOMOD/FomodAnalyzer.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/GuidedInstaller/StepViewStyles.axaml
tests/Games/NexusMods.Games.FOMOD.Tests/FomodXmlAnalyzerTests.cs

- Fix #860 
- Fix #864 
- Fix #865 
- Fix #866 
- Improved Fomod progress bar accuracy when there are few steps or hidden steps.
- Fixed tests to detect failures in loading fomod images.
- Enabled Multithreading when extracting archives with 7zip.
- Switched highlighted option description and image, so that description would always be visible.
- Various padding/spacing fixes.
- Fix Caps on Finish button.
- Fix auto scrolling to last option when new step is loaded.

FOMOD installer fixes

---

Directory.Packages.props

- Update `Avalonia.Diagnostics` 11.0.6 -> 11.0.7
- Update `Avalonia.Svg.Ska` 11.0.0.10 -> 11.0.0.13

Manually update dependencies (Skia, Avalonia.Diagnostics)

---

src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/SpineDownloadButtonStyles.axaml

fix #887 
Hover arc color style was applied for all cases, not just the `.Progress` class.
This moves the style to `.Progress:pointerover`

Fix DownloadSpine button hover showing the blue Arc

---

src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridViewModel.cs
src/NexusMods.App.UI/Windows/MainWindow.axaml
src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/AddPanelDropDownView.axaml.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/ComboBox/ComboBoxStyles.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/WorkspaceSystem/PanelViewStyles.axaml

- Fixed various erratic behaviour of tab header area when resizing
- Disabled Add Panel button when it is empty
- Closed Add Panel Drop Down when item selection is changed
- Fixed missing bottom border of Scroll left button in tab are
- Basic MainWindow layout and border adjustments to match new designs
This PR:
Latest design:
Stuff still needs moving around

Workspace integration improvements

---

src/NexusMods.App.UI/Controls/Spine/Buttons/Download/ISpineDownloadButtonViewModel.cs
src/NexusMods.App.UI/Controls/Spine/Buttons/Download/SpineDownloadButtonDesignerViewModel.cs
src/NexusMods.App.UI/Controls/Spine/Buttons/Download/SpineDownloadButtonView.axaml
src/NexusMods.App.UI/Controls/Spine/Buttons/Download/SpineDownloadButtonView.axaml.cs
src/NexusMods.App.UI/Controls/Spine/Buttons/Download/SpineDownloadButtonViewModel.cs
src/NexusMods.App.UI/Controls/Spine/Buttons/Icon/IIconButtonViewModel.cs
src/NexusMods.App.UI/Controls/Spine/Buttons/Icon/IconButton.axaml
src/NexusMods.App.UI/Controls/Spine/Buttons/Icon/IconButton.axaml.cs
src/NexusMods.App.UI/Controls/Spine/Buttons/Icon/IconButtonViewModel.cs
src/NexusMods.App.UI/Controls/Spine/Buttons/Image/ImageButton.axaml
src/NexusMods.App.UI/Controls/Spine/Buttons/Image/ImageButton.axaml.cs
src/NexusMods.App.UI/Controls/Spine/SpineViewModel.cs
src/NexusMods.App.UI/Resources/Language.Designer.cs
src/NexusMods.App.UI/Resources/Language.resx

- Highlight active workspace button on the spine
- Add tooltips for spine buttons

Spine UI fixes (workspaces improvements)

---

src/Games/NexusMods.Games.StardewValley/Installers/SMAPIInstaller.cs
src/Games/NexusMods.Games.StardewValley/Sorters/SMAPISorter.cs
src/Games/NexusMods.Games.StardewValley/TypeFinder.cs

Fix SMAPI apply order

---

src/NexusMods.App.UI/WorkspaceSystem/Controllers/OpenPageBehavior.cs
src/NexusMods.App.UI/WorkspaceSystem/Controllers/WorkspaceController.cs
src/NexusMods.App.UI/WorkspaceSystem/NewTabPage/NewTabPageViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelViewModel.cs

- This avoids having to explicitly wrap the actual behavior with the OpenPageBehavior container when passing it, avoiding the awkward double new
Should make lines more concise and clearer to read

Add implicit conversion for `OpenPageBehvaior` entries

---

src/NexusMods.App.UI/Controls/UnifiedIcon/IconValue.cs
src/NexusMods.App.UI/Controls/UnifiedIcon/UnifiedIcon.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Resources/UnifiedIconControlTheme.axaml

Simplified the various existing Setters on `IconValue` to be easier to use from XAML.
They now take the original types of `string`, `IImage`, `Geometry` instead of the custom types used internally by `IconValue`.
This allows them to be set them inline instead of having to wrap them in the custom types.
This maintains the single `UnifiedIcon.Value` Api, but reduces the number of lines needed to define the contents of an icon from XAML.
Before:
```xml
<unifiedIcon:IconValue x:Key="ProjektankerIconValue">
<unifiedIcon:IconValue.ProjektankerIconValueSetter>
<unifiedIcon:ProjektankerIcon Value="mdi-cog" />
</unifiedIcon:IconValue.ProjektankerIconValueSetter>
</unifiedIcon:IconValue>
```
After:
```xml
<unifiedIcon:IconValue x:Key="ProjektankerIconValue" MdiValueSetter="mdi-cog"/>
```

Simplify crating `IconValue`s for `UnifiedIcon` from XAML 

---

Directory.Packages.props
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
tests/NexusMods.DataModel.Tests/ALoadoutSynchronizerTests.cs

Fixes #924
Basic test included.
Draft until PR in Paths is merged, 
- https://github.com/Nexus-Mods/NexusMods.Paths/pull/38
so I can include new dependency version.

Add Support for Setting Execute Bit on Linux based on Extension (fixes #924)

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
tests/Abstractions/NexusMods.Abstractions.DataModel.Entities.Tests/Startup.cs
tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/Startup.cs
tests/Games/NexusMods.Games.BladeAndSorcery.Tests/Startup.cs
tests/Games/NexusMods.Games.MountAndBlade2Bannerlord.Tests/Startup.cs
tests/Games/NexusMods.Games.RedEngine.Tests/Startup.cs
tests/NexusMods.CLI.Tests/Startup.cs
tests/NexusMods.DataModel.Tests/Startup.cs

Main was broken after #949
`ALoadoutSynchronizer()` was expected to have a single parameter by many subclasses or users, which broke when the Os param was added

Fix build on main

---

src/NexusMods.App.UI/Controls/FoundGames/FoundGamesViewModel.cs
src/NexusMods.App.UI/Controls/Spine/ISpineViewModel.cs
src/NexusMods.App.UI/Controls/Spine/SpineDesignViewModel.cs
src/NexusMods.App.UI/Controls/Spine/SpineViewModel.cs
src/NexusMods.App.UI/Services.cs
src/NexusMods.App.UI/TypeFinder.cs
src/NexusMods.App.UI/Windows/DesignWindowManager.cs
src/NexusMods.App.UI/Windows/IWindowManager.cs
src/NexusMods.App.UI/Windows/MainWindow.axaml.cs
src/NexusMods.App.UI/Windows/MainWindowViewModel.cs
src/NexusMods.App.UI/Windows/WindowManager.cs
src/NexusMods.App.UI/WorkspaceSystem/Context/DownloadsContext.cs
src/NexusMods.App.UI/WorkspaceSystem/Context/EmptyContext.cs
src/NexusMods.App.UI/WorkspaceSystem/Context/HomeContext.cs
src/NexusMods.App.UI/WorkspaceSystem/Context/LoadoutContext.cs
src/NexusMods.App.UI/WorkspaceSystem/Controllers/IWorkspaceController.cs
src/NexusMods.App.UI/WorkspaceSystem/Controllers/WorkspaceController.cs
src/NexusMods.App.UI/WorkspaceSystem/DataStore/WindowData.cs
src/NexusMods.App.UI/WorkspaceSystem/DataStore/WorkspaceData.cs
src/NexusMods.App.UI/WorkspaceSystem/NewTabPage/NewTabPageFactory.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceViewModel.cs

Save and restore last window session

---

.editorconfig
.globalconfig
NexusMods.App.sln
NexusMods.App.sln.DotSettings

Update formatting and diagnostics

---

.editorconfig
NexusMods.App.sln.DotSettings
NexusModsApp.sln.DotSettings

- Uses `sln.DotSettings` instead of `.editorconfig` for most values.
- Uses a more "default" experience with some settings.

Fix formatting

---

NexusMods.App.sln.DotSettings
src/Abstractions/NexusMods.Abstractions.DiskState/DiskStateTree.cs
src/Abstractions/NexusMods.Abstractions.DiskState/IDiskStateRegistry.cs
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/NexusMods.DataModel/Loadouts/DiskStateRegistry.cs
tests/NexusMods.DataModel.Tests/ALoadoutSynchronizerTests.cs

Resolves #871 
It seems like the problem was mostly due to us storing the previous disk state keyed by LoadoutId instead of on the game version. One we switch to using the game version it all seems to work correctly. I'll do more testing on the CLI and we can create a new PR if this doesn't go far enough for some reason

Ingest required error

---

src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/Diagnostic.cs
src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/DiagnosticMessage.cs
src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/DiagnosticTemplateBuilder.cs
src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Emitters/BuiltInEmitter.cs
src/Games/NexusMods.Games.StardewValley/Diagnostics.cs
src/NexusMods.App.Generators.Diagnostics/NexusMods.App.Generators.Diagnostics.Sample/ExampleDiagnostics.cs
src/NexusMods.App.Generators.Diagnostics/NexusMods.App.Generators.Diagnostics/DiagnosticTemplateIncrementalSourceGenerator.cs
tests/Games/NexusMods.Games.StardewValley.Tests/Emitters/001_MissingDependencyTests.cs
tests/NexusMods.App.Generators.Diagnostics.Tests/DiagnosticTemplateIncrementalSourceGeneratorTests.TestGenerator#TestNamespace.MyClass.Diagnostic1Template.g.verified.cs
tests/NexusMods.App.Generators.Diagnostics.Tests/DiagnosticTemplateIncrementalSourceGeneratorTests.cs
tests/NexusMods.DataModel.Tests/Diagnostics/DiagnosticManagerTests.cs
tests/NexusMods.DataModel.Tests/Diagnostics/DummyLoadoutDiagnosticEmitter.cs
tests/NexusMods.DataModel.Tests/Diagnostics/DummyModDiagnosticEmitter.cs

Part of #977 and required for #915.
Changes:
- Replaced `Diagnostic.Message` with `Diagnostic.Summary` and `Diagnostic.Details`.
- Added `AddValue<T>` to the message builder. This allows you to include any kind of data in the diagnostic message data struct.

More diagnostic improvements

---

src/Abstractions/NexusMods.Abstractions.DiskState/DiskStateTree.cs
src/Abstractions/NexusMods.Abstractions.DiskState/IDiskStateRegistry.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/IApplyService.cs
src/Abstractions/NexusMods.Abstractions.Serialization/Services.cs
src/NexusMods.App.UI/LeftMenu/Items/ApplyControlDesignViewModel.cs
src/NexusMods.App.UI/LeftMenu/Items/ApplyControlView.axaml
src/NexusMods.App.UI/LeftMenu/Items/ApplyControlView.axaml.cs
src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs
src/NexusMods.App.UI/LeftMenu/Items/IApplyControlViewModel.cs
src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuView.axaml
src/NexusMods.App.UI/Resources/Language.Designer.cs
src/NexusMods.App.UI/Resources/Language.resx
src/NexusMods.DataModel/ApplyService.cs
src/NexusMods.DataModel/Loadouts/DiskStateRegistry.cs
src/NexusMods.DataModel/ToolManager.cs
tests/NexusMods.DataModel.Tests/ApplyServiceTests.cs
tests/NexusMods.DataModel.Tests/ToolTests.cs
tests/NexusMods.StandardGameLocators.TestHelpers/ListFilesTool.cs

- fixes #986
- fixes #987
- fixes #984
- fixes #983
- Handles parts of #995
- Apply button now correctly shows up when current loadout revision != last applied revision
- Apply button now shows Activate text when you need to switch loadouts
- Apply button now ingests outside changes and merges uncommitted changes on top
- Launch button no longer applies, but still merges at the end of the run
- Last applied revision is now correctly saved and restored
- Bunch of Apply button styling fixes and improvements
This requires nuking the Datamodel. App will crash and burn otherwise as its missing lastAppliedRevision

Apply fixes and refinements

---

src/Abstractions/NexusMods.Abstractions.Installers/ModInstallerResult.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/Mods/Mod.cs
src/NexusMods.DataModel/ArchiveInstaller.cs

Allow installers to set mod metadata

---

Directory.Packages.props
src/Games/NexusMods.Games.StardewValley/StardewValley.cs

Also updates our path libraries to 0.8.
Fixes #1029.

Override `GetVersion` for Stardew Valley

---

src/Games/NexusMods.Games.StardewValley/Diagnostics.cs
src/Games/NexusMods.Games.StardewValley/Emitters/DependencyDiagnosticEmitter.cs
src/Games/NexusMods.Games.StardewValley/NexusMods.Games.StardewValley.csproj
src/Games/NexusMods.Games.StardewValley/Services.cs
src/Games/NexusMods.Games.StardewValley/WebAPI/ISMAPIWebApi.cs
src/Games/NexusMods.Games.StardewValley/WebAPI/SMAPIWebApi.cs

Resolves #1028.
- Adds `ISMAPIWebApi` for interacting with the SMAPI Web API
- Updates existing diagnostics with links to mod pages

Link mod pages

---

src/NexusMods.App.UI/WorkspaceSystem/GridUtils.cs
tests/NexusMods.UI.Tests/WorkspaceSystem/GridUtilsTests/GetPossibleStatesTests.cs

Part of #906.
Fixes the order in which the possible grid states are generated. Now, we prioritize and put the primary action first, rather than last, depending on the orientation.

Reorder grid states

---

Directory.Packages.props
src/Games/NexusMods.Games.StardewValley.SMAPI/NexusMods.Games.StardewValley.SMAPI.csproj

Built, ran tests, opened the App played around a bit to check for obvious issues, didn't notice any problems.

Dep updates

---

src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Left/ModContent/TreeEntry/ModContentTreeEntryView.axaml
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Left/ModContent/TreeEntry/ModContentTreeEntryView.axaml.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/Preview/TreeEntry/PreviewTreeEntryView.axaml
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/Preview/TreeEntry/PreviewTreeEntryView.axaml.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/SelectLocation/TreeEntry/SelectableTreeEntryView.axaml

This tiny PR brings makes the AdvancedInstaller's icon presentation strategy to match the strategy used in the new `View Mod Files` functionality.
i.e. Applying ViewModFiles PR Feedback to Advanced Installer
I.e. We now no longer hide icons, but swap them out.

Use single `UnifiedIcon` in Advanced Installer Views

---

.github/dependabot.yml
Directory.Packages.props

Fixes the build issues related to the source generator.

Downgrade the `Microsoft.CodeAnalaysis.CSharp*` packages

---

src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/Diagnostic.cs
src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/IDiagnosticMessageData.cs
src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/IDiagnosticWriter.cs
src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/Values/NamedLink.cs
src/Games/NexusMods.Games.StardewValley/Diagnostics.cs
src/Games/NexusMods.Games.StardewValley/Emitters/DependencyDiagnosticEmitter.cs
src/Games/NexusMods.Games.StardewValley/Emitters/MissingSMAPIEmitter.cs
src/NexusMods.App.Generators.Diagnostics/NexusMods.App.Generators.Diagnostics/DiagnosticTemplateIncrementalSourceGenerator.cs
src/NexusMods.App.UI/DiagnosticSystem/DiagnosticWriter.cs
src/NexusMods.App.UI/DiagnosticSystem/IValueFormatter.cs
src/NexusMods.App.UI/DiagnosticSystem/LoadoutReferenceFormatter.cs
src/NexusMods.App.UI/DiagnosticSystem/ModReferenceFormatter.cs
src/NexusMods.App.UI/DiagnosticSystem/NamedLinkFormatter.cs
src/NexusMods.App.UI/DiagnosticSystem/ValueFormatterCache.cs
src/NexusMods.App.UI/NexusMods.App.UI.csproj
src/NexusMods.App.UI/Services.cs
tests/NexusMods.App.Generators.Diagnostics.Tests/DiagnosticTemplateIncrementalSourceGeneratorTests.TestGenerator#TestNamespace.MyClass.Diagnostic1Template.g.verified.cs
tests/NexusMods.App.Generators.Diagnostics.Tests/DiagnosticTemplateIncrementalSourceGeneratorTests.cs

This is the first step towards rendering diagnostics in the UI. Diagnostic messages can now be written as plain text with all their fields populated.

Convert diagnostic messages into plain text

---

src/NexusMods.DataModel/FileHashCache.cs
src/NexusMods.DataModel/SqliteDataStore.cs

This PR adds a simple writer lock into `SqliteDataStore`, such that concurrent access to the database doesn't result in failure. 
Although we will deprecate the data store I also (just in case) timed the performance of real workloads against this PR. Difference is negligible.
For more details, see #1089 
----
fixes #1089

Added: A Writer Lock for SqliteDataStore

---

.github/workflows/git-builds.yaml

Fixes #1079. Using [`17 08,15 * * *`](https://crontab.guru/#17_08,15_*_*_*) as a schedule:
> At minute 17 past hour 8 and 15

Run git builds on schedule

---

src/NexusMods.DataModel/Diagnostics/DiagnosticManager.cs

Part of #1091, supersedes #1103.
Uses `Replay` to replay the last value to all current and future subscribers.

Use `Replay` instead of `Publish`

---

src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Left/ModContent/ModContentViewModel.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Left/ModContent/TreeEntry/IModContentTreeEntryViewModel.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/Preview/PreviewViewModel.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/Preview/TreeEntry/IPreviewTreeEntryViewModel.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/SelectLocation/SelectLocationViewModel.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/SelectLocation/TreeEntry/ISelectableTreeEntryViewModel.cs
src/NexusMods.App.UI/Controls/ModInfo/ModFiles/IModFilesViewModel.cs
src/NexusMods.App.UI/Controls/ModInfo/ModFiles/ModFilesDesignViewModel.cs
src/NexusMods.App.UI/Controls/ModInfo/ModFiles/ModFilesView.axaml
src/NexusMods.App.UI/Controls/ModInfo/ModFiles/ModFilesView.axaml.cs
src/NexusMods.App.UI/Controls/ModInfo/ModFiles/ModFilesViewModel.cs
src/NexusMods.App.UI/Controls/Trees/Files/FileTreeNodeDesignViewModel.cs
src/NexusMods.App.UI/Controls/Trees/Files/FileTreeNodeViewModel.cs
src/NexusMods.App.UI/Controls/Trees/Files/IFileTreeNodeViewModel.cs
src/NexusMods.App.UI/Helpers/TreeDataGrid/IDynamicDataTreeItem.cs
src/NexusMods.App.UI/Helpers/TreeDataGrid/IExpandableItem.cs
src/NexusMods.App.UI/Helpers/TreeDataGrid/TreeDataGridHelpers.cs
src/NexusMods.App.UI/TreeNodeVM.cs

-----------
Checks off `Consider unifying TreeNodeVM with the underlying flat item view model.` in
https://github.com/Nexus-Mods/NexusMods.App/issues/1048
Successor to:
- #1053 
Need to merge previous PR if you want a slightly cleaner diff against main, as this PR builds upon it.
(Or just look at the new commits since that PR in isolation)
------------
This is a prototype which shows an implementation of inlining what was formerly `TreeNodeVM` directly into the ViewModels, for cleanliness. This PR adds the new system for doing so via `IDynamicDataTreeItem<TItem, TKey>`, and implements it for the `View Mod Files` view. 
This PR is purely for feedback/iteration on the idea we had. i.e. a working prototype.
For @Al12rs and anyone else interested.
DynamicData tree creation changes from: …

Prototype: Eliminate TreeNodeVM

---

src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/IDiagnosticManager.cs
src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
src/NexusMods.DataModel/Diagnostics/DiagnosticManager.cs

Show diagnostic count

---

NexusMods.App.sln.DotSettings
src/NexusMods.App.UI/Controls/Diagnostics/DiagnosticEntryViewModel.cs
src/NexusMods.App.UI/Controls/Diagnostics/IDiagnosticEntryViewModel.cs
src/NexusMods.App.UI/Extensions/ClassesExtensions.cs
src/NexusMods.App.UI/Pages/Diagnostics/Details/DiagnosticDetailsView.axaml
src/NexusMods.App.UI/Pages/Diagnostics/Details/DiagnosticDetailsView.axaml.cs
src/NexusMods.App.UI/Pages/Diagnostics/Details/DiagnosticDetailsViewModel.cs
src/NexusMods.App.UI/Pages/Diagnostics/List/DiagnosticListView.axaml
src/NexusMods.App.UI/Pages/Diagnostics/List/DiagnosticListView.axaml.cs
src/NexusMods.App.UI/Pages/Diagnostics/List/DiagnosticListViewModel.cs
src/NexusMods.App.UI/Pages/Diagnostics/List/IDiagnosticListViewModel.cs
src/NexusMods.App.UI/Resources/Language.Designer.cs
src/NexusMods.App.UI/Resources/Language.resx
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Border/BorderStyles.axaml

Part of #1091.
- Fixes the horizontal line coloring:
- Adds chips with counts and filters
- Adds text for no diagnostics
- Adds the summary as a header to the details page:
- Adds some basic Markdown styling:

Various diagnostic UI improvements

---

.github/workflows/git-builds.yaml

Realized that we should let it run on Friday morning as well, so that anyone interested can try the latest commits from late Thursday during the weekend.

Run Git Builds on Fridays

---

src/NexusMods.App/AppConfig.cs

Fixes #959.
`AppConfigManager` can probably be removed once we have settings.

Use `$OWD` instead of `EntryDirectory`

---

src/Abstractions/NexusMods.Abstractions.Serialization/DataModel/EntityDictionary.cs
src/Abstractions/NexusMods.Abstractions.Serialization/DataModel/EntityExtensions.cs
src/Abstractions/NexusMods.Abstractions.Serialization/IDataStore.cs
src/NexusMods.DataModel/FileHashCache.cs
src/NexusMods.DataModel/NxFileStore.cs
src/NexusMods.DataModel/SqliteDataStore.cs
tests/NexusMods.DataModel.Tests/Harness/ADataModelTest.cs

This is a small set of patches that improve performance of writes by a few orders of magnitude.
It's around 10x faster on an NVMe SSD, maybe a bit more on slower mediums, not a big deal.
-------
The jist of these patches is adding bulk INSERT operations into our data store.
Previously, when we wrote items to the data store, each write would be its own separate transaction, i.e. on every write, for safety, the DB would synchronize with disk, so in the event of a data loss, things won't commit total complete annihilation. 
Unfortunately that's a tiiiiiny bit slow.
Anyway, this PR adds some bulk add operations to the DataStore, and uses them whenever it's known we need to insert a bunch of items at once in some places previously bottlenecked.
------
Note: Don't think too hard about this PR. …

Removed Database Transaction Bottlenecks

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ILoadoutSynchronizer.cs
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/IStandardizedLoadoutSyncronizer.cs
src/Games/NexusMods.Games.BethesdaGameStudios/BethesdaLoadoutSynchronizer.cs
src/NexusMods.App.UI/Controls/GameWidget/GameWidget.axaml.cs
src/NexusMods.App.UI/Controls/GameWidget/GameWidgetDesignViewModel.cs
src/NexusMods.App.UI/Controls/GameWidget/GameWidgetViewModel.cs
src/NexusMods.App.UI/Controls/GameWidget/IGameWidgetViewModel.cs
src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
src/NexusMods.DataModel/Loadouts/LoadoutRegistry.cs
tests/NexusMods.DataModel.Tests/ALoadoutSynchronizerTests.cs

closes #1138
Handles all the remaining items on the issue:
This changes how Mange game works. 
Before we were indexing the game folder, creating a loaodut with a mod with all the entries and adding that to the LoadoutRegistry. Then we would run an ingest on that loadout to backup all those files.
This created a loadout that was in a precarious state without all the game files backup up in it, something not desirable for other systems like diagnostics as well as the loadout popping up in the UI before it was supposed to be interacted with by the user.
We changed that here by running a Backup operation on the files directly after they are indexed, creating the loadout a single time with all the files already backed up and added.

Add GameWidget functionality and show loading while managing a new game

---

NexusMods.App.sln.DotSettings
src/NexusMods.CrossPlatform/NexusMods.CrossPlatform.csproj
src/NexusMods.CrossPlatform/Process/ProcessFactory.cs
src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationLinux.cs

- Logs process execution
- Fixes #1149 by using `APPIMAGE` environment variable instead of `Environment.ProcessPath`. 
- Fixes #1150 by escaping whitespace: `Release 0.4` -> `Release\ 0.4`

Protocol registration fixes on Linux

---

NexusMods.App.sln.DotSettings
src/Games/NexusMods.Games.StardewValley/Diagnostics.cs
src/Games/NexusMods.Games.StardewValley/Emitters/SMAPIGameVersionDiagnosticEmitter.cs
src/Games/NexusMods.Games.StardewValley/Services.cs
src/Games/NexusMods.Games.StardewValley/StardewValley.cs
src/NexusMods.DataModel/Diagnostics/DiagnosticManager.cs

Resolves #1168.
Adds three new diagnostics:
- **Critical**: Current game version is lower than the minimum supported version by SMAPI
- **Critical**: Current game version is newer than the maximum supported version by SMAPI
- **Suggestion**: SMAPI and no SMAPI mods are installed, you should install SMAPI to get started with modding Stardew Valley

More SMAPI diagnostics

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/Diff/DiskDiffEntry.cs
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/Diff/FileChangeType.cs
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/Diff/FileDiffTree.cs
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/Diff/LoadoutDiskSateDiffUtils.cs
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/NexusMods.Abstractions.Loadouts.Synchronizers.csproj.DotSettings
tests/NexusMods.DataModel.Tests/ALoadoutSynchronizerTests.CanLoadoutToDiskDiff.verified.txt
tests/NexusMods.DataModel.Tests/ALoadoutSynchronizerTests.cs
tests/NexusMods.DataModel.Tests/Harness/VerifiableFile.cs
tests/NexusMods.DataModel.Tests/NexusMods.DataModel.Tests.csproj

This adds an extension method to the LoadoutSyncrhonizer to compute a Diff tree between a loadout and a DiskState.
Part of 
- #1113 
Added a test to check if it worked and results seem correct

Apply diff backend

---

NexusMods.App.sln
src/Abstractions/NexusMods.Abstractions.Settings/ISettings.cs
src/Abstractions/NexusMods.Abstractions.Settings/ISettingsManager.cs
src/Abstractions/NexusMods.Abstractions.Settings/NexusMods.Abstractions.Settings.csproj
src/Abstractions/NexusMods.Abstractions.Settings/NexusMods.Abstractions.Settings.csproj.DotSettings
src/Abstractions/NexusMods.Abstractions.Settings/SectionId.cs
src/Abstractions/NexusMods.Abstractions.Settings/ServiceExtensions.cs
src/Abstractions/NexusMods.Abstractions.Settings/SettingsBuilder/IPropertyUIBuilder.cs
src/Abstractions/NexusMods.Abstractions.Settings/SettingsBuilder/ISettingsBuilder.cs
src/Abstractions/NexusMods.Abstractions.Settings/SettingsBuilder/ISettingsUIBuilder.cs
src/Abstractions/NexusMods.Abstractions.Settings/SettingsTypeInformation.cs
src/Abstractions/NexusMods.Abstractions.Settings/ValidationResult.cs
src/Examples/Examples.csproj
src/Examples/Settings/AddingSettings.cs
src/Examples/Settings/ConsumingSettings.cs
src/Examples/Settings/README.md
src/NexusMods.App/NexusMods.App.csproj
src/NexusMods.App/Services.cs
src/NexusMods.Settings/NexusMods.Settings.csproj
src/NexusMods.Settings/Services.cs
src/NexusMods.Settings/SettingsManager.cs

Part of #1182, resolves #396.
Initial implementation of the settings backend:
- Adds `ISettings` for all setting types.
- Adds `ISettingsManager` to get or change settings.
- Adds `ISettingsBuilder` to configure how settings appear in the UI.
Missing from this PR that are done in a separate PR as part of #1182:
- Moving existing setting types to the backend
- Persisting and loading the settings
- Allowing the user to change the settings via a UI

Settings Backend

---

src/Abstractions/NexusMods.Abstractions.Games/RunGameTool.cs
src/Networking/NexusMods.Networking.NexusWebApi/Auth/OAuth.cs
src/NexusMods.CrossPlatform/Helper.cs
src/NexusMods.CrossPlatform/Process/IOSInterop.cs
src/NexusMods.CrossPlatform/Process/OSInteropLinux.cs
src/NexusMods.CrossPlatform/Process/OSInteropOSX.cs
src/NexusMods.CrossPlatform/Process/OSInteropWindows.cs
tests/Networking/NexusMods.Networking.NexusWebApi.Tests/OAuthTests.cs

I don't know if this will fix issue #1151, but it will definitely allow us to debug the issue better.
Changes:
- `IOSInterop.OpenUrl` add a `fireAndForget` parameter. Opening Steam on Linux using `xdg-open` blocked the entire task until Steam exited. This was undesired, so we can now opt in to a fire-and-forget-style of task running.
- More logging in `RunThroughSteam` and `WaitForProcessToStart`.
- Increased timeout from 1 minute to 5 minute in case Steam or the game take too long to start.

Better `RunThroughSteam`

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs

This fixes a DB bottleneck on ingest when ingesting 60k files.
```
Before: 385.5658 s/op
After: 3.0254 s/op
```
\> 100x improvement.
Tested with `DiskToFileTree` benchmark in `loadoutsynchronizer-benchmarks` branch.

Perf: Persist ingested files in DiskToFileTree in batch

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs

- Fixes #1212 
As discussed with Tim, for now we will only ingest the deletions if the the deleted files on disk are still present in the new loadut.
If there is a deletion on disk that is also matched by a deletion in the loadout, pass that through.

Run Ingest in case of detected file deletions

---

src/NexusMods.App.UI/Controls/Settings/SettingEntries/ISettingEntryViewModel.cs
src/NexusMods.App.UI/Controls/Settings/SettingEntries/SettingEntryDesignViewModel.cs
src/NexusMods.App.UI/Controls/Settings/SettingEntries/SettingEntryView.axaml
src/NexusMods.App.UI/Controls/Settings/SettingEntries/SettingEntryView.axaml.cs
src/NexusMods.App.UI/Controls/Settings/SettingEntries/SettingInteractionControls/ISettingToggleViewModel.cs
src/NexusMods.App.UI/Controls/Settings/SettingEntries/SettingInteractionControls/SettingToggleControl.axaml
src/NexusMods.App.UI/Controls/Settings/SettingEntries/SettingInteractionControls/SettingToggleControl.axaml.cs
src/NexusMods.App.UI/Controls/Settings/SettingEntries/SettingInteractionControls/SettingToggleViewModel.cs
src/NexusMods.App.UI/NexusMods.App.UI.csproj
src/NexusMods.App.UI/Pages/Settings/ISettingsViewModel.cs
src/NexusMods.App.UI/Pages/Settings/SettingsDesignViewModel.cs
src/NexusMods.App.UI/Pages/Settings/SettingsPage.cs
src/NexusMods.App.UI/Pages/Settings/SettingsView.axaml
src/NexusMods.App.UI/Pages/Settings/SettingsView.axaml.cs
src/NexusMods.App.UI/Resources/Language.Designer.cs
src/NexusMods.App.UI/Resources/Language.resx
src/NexusMods.App.UI/Services.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Border/BorderStyles.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Border/FooterBorder.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/BareIconStyles.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/StylesIndex.axaml

- Added `SettingsView` page
- Added `SettingEntryView`: this is a reusable view that shows the name, description and restart requirements of any setting. It contains a ViewModelViewHost for the actual interaction control (e.g. toggleSwitch, ComboBox)
- Different implementations of `ISettingEntryViewModel` can provide different InteractionControls and handle value updates/validations etc.
- Downside is that we need a wrapper for simple controls like ToggleSwitch, just so we can swap them out using different VMs.

Main UI layouts for Settings page and setting entry

---

src/Games/NexusMods.Games.StardewValley/Diagnostics.cs
src/Games/NexusMods.Games.StardewValley/Emitters/DependencyDiagnosticEmitter.cs
src/Games/NexusMods.Games.StardewValley/Emitters/Helpers.cs
src/Games/NexusMods.Games.StardewValley/Emitters/MissingSMAPIEmitter.cs
src/Games/NexusMods.Games.StardewValley/Emitters/SMAPIGameVersionDiagnosticEmitter.cs
src/Games/NexusMods.Games.StardewValley/Emitters/SMAPIModDatabaseCompatibilityDiagnosticEmitter.cs
src/Games/NexusMods.Games.StardewValley/Emitters/VersionDiagnosticEmitter.cs
src/Games/NexusMods.Games.StardewValley/Installers/SMAPIInstaller.cs
src/Games/NexusMods.Games.StardewValley/Services.cs
src/Games/NexusMods.Games.StardewValley/StardewValley.cs

Resolves #1265.
- Fixes an issue with SMAPI versions, again.
- Upgrades the SMAPI submodule to `4.0.7`
- Adds two new diagnostics:

Add minimum game/api version diagnostics

---

Directory.Packages.props
src/NexusMods.App.UI/Controls/MarkdownRenderer/MarkdownRendererView.axaml.cs

Resolves #1270. Note that this also upgrades `Markdown.Avalonia.Tight` to `11.0.3-a1` which we use for rendering Markdown. This version upgrade breaks our styling for links, see https://github.com/whistyun/Markdown.Avalonia/issues/145 for more details.
Before:
After:

Upgrade Avalonia to 11.1.0 beta2

---

src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs
src/ArchiveManagement/NexusMods.FileExtractor/build/NexusMods.FileExtractor.targets

Fixes #1306.
Usage:
`NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR=1 dotnet build`

Use system extractor executable

---

src/NexusMods.App/Program.cs

This prevents the Design Preview process from locking the database, blocking actually running the app on windows after opening any xaml file in the IDE.
This makes it use the inMemoryDatabase.

Fix Design Preview process accessing and locking the database

---

src/Abstractions/NexusMods.Abstractions.FileStore/ArchiveMetadata/NestedArchiveMetadata.cs
src/Abstractions/NexusMods.Abstractions.FileStore/ArchiveMetadata/StreamBasedFileOriginMetadata.cs
src/Abstractions/NexusMods.Abstractions.FileStore/Downloads/DownloadAnalysis.cs
src/Abstractions/NexusMods.Abstractions.FileStore/NexusMods.Abstractions.FileStore.csproj
src/Abstractions/NexusMods.Abstractions.FileStore/TypeFinder.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/Mods/Mod.cs
src/Networking/NexusMods.Networking.Downloaders/Tasks/NxmDownloadTask.cs
src/NexusMods.App.UI/Pages/LoadoutGrid/Columns/ModInstalled/ModInstalledViewModel.cs
src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginEntry/FileOriginEntryViewModel.cs
src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginEntry/IFileOriginEntryViewModel.cs
src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPage.cs
src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPageViewModel.cs
src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/IFileOriginsPageViewModel.cs
src/NexusMods.App.UI/Services.cs
src/NexusMods.DataModel/FileOriginRegistry.cs
src/NexusMods.DataModel/Services.cs

- Closes #1284
- Closes #1210 
- Closes #1155
This implements the remaining missing features of the Mod Library as current designs.
- Filter entries by Game, if entry has no Game, it is shown.
- Compute and show "Downloaded" DateTime column which is either when a manual archive was first analyzed, or when a download was started.
- Show Version data if available (it is only present on NXM downloads)
- Compute and update "Added" DateTime column by querying the loadout mods for matches and getting the most recent CreatedAt time
- Excluded Nested archives (e.g. SMAPI internal archive) from showing up
- Used Nexus Mod page name if available instead of file name
I'm not completely happy with the subscriptions and the all the attributes shenanigans, but at least everything seems to work now.

Finish Mod Library

---

src/NexusMods.App/LoggingSettings.cs
src/NexusMods.App/Program.cs

I've intended to add this for months now. Adds a setting that removes the log to console feature of the app so that logs only go into the log files. Reduces spam on the console and in the pop-up window. The console window still appears on Windows as that's a strange windows thing we need to look into at some point, but likely after we merge #1345

Add a setting to not log to the console, just to log files

---

Directory.Packages.props
src/Games/NexusMods.Games.BethesdaGameStudios/PluginAnalyzer.cs

Upgrades almost all the dependencies in the app that are behind. Does not upgrade a SMAPI dependency (so we stay in sync with SMAPI) or the Bannerlord launcer code (that has a breaking change in a minor release)

Upgrade (almost) all the deps

---

src/NexusMods.App.UI/Controls/Spine/SpineViewModel.cs

This PR restores (uncomments) the code that navigates away from the current loadout if the current loadout is the loadout being deleted.
This was previously temporarily commented while the loadout removal detection was being corrected (also Spine bug).
But since @halgari fixed that up at the end of the last week, this is now OK to restore.

Restored: Navigating away from Deleted Loadout

---

src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPageView.axaml

Fixes #1378
Old Mod Library text looked like this:
When it should look like this:
Updated the grid to use template cells with custom styles on the text blocks
Now looks like this:
Also fixed the strange padding on the actions buttons by widening the column a bit:

Fix mod library styling

---

src/Networking/NexusMods.Networking.Downloaders/DownloadService.cs

Fixes #1311. On a normal shutdown, all in-progress downloads are canceled. But in the case of a hard crash they are not cleaned up on app restart. This adds a cleanup of orphaned download tasks on the startup of the app.

Cancel any orphaned tasks on startup.

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs

Fixes #1357 
Turns out, in my coding binge a few weeks ago, I missed that we store the deletes that need to be performed in a `toDelete` collection then run through later in that method and delete everything. I wasn't adding reified deletes to this list so the deletes were never executed. 
Example using the replication case from #1357

Fix reified deletes in Apply

---

tests/NexusMods.UI.Tests/AVmTest.cs
tests/NexusMods.UI.Tests/RightContent/LoadoutGridViewModelTests.cs

This should fix the flakey tests. In the past we were managing the StubbedGame on every single test. Since the stubbed game was created via DI all the tests in the process were sharing the same stubbed game, and that was somehow causing issues. I made this part of the test framework optional and we only ever use it in two tests, so we may be fine now?

Fix flakey tests

---

src/NexusMods.SingleProcess/CliServer.cs

The app takes way to long to shutdown. It turns out it's beause we were awaiting a `.CancelAsync()` call. Even when nothing is attached to this, it takes way to long to complete. This PR discards the task instead of awaiting it.

Fix slow shutdown

---

src/Networking/NexusMods.Networking.NexusWebApi/LoginManager.cs

fixes #1406 
Because we deleted first from `_jwtTokenRepository`, this would cause `_jwtTokenRepository.Observable` to be invoked.
When this calls `Verify`, the item would not be expired because we haven't actually called evict first.
Changing the order of events so we first invalidate the `CachedObject<UserInfo>` fixes the issue.

Fixed: Avatar Icon Not Disappearing on Logout

---

src/NexusMods.App/Commandline/CleanupVerbs.cs

This deletion should be recursive, or else it may fail depending on the order of directories obtained from code.
I forgot to set this to recursive when applying PR feedback.
And it slipped past review too.

Bugfix: Directory Cleanup on Unix should be Recursive

---

src/NexusMods.App.UI/LeftMenu/Items/IIconViewModel.cs
src/NexusMods.App.UI/LeftMenu/Items/IconView.axaml
src/NexusMods.App.UI/LeftMenu/Items/IconView.axaml.cs
src/NexusMods.App.UI/LeftMenu/Items/IconViewModel.cs
src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
src/NexusMods.App.UI/NexusMods.App.UI.csproj
src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridViewModel.cs
src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPageViewModel.cs

Resolves #1424.
Also adds badges for diagnostics instead of using `(count)` as before. Since the left menu doesn't know if the mod library page is currently open and visible, the badge will only be removed if the user actually clicks on the item.

Add left menu badges

---

.github/workflows/build-linux-pupnet.yaml
.github/workflows/build-windows-pupnet.yaml

With the upstream maintainer going on hiatus, thus meaning we can't get our changes available in an actual release build for the time being; this PR changes our existing build script to use a self-built version of PupNet directly from upstream's latest commit on `main` (`dabed0cc2063c5a2d2c4f780bb6718f4b90cfd16`).
I've made the changes in such a way such that they're as non-destructive as possible, i.e. as much of the existing build script is unaltered.
That's about it.
I (of course) forked the app and tested it works.
-----
With this, hopefully Windows can finally have proper uninstalls for real.

Added: Use Pinned PupNet Commit

---

src/Abstractions/NexusMods.Abstractions.Loadouts/Extensions/LoadoutExtensions.cs
src/Games/NexusMods.Games.StardewValley/Diagnostics.cs
src/Games/NexusMods.Games.StardewValley/Emitters/ModOverwritesGameFilesEmitter.cs
src/Games/NexusMods.Games.StardewValley/Services.cs
src/Games/NexusMods.Games.StardewValley/StardewValley.cs

Add diagnostic for mods that overwrite game files

---

src/NexusMods.App/TelemetryProvider.cs

Fixes a silent exception under the hood.

Telemetry/Vogen: Set Default Download Size

---

.github/workflows/build-linux-pupnet.yaml
.github/workflows/build-windows-pupnet.yaml
src/NexusMods.App/Commandline/CleanupVerbs.cs

This is a simple two set of patches:
- Replacing `Assembly.GetExecutingAssembly().Location`
- Single-File Apps don't have an assembly location. (Breaking change)
- So we use the folder used for resolving assemblies instead.
- Ensuring CI uses our locally built PupNet
- Depending on how NuGet is configured on Actions runner, there's a technical possibility it could install a release from `nuget.org`.
- So to avoid this, we build and install a custom version.
You can find a test CI Run at https://github.com/Sewer56/NexusMods.App/actions/runs/9302098600 . Binary  from that CI run is also on Slack.

Fixed: App Uninstallation in Single File Apps & Improve PupNet CI Build Step

---

src/NexusMods.App.UI/Pages/Diff/ApplyDiff/ApplyDiffView.axaml
src/NexusMods.App.UI/Pages/Downloads/InProgressView.axaml
src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridView.axaml
src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPageView.axaml
src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageView.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Border/Toolbar.xaml

This PR slightly improves how we present toolbars in the various user interface elements.
Previously, inner contents of every single toolbar was declared as something like:
```xaml
<Grid ColumnDefinitions="Auto, *">
<StackPanel Grid.Column="0" Orientation="Horizontal">
```
(Note: Some views had `Orientation == Horizontal` and some had `Alignment == Right`, both are redundant with our styles)
The first column of the Grid being reserved to represent the title.
However, ***none of our current views*** actually have a title on the toolbar, therefore this can be simplified to:
```xaml
<StackPanel>
```
Greatly reducing nesting, and making UI work easier.
When I was working with moving some of the buttons over from My Mods to Mod Library, I noticed this, and thus have cleaned up this unneeded …

Cleanup: Toolbars in App no longer include unused nesting.

---

src/NexusMods.App.UI/NexusMods.App.UI.csproj
src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridDesignViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridView.axaml

This re-adds a very minimal design VM for LoadoutGrid
The intent here is to have a preview of the toolbar.
In its current state, on the main branch the preview is completely broken, which makes edits more tedious.
----------
Note: When adding this, I kinda thought that there ought to be a better way to do this.
We still haven't had that talk about redundancy of Design ViewModels after standup, but when working on this, I kinda started to think to myself: `Can't we just DI Inject and use the standard ViewModel?`. I haven't yet tried to find out; but maybe that's worth investigating.

Re-added: A minimal dummy Design VM for LoadoutGrid Toolbar Support

---

docs/development-guidelines/UIStylingGuidelines.md
src/NexusMods.App.UI/Controls/Spine/Buttons/Icon/IconButton.axaml
src/NexusMods.App.UI/Controls/Spine/Buttons/Image/ImageButton.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Resources/Palette/Colors/ElementColors.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/SpineButtonStyles.axaml

- Fixes #1486
- Addresses some parts of #952 
Changed the UI of Loadout buttons in the Spine to be square.
Changed the Styles for ImageButtons to not be inherited by the ToolTips.

Spine Loadout ImageButtons Styling and Tooltip fix

---

src/Abstractions/NexusMods.Abstractions.Games/RunGameTool.cs
src/Games/NexusMods.Games.StardewValley/RunGameTools/SmapiRunGameTool.cs
src/NexusMods.App/Commandline/CleanupVerbs.cs
src/NexusMods.App/Program.cs
src/NexusMods.CrossPlatform/LoggingSettings.cs
src/NexusMods.CrossPlatform/NexusMods.CrossPlatform.csproj
src/NexusMods.CrossPlatform/Process/AOSInterop.cs
src/NexusMods.CrossPlatform/Process/FakeProcessFactory.cs
src/NexusMods.CrossPlatform/Process/IProcessFactory.cs
src/NexusMods.CrossPlatform/Process/OSInteropLinux.cs
src/NexusMods.CrossPlatform/Process/ProcessFactory.cs
src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationLinux.cs
tests/NexusMods.CrossPlatform.Tests/NexusMods.CrossPlatform.Tests.csproj
tests/NexusMods.CrossPlatform.Tests/OSInteropTests.cs
tests/NexusMods.CrossPlatform.Tests/ProtocolRegistrationTests.Linux.cs
tests/NexusMods.CrossPlatform.Tests/Startup.cs

Log process output

---

src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridViewModel.cs

This fixes the key from `AdvancedInstaller` to `AdvancedManualInstaller`.
The key got renamed alongside the class at some point, but it seems not all cases were renamed.
Fixes
- #1527
In simpler terms, AdvancedInstaller now shows up when you hit `Add Advanced` in the UI

Renamed: Key for AdvancedManualInstaller

---

src/Abstractions/NexusMods.Abstractions.Installers/IArchiveInstaller.cs
src/NexusMods.App.Cli/ProtocolVerbs.cs
src/NexusMods.App.Cli/Types/DownloadHandlers/NxmDownloadProtocolHandler.cs
src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridViewModel.cs
src/NexusMods.DataModel/ArchiveInstaller.cs
src/NexusMods.DataModel/CommandLine/Verbs/LoadoutManagementVerbs.cs
tests/Games/NexusMods.Games.TestFramework/AModInstallerTest.cs
tests/NexusMods.DataModel.Tests/Harness/ADataModelTest.cs
tests/NexusMods.UI.Tests/AVmTest.cs

This should hopefully
- fix #1541 
fingers crossed
There are two reasons that test is failing on the CI:
- If an archive is installed multiple times, we were using the previous name, so the test was expecting a mod with a specific name, but wouldn't find it.
- Other problem is that the archive is not supposed to be installed multiple times, so this test is sharing the DataStore with other concurrent tests, which are also installing the same file concurrently, which should not be happening.
This PR only fixes the first problem, which is also a UX problem for normal users.
The sharing db in the tests is an issue that we also need to fix but outside the scope for this.

Add ability to set mod name in `ArchiveInstaller.AddMods()`

---

tests/NexusMods.StandardGameLocators.Tests/BasicTests.cs

In Game Finder
@erri120 Just a heads up that this will need to be enabled back in once we add support for GamePass again

Fix Test_Locators_Windows failing on xboxGamePass since it was disabled

---

src/Games/NexusMods.Games.FOMOD.UI/Step/GuidedInstallerStepViewModel.cs
src/NexusMods.App.UI/Controls/MarkdownRenderer/MarkdownRendererViewModel.cs
src/NexusMods.App.UI/Extensions/ReactiveExtensions.cs
src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageViewModel.cs
src/NexusMods.App.UI/Windows/MainWindowViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/PanelResizer/PanelResizerView.axaml.cs

Was tricky to pin down since stack trace didn't help. 
In the end I noticed it happened right after login and after a code search for `InvokeCommand` I found it.
Following @erri120 advice I added a couple of wrapper extensions for `InvokeCommand` that would not accept `ICommand`, resulting in better static type checking, which should prevent a similar issue from happening in the future.

Fix command expected Unit, but received bool exception

---

src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/BareIconStyles.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/ButtonStyles.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/HyperlinkStyles.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/PillStyles.xaml

@captainsandypants is happy with the global  removal of transform scale, and I've commented out the press state as it doesn't make sense until the active state is implemented
Fixes #1609

Remove transform scale on left menu button click

---

src/Networking/NexusMods.Networking.NexusWebApi/LoginManager.cs
src/Networking/NexusMods.Networking.NexusWebApi/Services.cs
src/NexusMods.App/Program.cs
src/NexusMods.App/Services.cs
src/NexusMods.SingleProcess/CliServer.cs
src/NexusMods.SingleProcess/NexusMods.SingleProcess.csproj
src/NexusMods.SingleProcess/Services.cs
tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/Startup.cs
tests/Games/NexusMods.Games.BladeAndSorcery.Tests/Startup.cs
tests/Games/NexusMods.Games.DarkestDungeon.Tests/Startup.cs
tests/Games/NexusMods.Games.FOMOD.Tests/Startup.cs
tests/Games/NexusMods.Games.MountAndBlade2Bannerlord.Tests/Startup.cs
tests/Games/NexusMods.Games.RedEngine.Tests/Startup.cs
tests/Games/NexusMods.Games.Sifu.Tests/Startup.cs
tests/Games/NexusMods.Games.StardewValley.Tests/Startup.cs
tests/Games/NexusMods.Games.TestFramework/DependencyInjectionHelper.cs
tests/Games/NexusMods.Games.TestFramework/NexusMods.Games.TestFramework.csproj
tests/Networking/NexusMods.Networking.Downloaders.Tests/Startup.cs
tests/Networking/NexusMods.Networking.NexusWebApi.Tests/Startup.cs
tests/NexusMods.CLI.Tests/Startup.cs

- fixes #515
- Slim process was not spawning new main process due to missing `LoggingSetting` in DI for `ProcessFactory`
- Fixed that, the DL was being skipped due to login check returning false
- `LoginManger` wouldn't have data until DB was initialized
- Had to make the `LoginManger` into a `HostedService` and await in `StartAsync()` on the db to be ready.
- This initialized the UserData from DB, but `CliServer.StartAsync()` started listening before that.
- Changed `CliServer` to require explicit `StartCliServerAsync` call in `Program.cs`
- `CliServer` is only started after all the other `HostedServices` have initialized.
- Removed hack workaround where `CliServer` was waiting for `GameRegistry` to initialize in `StartAsync`.
- Fixed DI for all serviced that used either `PrcessFactory` …

Fix nxm downloads not opening the App if app is closed

---

src/NexusMods.App.UI/WorkspaceSystem/Page/APageViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Page/IPageViewModelInterface.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceViewModel.cs

Part 1 of #1372. This adds `CanClose` method that pages can implement. Part 2 will be a confirmation overlay/modal for unsaved changes in the text editor.

Add `CanClose`

---

src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
src/NexusMods.CrossPlatform/Process/AOSInterop.cs
src/NexusMods.CrossPlatform/Process/IOSInterop.cs

Resolves #1588.
Re-uses the same code we have for opening URIs by created a `file://` URI. Tested on both Linux and Windows.
It's not the best solution, and I'll probably change this to just use `explorer.exe` and `xdg-open` directly, after doing #163.

Implement `OpenDirectory` and enable TopBar button

---

src/Networking/NexusMods.Networking.Downloaders/DownloadService.cs
src/Networking/NexusMods.Networking.Downloaders/Services.cs
src/NexusMods.App/Program.cs
src/NexusMods.App/Services.cs

Closing app with ongoing downloads caused infinite hang, had to make several adjustments to get the app to close cleanly for now.
Downloads are currently cancelled on close, fixing that will require more involved changes for another PR.
See commit messages for details on reasons for some of the changes.
Open to suggestions for better approaches as I'm not necessarily convinced this to be the best solution.

Fix app not disposing service host correctly

---

src/NexusMods.App.UI/Pages/Downloads/InProgressView.axaml
src/NexusMods.App.UI/Pages/Downloads/ViewModels/DownloadTaskDesignViewModel.cs
src/NexusMods.App.UI/Pages/Downloads/ViewModels/DownloadTaskViewModel.cs
src/NexusMods.App.UI/Pages/Downloads/ViewModels/IDownloadTaskViewModel.cs
src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPageView.axaml

- fix #1616 
Fixes sorting for Mod Library and Completed Downloads section.
`DataGridTemplateColumn` needs `SortMemberPath` to know which property to use for sorting.
The ugly part is that it takes a string rather than a binding or something Type checkable.

Fix DataGrid sorting

---

Directory.Packages.props
src/NexusMods.App/Services.cs
src/NexusMods.DataModel/GameRegistry/GameRegistry.cs
src/NexusMods.DataModel/Services.cs

Summary:
- Removed game registry waiting on Db initialization since it should already be ready.
- Renamed the game `Registry` to `GameRegistry` for clarity
- Made the execution of different `HostedServices` `StartAsync` and `StopAsync` calls concurrent
- `StartAsync` for performance reasons
- `StopAsync` to avoid one call stalling and preventing the others from executing before the timeout. 
I tried moving the `StartAsync` of `DownloadService` into the constructor since it wasn't actually async, but I got infinite loading on startup due to DI getting stuck when trying to resolve new `DownloadTasks` from loaded download states.
Didn't really manage to figure out the cause for that.

Upgrade to MenmonicDB sync startup

---

Directory.Packages.props
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/Networking/NexusMods.Networking.Downloaders/DownloadService.cs
src/Networking/NexusMods.Networking.NexusWebApi/Auth/JWTToken.cs
src/NexusMods.DataModel/NxFileStore.cs
tests/Games/NexusMods.Games.StardewValley.Tests/StardewValleySynchronizerTests.cs

Updates to the latest version of MnemonicDB which introduces some small *code only* breaking changes to the API. Firstly, all the query methods on `IDb` now return `IndexSegment` instead of `IEnumerable<Datom>`, they were already `IndexSegment` internally, so this exposes some optimization options. 
Secondly we now support multiple `Include<T>` attributes on models, in order maintain consistent ids in construction, the including model must either create a id (and return it via `out`) or use a pre-defined Id. Further examples can be seen here (https://github.com/Nexus-Mods/NexusMods.MnemonicDB/blob/main/tests/NexusMods.MnemonicDB.Tests/DbTests.cs#L627-L689). The model construction code will throw if any included entity does not have the same Id when it is assigned. This change makes the …

Update to the new Include model structure in MnemonicDB

---

src/NexusMods.CrossPlatform/Process/ProcessFactory.cs

Current formatting results in file name containing `:` symbol and so file creation fails. Basically it results in something like
```
PenDriverPro.exe-2024-07-08T02:05:41.stdout.log
```
And since the path isn't validated in any way it fails with 
```
00:00:21.847 [ERROR] (NexusMods.App.Program) Encountered an exception published to an object with an unobserved ThrownExceptions property|System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\██████\AppData\Local\NexusMods.App\Logs\ProcessLogs\PenDriverPro.exe-2024-07-08T02:05:41.stdout.log'
at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String …
```

[CrossPlatform][ProcessFactory] fix log file creation

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs

Fix loadout disappearing from spine

---

src/NexusMods.App.Generators.Diagnostics/NexusMods.App.Generators.Diagnostics/NexusMods.App.Generators.Diagnostics.csproj

For reasons yet unknown `NexusMods.App.Generators.Diagnostics` targeting `netstandard2.1` results in the compiler not being able to load the emitted DLL. Switching to `netstandard2.0` resolves this issue. Most of the dependencies don't even have `2.1` targeting versions, only 2 do.
Unless you specifically need `2.1` this seems to be a valid solution for now. As a bonus while `2.1` and `2.0` are supposed to be compatible having all the deps and the project on a single version is better - reduces the risk of unintended shenanigans.

[VS2022] fix build

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/Rules/Actions.cs

currently `DeleteFromDisk` action was ordered after `ExtractToDisk` action which in combination of the 2 resulted in a deleted file instead of a replaced one, it looks like actions need reordering but I am not too sure about the side effects so a draft. Also, bitshift, in C# should be endianness independent.

[Loadouts.Synchronizers][Actions] change action order

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/Rules/Signature.cs
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/Rules/SignatureShorthand.cs

Replaces direct numbers with `Signature` values and replaces comments with what I hope is a more understandable summary. This way variable assignment in the tooltip fulfils the same role the older comment did and the comment itself makes understanding the shorthand easier.
Also uses shift in `Signature`

Make `SignatureShorthand` more readable

---

src/Abstractions/NexusMods.Abstractions.Library.Installers/ALibraryArchiveInstaller.cs
src/Abstractions/NexusMods.Abstractions.Library.Installers/ALibraryFileInstaller.cs
src/Abstractions/NexusMods.Abstractions.Library.Installers/ALibraryItemInstaller.cs
src/Abstractions/NexusMods.Abstractions.Library.Installers/ILibraryArchiveInstaller.cs
src/Abstractions/NexusMods.Abstractions.Library.Installers/ILibraryFileInstaller.cs
src/Abstractions/NexusMods.Abstractions.Library.Installers/ILibraryItemInstaller.cs
src/Abstractions/NexusMods.Abstractions.Library.Models/LibraryArchive.cs
src/Abstractions/NexusMods.Abstractions.Library.Models/LibraryArchiveFileEntry.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/LoadoutItem.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/LoadoutItemGroup.cs
src/NexusMods.Library/AddLibraryFileJobWorker.cs
src/NexusMods.Library/InstallLoadoutItemJob.cs
src/NexusMods.Library/InstallLoadoutItemJobWorker.cs
src/NexusMods.Library/LibraryService.cs

Part of #1763, will conflict with #1799.
Changes:
- adds `Path` to `LibraryArchiveFileEntry`
- uses `MarkerAttribute` for `LoadoutItem.IsDisabled`
- renamed existing markers and updated usage to set them
- updated the installer API with a simpler `IsSupported`
- updated the job worker to skip unsupported installers
There is one issue here:
The job worker for installing a loadout item passes a transaction to each of the installer. If the installer doesn't support the item, we need to retract all entities it has added to the transaction before continuing. Not sure what's the best approach here @halgari.

Loadout Item API update

---

src/Abstractions/NexusMods.Abstractions.FileExtractor/ISignatureChecker.cs
src/Abstractions/NexusMods.Abstractions.Jobs/IJob.cs
src/Abstractions/NexusMods.Abstractions.Library.Installers/Extensions.cs
src/Abstractions/NexusMods.Abstractions.Library/ILibraryService.cs
src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs
src/ArchiveManagement/NexusMods.FileExtractor/FileExtractor.cs
src/ArchiveManagement/NexusMods.FileExtractor/FileSignatures/SignatureChecker.cs
src/Games/NexusMods.Games.StardewValley/Installers/SMAPIInstaller.cs
src/Games/NexusMods.Games.StardewValley/Installers/SMAPIModInstaller.cs
src/Games/NexusMods.Games.StardewValley/Models/SMAPILoadoutItem.cs
src/Games/NexusMods.Games.StardewValley/Models/SMAPIManifestLoadoutFile.cs
src/Games/NexusMods.Games.StardewValley/Models/SMAPIManifestMetadata.cs
src/Games/NexusMods.Games.StardewValley/Models/SMAPIMarker.cs
src/Games/NexusMods.Games.StardewValley/Models/SMAPIModDatabaseLoadoutFile.cs
src/Games/NexusMods.Games.StardewValley/Models/SMAPIModDatabaseMarker.cs
src/Games/NexusMods.Games.StardewValley/Models/SMAPIModLoadoutItem.cs
src/Games/NexusMods.Games.StardewValley/Models/SMAPIModMarker.cs
src/Games/NexusMods.Games.StardewValley/Services.cs
src/Games/NexusMods.Games.StardewValley/StardewValley.cs
src/NexusMods.DataModel/ArchiveInstaller.cs
src/NexusMods.DataModel/FileOriginRegistry.cs
src/NexusMods.Library/AddLibraryFileJob.cs
src/NexusMods.Library/AddLibraryFileJobWorker.cs
src/NexusMods.Library/AddLocalFileJob.cs
src/NexusMods.Library/AddLocalFileJobWorker.cs

Part of #1763, requires #1801, conflicts with #1799.
This also contains many miscellaneous fixes to the library and job system, as well as making the `SignatureChecker` thread-safe.
This is missing tests, I'll add those after #1799 gets merged. The SMAPI installer is not complete yet, it's missing access to the game files.

Convert Stardew Valley installers

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/DeletedFile.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/LoadoutGameFilesGroup.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/NexusMods.Abstractions.Loadouts.csproj
src/Abstractions/NexusMods.Abstractions.Loadouts/Services.cs
tests/NexusMods.DataModel.Tests/ApplyServiceTests.cs

Part of #1763.
- enables `DeletedFile` model and fixes imports
- adds `LoadoutGameFilesGroup`
- updates the synchronizer to create groups per location
Planned for #1763 is putting game files in some capacity into the library as well. This would also remove the need for a "vanilla state loadout".

Add `LoadoutGameFilesGroup`

---

src/Abstractions/NexusMods.Abstractions.Library/ILibraryService.cs
src/Games/NexusMods.Games.RedEngine/ModInstallers/RedModInstaller.cs
src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridViewModel.cs
src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginEntry/FileOriginEntryViewModel.cs
src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginEntry/IFileOriginEntryViewModel.cs
src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPageViewModel.cs
src/NexusMods.Library/InstallLoadoutItemJob.cs
src/NexusMods.Library/InstallLoadoutItemJobWorker.cs
src/NexusMods.Library/LibraryService.cs

Converts the internals of the FileOrigin Page/ViewModel over to `ILibraryService`. 
The loop of Download->Install->Sync->Disable->Sync has been hand verified by me. NXM links also work, but the name in the library is all whack. We'll handle that in a separate PR.

FileOriginViewModel to Library

---

docs/developers/decisions/backend/0015-loadout-items.md
src/NexusMods.App.UI/Controls/LoadoutCard/Standard/LoadoutCardViewModel.cs

Also fixes the count on the loadout card.
Part of #1763.

Add Loadout Items ADR

---

Directory.Packages.props
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/FlexPanel/FlexPanelStyles.axaml

- fix #1816 
and other resizing related crashes caused by old FlexPanel version.
I tested the app with the labs version with the fixes and am no longer able to reproduce the crashes.

Fix FlexPanel crashes by updating Avalonia Labs version

---

src/Abstractions/NexusMods.Abstractions.Loadouts/Loadout.cs

Improves the performance of finding loadout items that link to a given library item. 
Before:
* For each item in the loadout (there could be thousands)
* Try to convert it to a Library linked item: O(n) filter
* See if the item points to the library item we're looking for
Complexity: O(loadoutItems * libraryItems)
After:
* Find all the loadout items that link to a given library item
* Filter out those that are from the wrong loadout O(n)
Complexity: O(libraryItems * loadouts with those libary items)
Since we will likely have only a few loadouts for a given library item, this should always be a performance win.

Fix for loadout->library item links

---

src/Abstractions/NexusMods.Abstractions.Loadouts/Loadout.cs
src/NexusMods.App.UI/Controls/LoadoutCard/Standard/LoadoutCardViewModel.cs
src/NexusMods.App.UI/Filters/LoadoutUserFilters.cs
src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridViewModel.cs

Instead of filtering per-item, this filters on all items.

Improve `LoadoutUserFilters` performance

---

Directory.Packages.props
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ILoadoutSynchronizer.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/LoadoutObservables.cs
src/NexusMods.App.UI/Controls/LoadoutCard/Standard/LoadoutCardView.axaml
src/NexusMods.App.UI/Controls/LoadoutCard/Standard/LoadoutCardViewModel.cs
src/NexusMods.App.UI/Filters/LibraryUserFilters.cs
src/NexusMods.App.UI/Pages/LocalFileDataProvider.cs
src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
src/NexusMods.App.UI/Pages/MyLoadouts/GameLoadoutsSectionEntry/GameLoadoutsSectionEntryViewModel.cs
src/NexusMods.App.UI/Pages/MyLoadouts/MyLoadoutsViewModel.cs
src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
src/NexusMods.App/TelemetryProvider.cs
tests/NexusMods.DataModel.Synchronizer.Tests/GeneralLoadoutManagementTests.SynchronizerIntegrationTests.verified.md
tests/NexusMods.DataModel.Synchronizer.Tests/GeneralLoadoutManagementTests.cs

Allows users to clone loadouts. This is a shockingly fast operation. Even with 50k files the clone time is less than a second. 
*Note:* this PR also updates to the latest MnemonicDB which while it's faster also changes `ObserveDatoms` to return a `IChangeSet<Datom, DatomKey>` I fixed most of the code by using `.RemoveKey()` but we likely will want to go back later and remove these method calls and update the Observable chains to also use keyed changesets.
Example usage:
fixes #406

Copy Loadouts

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/NexusMods.App.UI/Controls/Spine/SpineViewModel.cs

Checked in with design to update the following:
- Changed loadout naming scheme to `"Loadout " + ShortName` from `GameName  + " " + ShortName`
- Fixed CopyLoadout from considering short names of other game installs when generating new `ShortName`
- Updated Spine Loadout ToolTips to show `GameName + " - " + LoadoutName`

Update loadout naming

---

src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/Emitters/PatternDefinitions.cs

Adds the following diagnostic:
* `.preset` files for the Appearance Change Unlocker alert if ACU isn't installed/enabled
* `.reds` files in `r6` now alert if red4ext is not installed/enabled

Refine Cyberpunk 2077 diagnostics

---

src/Abstractions/NexusMods.Abstractions.Jobs/AJobWorker.cs
src/Abstractions/NexusMods.Abstractions.Jobs/IJobMonitorExtensions.cs
src/Abstractions/NexusMods.Abstractions.Jobs/Percent.cs
src/Networking/NexusMods.Networking.HttpDownloader/BytesPerSecondFormatter.cs
src/Networking/NexusMods.Networking.HttpDownloader/HttpDownloadJob.cs
src/Networking/NexusMods.Networking.HttpDownloader/HttpDownloadJobWorker.cs
src/Networking/NexusMods.Networking.HttpDownloader/HttpDownloaderSettings.cs
src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.cs
src/NexusMods.App.UI/Controls/Spine/Buttons/Download/ISpineDownloadButtonViewModel.cs
src/NexusMods.App.UI/Controls/Spine/Buttons/Download/SpineDownloadButtonDesignerViewModel.cs
src/NexusMods.App.UI/Controls/Spine/Buttons/Download/SpineDownloadButtonViewModel.cs
src/NexusMods.App.UI/Pages/Downloads/IInProgressViewModel.cs
src/NexusMods.App.UI/Pages/Downloads/InProgressView.axaml
src/NexusMods.App.UI/Pages/Downloads/InProgressView.axaml.cs
src/NexusMods.App.UI/Pages/Downloads/InProgressViewModel.cs
src/NexusMods.App.UI/Resources/Language.Designer.cs
src/NexusMods.App.UI/Resources/Language.resx
tests/NexusMods.UI.Tests/Controls/Spine/DownloadButtonViewTests.cs

As discussed, wires up the download spine button to the new job manager, also disables the contents of the Downloads panel and replaces them with a message and a progress bar. It's super simple, but gets the message across
The download happened to fast to see it in that image, but we do get a download speed update in the button still:

Disable download page & Wire up the download spine button

---

src/NexusMods.DataModel/CommandLine/Verbs/LoadoutManagementVerbs.cs
src/NexusMods.Library/InstallLoadoutItemJobWorker.cs
tests/NexusMods.CLI.Tests/VerbTests/ModManagementVerbs.cs

Fixes a regression caused by incorrect boolean logic around how we fallback to advanced installers. It's a 3-state situation, not a 2 state

Fix some of the CLI commands and fix logic with the mod installer fallback to advanced installer

---

src/Games/NexusMods.Games.StardewValley/Emitters/DependencyDiagnosticEmitter.cs
src/Networking/NexusMods.Networking.HttpDownloader/HttpDownloaderSettings.cs

Enabled mods showed up as disabled.

Fix Stardew Valley disabled diagnostic

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
tests/Games/NexusMods.Games.TestFramework/ACyberpunkIsolatedGameTest.cs
tests/Games/NexusMods.Games.TestFramework/AIsolatedGameTest.cs
tests/Games/NexusMods.Games.TestFramework/GithubIssueAttribute.cs
tests/Games/NexusMods.Games.TestFramework/NexusMods.Games.TestFramework.csproj
tests/NexusMods.DataModel.Synchronizer.Tests/GeneralLoadoutManagementTests.cs
tests/NexusMods.DataModel.Synchronizer.Tests/Startup.cs
tests/NexusMods.DataModel.Synchronizer.Tests/SynchronizerUnitTests.cs

- fixes #1925
- Could maybe fix #1907  
To explain the fix, the function created a hashset of existing file paths and was using `hashSet.Contains(parentPath)` to check whether a parent folder had any children, this always returned false, since the hashset contained the file paths, not parent paths. This change builds a hashset of all the parent paths, so the check works correctly.
Probably not the most efficient way to do the entire directory check but this is the simplest fix.

Fix CleanDirectories deleting folders still containing other files

---

Directory.Packages.props
src/Abstractions/NexusMods.Abstractions.MnemonicDB.Analyzers/TreeAnalyzer.cs
tests/NexusMods.DataModel.Tests/LoadoutObservableTests.cs
tests/NexusMods.DataModel.Tests/NexusMods.DataModel.Tests.csproj
tests/NexusMods.DataModel.Tests/Startup.cs

Previously the TreeAnalyzer would try to find parent entities in the database handed to it from MnemonicDB. However, if the entity was deleted as part of the transaction, the entity would be null, so the parents of the entity wouldn't be notified. This change uses the previous DB value for retracts and the current for asserts. 
Fixes #1904.

Fixes deleting of mods

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/Games/NexusMods.Games.StardewValley/StardewValleyLoadoutSynchronizer.cs

- Fixes #1924 
The issue was caused by the generation of duplicated file entries in the loadout when the new version was ingested, as the previous version was never removed.
This changes the Synchronizer logic to _update_ the LoadoutFile entries in place instead of adding new entries in Override.
This not only fixes the issue of duplicated entries (since we were not removing previous entries) but also ensures that any metadata or references that was attached to the previous LoadoutFile entry are not lost.
Replacing the entries would lose us data.
This is a change in behavior but  we don't actually have a spec for how Synchronizer should behave so and this was the best solution available. 
In the future, if we did want to instead create copies of the entries in Override or in sidecar mods, …

Fix changes to existing files not persisting after synchronize

---

Directory.Packages.props
src/Abstractions/NexusMods.Abstractions.Jobs/AJobWorker.cs
src/Abstractions/NexusMods.Abstractions.Jobs/DeterminateProgress.cs
src/Abstractions/NexusMods.Abstractions.Jobs/Percent.cs
src/Abstractions/NexusMods.Abstractions.Jobs/StreamProgressWrapper.cs
src/Networking/NexusMods.Networking.HttpDownloader/HttpDownloadJob.cs
src/Networking/NexusMods.Networking.HttpDownloader/HttpDownloadJobWorker.cs
src/Networking/NexusMods.Networking.HttpDownloader/HttpDownloaderSettings.cs
src/Networking/NexusMods.Networking.HttpDownloader/NexusMods.Networking.HttpDownloader.csproj
src/Networking/NexusMods.Networking.HttpDownloader/SimpleHttpDownloader.cs
src/NexusMods.App.UI/Controls/Spine/Buttons/Download/SpineDownloadButtonViewModel.cs
tests/Games/NexusMods.Games.TestFramework/DependencyInjectionHelper.cs
tests/Networking/NexusMods.Networking.HttpDownloader.Tests/HttpDownloadJobWorkerTests.cs
tests/Networking/NexusMods.Networking.HttpDownloader.Tests/HttpDownloaderTests.cs
tests/Networking/NexusMods.Networking.HttpDownloader.Tests/NexusMods.Networking.HttpDownloader.Tests.csproj
tests/Networking/NexusMods.Networking.HttpDownloader.Tests/Startup.cs

Resolves #1927.
Replaces the downloader with a resilient `HttpClient` that supports resuming using ranges.

Rework downloader

---

src/NexusMods.App.UI/Controls/TreeDataGrid/CustomElementFactory.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridStyles.axaml

- Fixed flat version text foreground colors and padding
- Added different styling for root and children rows

Trees root and child row styling

---

src/Abstractions/NexusMods.Abstractions.Library/ILibraryService.cs
src/Abstractions/NexusMods.Abstractions.Library/Jobs/IInstallLoadoutItemJob.cs
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/CollectionGroup.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/Extensions/LoadoutItemExtensions.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/Services.cs
src/NexusMods.App.UI/Pages/ILoadoutDataProvider.cs
src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutPage.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
src/NexusMods.Library/InstallLoadoutItemJob.cs
src/NexusMods.Library/LibraryService.cs
tests/NexusMods.CLI.Tests/VerbTests/ModManagementVerbs.cs
tests/NexusMods.DataModel.Synchronizer.Tests/GeneralLoadoutManagementTests.SynchronizerIntegrationTests.verified.md

This probably needs to wait until #1705, but the structure here is helpful for what comes after that code
* Adds the concept of collections in the loadouts
* Makes a default "My Mods" collection when a loadout is created
* All mods that are not assigned to another group will be put into the "My Mods" collection
* Adds a "group" filter to the Loadout tree view that scopes it to "My Mods" by default
This should be a unoticable change to users, but internally all mods are now in a collection and the loadout should filter out any mods that are not part of the currently selected collection. There is no way to select a collection or add a new one, but the code is there. We can merge this or #1705 first, or merge them both. Once the code is in, we can update the modesl in #1705 to include the …

Loadout support for collections

---

src/NexusMods.App.UI/Overlays/LibraryDeleteConfirmation/LibraryItemDeleteConfirmationView.axaml

This adds a missing scrollbar to the library delete confirmation dialog.
Max Dialog Size Allowed @ Steam Deck Size
(Ignore the content, just let me know if you want the max size of window smaller/bigger)
And the window of course shrinks if the content doesn't match this max size:
Tags
-----
fixes #1990

Added: Scrolling for Library Delete Confirmation Dialog

---

benchmarks/NexusMods.Benchmarks/Benchmarks/Loadouts/Harness/DummyFileStore.cs
src/Abstractions/NexusMods.Abstractions.IO/IFileStore.cs
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageViewModel.cs
src/NexusMods.DataModel/NxFileStore.cs
src/NexusMods.Library/AddLibraryFileJob.cs
tests/NexusMods.Collections.Tests/CollectionInstallTests.CanInstallBasicCollection.verified.txt

This is a fix for
- #1994
This fixes a bug where we unnecessarily back up items which may already be in the FileStore.
[Explanation Copied from Discord]
When the code for adding library items was rewritten to the new job system, someone forgot to add a check to make sure we're not packing duplicates.
[Which is a bug]
When adding an item we're only supposed to back up new files. Much of our previous code, including the GC was written under this assumption. We've broken this behaviour for adding library items; and now we've got a situation where adding mods with duplicates causes us to store compressed duplicates in separate archives on disk.
The general repro on this is:
- Install an archive for ModA
- Install an archive for ModB where some files in ModB existed in ModA
- Delete ModB
It's …

Fixed: Adding Library Files no longer Adds Duplicates

---

benchmarks/NexusMods.Benchmarks/Benchmarks/Loadouts/Harness/DummyFileStore.cs
src/Abstractions/NexusMods.Abstractions.IO/IFileStore.cs
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageViewModel.cs
src/NexusMods.DataModel/NxFileStore.cs
src/NexusMods.Library/AddLibraryFileJob.cs
tests/NexusMods.Collections.Tests/CollectionInstallTests.CanInstallBasicCollection.verified.txt

Reverts Nexus-Mods/NexusMods.App#2015
I find several parts of this to be a hack, I'll detail them below:
`bool deduplicate = true` - something that would stop the app from working if configured wrong shouldn't be a boolean flag. Components should work correctly and maintain consistency internally. If stuff breaks if there are duplicates the component should *always* deduplicate.
```
if (!await fileStore.HaveFile(hash))
await fileStore.BackupFiles([new ArchivedFileEntry(streamFactory, hash, size)], deduplicate: false);
```
Users of this component shouldn't have to constantly watch out for foot guns like this. The component should work correctly without out-of-band logic. This is also a race condition.
`ToArchive` being global to the job was intentional. That way we do all our analysis then …

Revert "Fixed: Adding Library Files no longer Adds Duplicates"

---

src/NexusMods.App.UI/Controls/TreeDataGrid/CustomElementFactory.cs

We weren't generating keys properly in our factory class, causing rows to be created but never reused. The massive performance issues in the Library were due to building up hundreds (or thousands) of rows. Each of these rows was listening to Avalonia Styling classes and causing a ton of issues throughout the app as they left their bindings and styling active. 
Big thanks to @erri120 and @Al12rs for helping me walk through this code.

Fixes for virtualization with our use of the TreeDataGrid

---

src/Networking/NexusMods.Networking.NexusWebApi/Auth/JWTToken.cs
src/Networking/NexusMods.Networking.NexusWebApi/Auth/OAuth2MessageFactory.cs
src/Networking/NexusMods.Networking.NexusWebApi/LoginManager.cs

Fixes #2031.
I'm guessing there was a concurrency issue where we set a field to a valid non-null value, and before we could access the value, something else changed the value back to a null value.
I decided to remove the cached value entirely and always get the latest from the DB, that's what our code did anyway.

Fix exception on cached value

---

src/NexusMods.App.GarbageCollection.DataModel/RunGarbageCollector.cs
src/NexusMods.App.GarbageCollection.Nx/NxRepacker.cs

This PR follows #2053 (to avoid merge conflict), please merge after #2053.
There is a minor flaw I caught in the GC code I noticed 1-2 weeks back.
Now's the right time to fix it.
Before this PR, there was technically a small amount of time,
(around 200-600 microseconds) where a power loss (or process death)
could mean leaving the App in an inconsistent state; namely:
- Archive was repacked
- Original archive was deleted
- DataStore entries were not adjusted to point at new repacked archive.
That would break the App.
Before this PR, deleting original archive was done before the DataStore entries were adjusted. Now it happens after.
Therefore, if there is power loss in that 200-600us time span, the App will not end up broken.
> [!NOTE]  
> Should that power loss occur, the old archive that …

Fixed: Edge Case Where Power Loss During GC within a (200-600 microsecond window) could break App

---

benchmarks/NexusMods.Benchmarks/Benchmarks/Loadouts/Harness/DummyFileStore.cs
src/Abstractions/NexusMods.Abstractions.IO/IFileStore.cs
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageViewModel.cs
src/NexusMods.DataModel/NxFileStore.cs
src/NexusMods.Library/AddLibraryFileJob.cs
tests/NexusMods.Collections.Tests/CollectionInstallTests.CanInstallBasicCollection.verified.txt

This is a revised version of #2015 , with the following changes:
- `AddLibraryFileJob` is left unchanged, sans adding the duplicate check.
- `IFileStore.BackupFiles` has a `remarks` section with recommended usage.
And fixed any comments related to the code changes.
Quick Notes.
It's enabled by default and opt-out.
Manually checking for duplicates and opting out has small minimal performance improvement;
so it is recommended that you do so by the remarks section. However it is not mandatory.
No change here.
Calling `BackupFiles` or `ExtractFiles` from multiple threads is safe, but may lead to duplicates.
This is a-ok as noted in the remarks section, GC will clean up duplicates after #2053
If a GC is happening, you can't update the FileStore info in DataStore or query the FileStore due to …

Fixed: Adding Mods to Library no longer Adds Duplicate Files

---

src/NexusMods.DataModel/NxFileStore.cs

This fixes the file deletion deadlock, by removing the lock inside `HaveFile` this is a one line change
But won't this cause issues? Perhaps, but the lock was mostly worthless anyways. Look at the code, we lock and say "do we have this file" because someone may want to make sure a file exists before they open it. Okay, so what if they call `HaveFile` and then before they can call `GetFileStream` the GC deletes the file? 
A good rule of thumb here is no predicate can protect against race conditions unless the predicate is itself inside a lock. All the locking code in the GC needs to be re-considered and reworked to either be lock-free or fault tollerant. 
At any rate, this solves the issue at hand and won't introduce any new bugs.

Fix the file deletion error by removing the deadlock

---

src/NexusMods.App.GarbageCollection.DataModel/RunGarbageCollector.cs
src/NexusMods.DataModel/NxFileStore.cs

Very quick patch.
Updating the DataBase's file copy of the FileStore objects interacts with external non-GC components,
such as MnemonicDB. This may cause us to yield to external code that could touch the FileStore lock.
To avoid deadlocks, we should prevent this from happening if possible. This is why we release `store.Lock()` early
and instead put another lock on the GC operation itself.
----------
Long term, we may want to update IFileStore a bit to be resilient when opening streams. For additional comments see:
https://github.com/Nexus-Mods/NexusMods.App/pull/2058#issuecomment-2359024216
In addition, we still need a non-blocking Commit in MMDB; I put the details surrounding that in the code itself.

Changed: Prevent possible FileStore Deadlocks on GC By Preventing Yielding to external code. 

---

src/Games/NexusMods.Games.AdvancedInstaller.UI/AdvancedManualInstallerUI.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/BodyView.axaml
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/BodyView.axaml.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Left/ModContent/ModContentView.axaml
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Left/ModContent/TreeEntry/ModContentTreeEntryView.axaml
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/EmptyPreview/EmptyPreviewView.axaml
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/Preview/PreviewView.axaml
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/Preview/TreeEntry/PreviewTreeEntryView.axaml
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/Preview/TreeEntry/PreviewTreeEntryView.axaml.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/SelectLocation/SelectLocationView.axaml
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/SelectLocation/SuggestedEntry/SuggestedEntryView.axaml
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/SelectLocation/TreeEntry/SelectableTreeEntryView.axaml
src/Games/NexusMods.Games.AdvancedInstaller.UI/Pages/AdvancedInstallerPages/AdvancedInstallerPageView.axaml
src/Games/NexusMods.Games.AdvancedInstaller.UI/Pages/ModUnsupportedPage/UnsupportedModPageView.axaml
src/Games/NexusMods.Games.AdvancedInstaller.UI/Pages/ModUnsupportedPage/UnsupportedModPageView.axaml.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/Resources/Language.Designer.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/Resources/Language.resx
src/NexusMods.App.UI/Controls/Trees/DiffTreeViewModel.cs
src/NexusMods.App.UI/Controls/Trees/FileTreeView.axaml
src/NexusMods.App.UI/Controls/Trees/Files/FileTreeNodeView.axaml
src/NexusMods.App.UI/Controls/Trees/Files/FileTreeNodeViewModel.cs
src/NexusMods.App.UI/Controls/Trees/Files/IFileTreeNodeViewModel.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridStyles.axaml

Styling bugs fixed:
- Expander chevrons now have hover states and correctly sized
- Compact class for `TreeDataGrid` with narrower rows
- Get Advanced Installer back in line with Figma
- Status bar on Preview Changes no longer above the tree
Advanced Installer changes really are enough to be getting on and don't exactly meet how we do the other controls (styling where it ideally shouldn't be etc.). To take this further would be too much refactoring at this time. We will come back around to advanced installer at some point.

Styling bug fixes for TreeDataGrid

---

src/NexusMods.App.UI/Pages/LibraryPage/FakeParentLibraryItemModel.cs
src/NexusMods.App.UI/Pages/LibraryPage/NexusModsModPageLibraryItemModel.cs
src/NexusMods.App.UI/Pages/LocalFileDataProvider.cs
src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs

by ensuring that even never activated items have `LibraryItems` subscription set up.
Apparently it is possible to select rows while their models are never activated, if the Library is scrolled using the Scrollbar very quickly, as some rows will be skipped from rendering.
This means it is possible to select those rows and attempt to delete them, while their models were never activated, and so their data never properly populated.
This was unexpected, as it was assumed that for an item to be selected it would at some point have to appear into view at least once.
This moves the setting up of the subscription for `LibraryItems` property into the constructor instead of inside the `WhenActivated` block.

Fix Library deletions 

---

NexusMods.App.sln
src/Abstractions/NexusMods.Abstractions.GameLocators/GameCapabilities/IModInstallDestination.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/GameCapabilities/InstallFolderTarget.cs
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/AdvancedManualInstallerUI.cs
src/Games/NexusMods.Games.Generic/Extensions/LibraryArchiveTreeExtensions.cs
src/Games/NexusMods.Games.Generic/Installers/GenericPatternMatchInstaller.cs
src/Games/NexusMods.Games.Larian/BaldursGate3/BaldursGate3.cs
src/Games/NexusMods.Games.Larian/BaldursGate3/BaldursGate3Synchronizer.cs
src/Games/NexusMods.Games.Larian/BaldursGate3/Installers/BG3SEInstaller.cs
src/Games/NexusMods.Games.Larian/BaldursGate3/RunGameTools/BG3RunGameTool.cs
src/Games/NexusMods.Games.Larian/BaldursGate3/Services.cs
src/Games/NexusMods.Games.Larian/NexusMods.Games.Larian.csproj
tests/Games/NexusMods.Games.AdvancedInstaller.Tests/ModInstallDestinationTests.cs
tests/Games/NexusMods.Games.Larian.Tests/BaldursGate3/BG3InstallerTests.CanInstallBG3Mods_testCaseName=BG3 Script Extender.verified.txt
tests/Games/NexusMods.Games.Larian.Tests/BaldursGate3/BG3InstallerTests.CanInstallBG3Mods_testCaseName=Bin Mod.verified.txt
tests/Games/NexusMods.Games.Larian.Tests/BaldursGate3/BG3InstallerTests.CanInstallBG3Mods_testCaseName=Data Mod.verified.txt
tests/Games/NexusMods.Games.Larian.Tests/BaldursGate3/BG3InstallerTests.CanInstallBG3Mods_testCaseName=Data Public Mod with nested Data folder.verified.txt
tests/Games/NexusMods.Games.Larian.Tests/BaldursGate3/BG3InstallerTests.CanInstallBG3Mods_testCaseName=Multiple Pak files Mod.verified.txt
tests/Games/NexusMods.Games.Larian.Tests/BaldursGate3/BG3InstallerTests.CanInstallBG3Mods_testCaseName=NativeMods Mod.verified.txt
tests/Games/NexusMods.Games.Larian.Tests/BaldursGate3/BG3InstallerTests.CanInstallBG3Mods_testCaseName=Nested Pak Mod.verified.txt
tests/Games/NexusMods.Games.Larian.Tests/BaldursGate3/BG3InstallerTests.CanInstallBG3Mods_testCaseName=Simple Pak Mod.verified.txt
tests/Games/NexusMods.Games.Larian.Tests/BaldursGate3/BG3InstallerTests.cs
tests/Games/NexusMods.Games.Larian.Tests/NexusMods.Games.Larian.Tests.csproj
tests/Games/NexusMods.Games.Larian.Tests/Startup.cs

Part of #1262 
This adds support for the following types of mods:
- BG3 Script Extender
- Pak mods
- Loose files Data mods
- NativeMods loader
- NativeMods `dll` mods
I tried covering most cases, like multiple pak files, loose files with nested Data folders and checked a bunch of mods.
Also added tests to verify the correct installation of all the supported mod types.

Add support for installing BG3 mods

---

src/NexusMods.App.UI/Pages/LoadoutPage/FakeParentLoadoutItemModel.cs
src/NexusMods.App.UI/Pages/LocalFileDataProvider.cs
src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs

When scrolling very fast, it is possible to reach the bottom of a long loadout list and select all items without some items being activated and thus properly populated. 
This makes sure the needed data is populated to prevent issues with mass deletion or other operations.

Fix data not being initialized for some rows in LoadoutView when fast scrolling through

---

src/Games/NexusMods.Games.StardewValley/Diagnostics.cs
src/Games/NexusMods.Games.StardewValley/Emitters/ModOverwritesGameFilesEmitter.cs

This health check was being being emitted for every overwriting file.
The PR only emits one health check for each mod (itemGroup).
- deduped on mod
- fixed exception when trying to open details, due to incorrect markdown placeholder (mod -> groupName)

Fix StardewValley "Mod x overwrites game files" health check spam

---

src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardView.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionCards/CollectionCardStyles.axaml

Fixes layout and FlexPanel usage to better handle changes in description size and author name.
There will likely be more fixes needed. It seems that the starting layout taken from figma didn't really cover these cases well

Collection Cards layout fixes

---

Directory.Packages.props
src/Abstractions/NexusMods.Abstractions.GameLocators/GameLocatorResult.cs
src/Abstractions/NexusMods.Abstractions.Games/AGame.cs
src/NexusMods.StandardGameLocators/AGameLocator.cs
src/NexusMods.StandardGameLocators/HeroicGogLocator.cs
src/NexusMods.StandardGameLocators/ManuallyAddedLocator.cs
src/NexusMods.StandardGameLocators/NexusMods.StandardGameLocators.csproj
src/NexusMods.StandardGameLocators/Services.cs
src/NexusMods.StandardGameLocators/SteamLocator.cs
tests/NexusMods.StandardGameLocators.TestHelpers/UniversalStubbedGameLocator.cs

Fixes #2107.
There's an issue in GameFinder I found that I need to fix, but that doesn't require any changes in this code besides a version bump.

Use mapped filesystem

---

src/NexusMods.App/Commandline/CleanupVerbs.cs

This PR makes a slight improvement to the uninstall experience.
1. Disables GC when unmanaging game during uninstall, as it's not needed, since the uninstaller will wipe the archives anyway.
2. Deletes the `Downloads` folder during the uninstall procedure.
Currently trying to reproduce the uninstall issue, I cannot either on Linux or Windows at the moment. So this PR should also serve me CI builds to get installer.

Improved: Uninstall Experience

---

src/NexusMods.App/Commandline/CleanupVerbs.cs
src/NexusMods.DataModel/DataModelSettings.cs

Very tiny patch.
Up until now, the uninstaller has been focusing on all locations defined within the App's config files; this is because it has historically been possible to re-route these to different locations on disk via various config knobs.
However, that leaves the base NMA folder stranded on the FileSystem, which means that users will get an unwanted prompt on re-install:
This PR adds the 'Local Application Data' directory as one of the targets to wipe, ensuring no folders are left behind.
Uninstall on Windows now works if the path to the Application folder has spaces in it.
The path to the PowerShell script wasn't escaped properly, PS has rules for nested escapes, and that wasn't being handled properly.
See deleted lines. We used to have a concurrency bug with `IRepository`, but …

Improved: Additional Set of Uninstaller Improvements

---

src/NexusMods.App.UI/WorkspaceSystem/NewTabPage/NewTabPageView.axaml

Make New Tab Page scrollable

---

src/NexusMods.App.UI/LeftMenu/Items/ApplyControlView.axaml

Closes #2123 
Just a foreground mismatch.
Another issue with the style-inheritance, like seen on #1822 i think

Corrected tooltip foreground

---

src/Abstractions/NexusMods.Abstractions.MnemonicDB.Attributes/Extensions/EntityExtensions.cs
src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridAdapter.cs
src/NexusMods.App.UI/Pages/LibraryPage/FakeParentLibraryItemModel.cs
src/NexusMods.App.UI/Pages/LibraryPage/LibraryItemModel.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
src/NexusMods.Collections/NexusMods.Collections.csproj

The install/installed status of a row is dependent on the number of connect loadout items. `ObserveCountChanged()` does not notify of the current count on a subscription (by default). So when a row was re-activated the installed status of the row defaulted to the status when it was last seen on screen, and would only update if the status changed again in the future. This PR adds `notifyCurrentCount:true` to these invocations to fix this problem. 
Also updates `GetCreatedAt` so it no longer crashes Rx chains during deletion of entities. 
fixes: #2141 and #2140

Fix off-screen row updates in the Library

---

src/Abstractions/NexusMods.Abstractions.GameLocators/FNV1aHash.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/LocationId.cs
src/Abstractions/NexusMods.Abstractions.MnemonicDB.Attributes/GamePathAttribute.cs
src/Abstractions/NexusMods.Abstractions.MnemonicDB.Attributes/GamePathParentAttribute.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/Preview/TreeEntry/PreviewTreeEntryViewModel.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/SelectLocation/SuggestedEntry/SuggestedEntryViewModel.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/SelectLocation/TreeEntry/SelectableTreeEntryViewModel.cs
src/NexusMods.DataModel/JsonConverters/GamePathConverter.cs

A longstanding problem with efficiency with `LocationId`, is that internally it stores the location as a string (not even interned incidentally). With MnemonicDB this is even worse as we store GamePaths as tuples, which results in the stored value being a composite value of two variable sized strings. We can clean all this up fairly simply, and that's what this patch does:
* Stores LocationId now as a ushort
* The ushort is calculated via a FNV1a (32bit) hash with the upper and lower halves combined with an XOR
* When a string is converted to a LocationId we hash it, then make sure it doesn't collide with existing values
* Performance of creating LocationIds from strings will be slightly slower with this method but the most performance critical parts of the code use `ushorts` and not …

Switch LocationId (and GamePaths) over to an ushort instead of a string

---

Directory.Packages.props
src/Abstractions/NexusMods.Abstractions.FileStore/Downloads/DownloadAnalysis.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/Files/Metadata.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/Loadout.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/Mods/Mod.cs
src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/CollectionTag.cs
src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionMetadata.cs
src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionRevisionMetadata.cs
src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionRevisionModFile.cs
src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Models/User.cs
src/Networking/NexusMods.Networking.NexusWebApi/LoginManager.cs
src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.cs
src/NexusMods.Collections/InstallCollectionJob.cs
src/NexusMods.DataModel/CommandLine/Verbs/ImportExport.cs
src/NexusMods.DataModel/Services.cs

Updates MnemonicDB to the latest version (fixes the UTF8 decode error), also adds an `Export` CLI method for exporting the MnemonicDB database to a file so that we can use the data for testing in MnemonicDB

Small fixes and Export CLI method

---

src/Abstractions/NexusMods.Abstractions.NexusWebApi/ILoginManager.cs
src/Networking/NexusMods.Networking.NexusWebApi/LoginManager.cs
src/Networking/NexusMods.Networking.NexusWebApi/Services.cs
src/NexusMods.App/TelemetryProvider.cs

The code used to trigger the observables in `ILoginManager` every time the token was used in an API call. This meant that we were downloading the avatar for every API call...

Fix login observables triggering on every API call

---

src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs

fixes #2028
Decrements the badge number when a library item is deleted.
I'll keep:
- https://github.com/Nexus-Mods/NexusMods.App/issues/2016#issue-2521093393
Open, we should auto clear if library is already open; so I'll do that next.

Fixed: Loadout Left Menu Badge Not Decrementing on Library Item Delete

---

src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/EmptyState/EmptyStateStyles.axaml

fixes #2159 (good enough to consider it a 'fix' for now)
fixes #2160 (adds missing hyperlink)
For the shrinking issue, the following margin is reduced:
Currently shrinking the window does this:
With the PR it is shrunk down to `16` (from `128`):
The contents remain centered, 1:1 with before if not shrunk.
The movement of the title and link is still inconsistent, however that's due to an unrelated reason; the hyperlink is actually a button, and unlike the text, the button has a minimum size, and thus can't wrap around edges. Will leave to @insomnious to pick that one up since they volunteered.
Already got the thumbs up from @captainsandypants on Slack.

Improved: Empty State View

---

src/NexusMods.App.UI/Controls/MarkdownRenderer/MarkdownRendererDesignViewModel.cs
src/NexusMods.App.UI/Controls/MarkdownRenderer/MarkdownRendererView.axaml
src/NexusMods.App.UI/Pages/Changelog/ChangelogPageViewModel.cs
src/NexusMods.App.UI/Pages/Diagnostics/Details/DiagnosticDetailsView.axaml

Fixes #2134
Fixed markdown styles and better documented how to tweak them
Changed parsing to match new changelog specs (won't work until #2176 is merged)
Left some placeholder `Style` selectors for completeness and for if we need to go back

Updated markdown styles

---

src/NexusMods.App.UI/Controls/Alerts/Alert.axaml.cs

This hides the whole block (fixing any layout spacing weirdness) if no actual text to render

Fix for Alert Body being rendered incorrectly if only containing whitespace

---

Directory.Packages.props

This PR updates to the latest MnemonicDB release which fixes 2 major issues in the app: 
1) General performance - the `GlobalCompare` method in MnemonicDB was performing 2 allocations on every compare. This was having a massive impact on everything from reads to writes. This issue has been resolved
2) Timestamp regression - we were storing transaction timestamps incorrectly, resulting in the `400 years from now` bug in the UI
Resolves #2211, #2207

Fix two bugs found in testing

---

src/NexusMods.DataModel/ChunkedStreams/ChunkedStream.cs

After installing a SDV collection we were getting a lot of "Manfifest parse errors". This was due to our ChunkedStreamReader improperly terminating streams it reads in the sync code. This fixes that bug (copies the logic from the async version) which removes the parse errors.

Fix SDV Manifest parse error

---

src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/GraphQLResolver.cs
src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionRevisionMetadata.cs
src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Models/User.cs
src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/NexusModsCollectionLibraryFile.cs
src/Networking/NexusMods.Networking.NexusWebApi/Extensions/FragmentExtensions.cs
src/Networking/NexusMods.Networking.NexusWebApi/NexusMods.Networking.NexusWebApi.csproj
src/Networking/NexusMods.Networking.NexusWebApi/NexusModsCollectionDownloadJob.cs
src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.Collections.cs
src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.cs
src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs
tests/Networking/NexusMods.Networking.NexusWebApi.Tests/NexusModsLibraryTests.cs

Most of the changes are just code cleanup and moving code from one place to another to make it easier to update later.
The most important change is the ordering. Previously, we'd get the metadata from the API before we even download the collection file. Now, we first download the file and then get the metadata from the API.
This PR is just a stepping stone that hopefully doesn't break anything, the next PR will use this as a base and re-do how we store metadata for collection files.

Restructure collection metadata creation

---

tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.cs
tests/NexusMods.DataModel.SchemaVersions.Tests/SchemaFailsafes.cs
tests/NexusMods.DataModel.SchemaVersions.Tests/Startup.cs

Based on checking if the file is a ZIP file instead of a known string (that maybe could run afoul of newline/encoding issues?) same sort of thing as #2239

Add a sanity check to the legacy database sanity checks

---

src/NexusMods.App/Program.cs

Fixes an issue where running the CLI causes an exception because our "slim-client" used for NXM protocol invocations doesn't have the data model registered.

Don't migrate on the CLI

---

src/Games/NexusMods.Games.Larian/BaldursGate3/BaldursGate3.cs

It was pulling the version info from the LariLauncher rather than the game exe, since the launcher is now the primary file.

Fix BG3 incorrect version on MyGames page

---

src/NexusMods.App.UI/Overlays/AOverlayViewModel.cs
src/NexusMods.App.UI/Overlays/Login/StartupMessageBox/LoginMessageBoxViewModel.cs
src/NexusMods.DataModel/Settings/MnemonicDBSettingsBackend.cs

Still not totally sure what's going on here, but this solution is cleaner. The end result is that we move the `Update` on the "HasShownModal" into the `Close` handler of the modal. All the other modals do it this way, and it's something to do with setting this value during startup (which gets called from the constructor of the main window) that is causing this issue. 
Clean enough of a fix for the release.
Also makes the MnemonicDB settings manager async vs sync.

Fix the login twice bug

---

src/Abstractions/NexusMods.Abstractions.Loadouts/Models/LoadoutItem.cs
src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Diagnostics/BannerlordDiagnosticEmitter.cs

fixes #2295
- https://github.com/Nexus-Mods/NexusMods.App/issues/2295

Fixed: Skip Diagnostics on Disabled Mods in Bannerlord

---

src/NexusMods.App.UI/Controls/Alerts/Alert.axaml.cs
src/NexusMods.App.UI/Controls/Alerts/AlertSettingsWrapper.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/ILoadOrderViewModel.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderView.axaml
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderView.axaml.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderViewDesignViewModel.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderViewModel.cs
src/NexusMods.App.UI/Pages/Sorting/SortingSelection/SortingSelectionDesignViewModel.cs
src/NexusMods.App.UI/Pages/Sorting/SortingSelection/SortingSelectionViewModel.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Resources/ControlThemes/AlertControlTheme.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/CheckBox/CheckBoxStyles.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/ComboBox/ComboBoxStyles.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TabControl/TabControlStyles.axaml

Part of #2277 
- Styling tweaks and fixes for ComboBox and CheckBox
- Alert hide and show

Load Order Styling - Part 3

---

src/NexusMods.App/TelemetryProvider.cs

Fix mod counting

---

docs/developers/development-guidelines/UIStylingGuidelines.md

And how to style `TreeDataGrid` rows contents in general.
Method is based on:
- defining `ContentTemplates` as resources with `x:DataType` attribute set to the item model type.
- Set Classes in the content template using the `Classes.MyClass="{CompiledBinding .MyModelBoolProperty}"` syntax.
- Apply the `ContentTemplate` to the row using a style
- Use the set classes in the selector
- Profit

Add Docs on method to apply style classes to `TreeDataGridRows`

---

src/NexusMods.App.UI/Pages/ItemContentsFileTree/ItemContentsFileTreeView.axaml
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/ILoadOrderViewModel.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderView.axaml
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderViewDesignViewModel.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderViewModel.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridStyles.axaml

Part of https://github.com/Nexus-Mods/NexusMods.App/issues/2277
Fake button to cover the header for the first column to use existing sort functions instead of using the combo box.

Load order header button

---

src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionDownload.cs
src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionDownloadBundled.cs
src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionMetadata.cs
src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/NexusModsFileMetadata.cs
src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Services.cs
src/Abstractions/NexusMods.Abstractions.NexusWebApi/IGameDomainToGameIdMappingCache.cs
src/Abstractions/NexusMods.Abstractions.Telemetry/NexusModsURLBuilder.cs
src/Networking/NexusMods.Networking.NexusWebApi/GraphQL/CollectionRevisionInfo.graphql
src/Networking/NexusMods.Networking.NexusWebApi/LoginManager.cs
src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.Collections.cs
src/Networking/NexusMods.Networking.NexusWebApi/V1Interop/GameDomainToGameIdMappingCache.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadDesignViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadPage.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDownload/ICollectionDownloadViewModel.cs
src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardViewModel.cs
src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionsPage.cs
src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionsViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutItemModel.cs
src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
src/NexusMods.App/TelemetryProvider.cs
src/NexusMods.Collections/CollectionDownloader.cs
src/NexusMods.Collections/InstallCollectionJob.cs
src/NexusMods.Collections/Verbs.cs
tests/NexusMods.Collections.Tests/CollectionInstallTests.cs
tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=SDV.4_11_2024.rocksdb.zip.verified.txt
tests/NexusMods.DataModel.SchemaVersions.Tests/Schema.verified.md

Part of #2254.
If you want to test this, you can't use collections that you've added previously. You must delete old collections and re-add them.
- Reworks how collections are installed.
- Fixes exceptions related to dates
- Filters collections by game
- Delete collections (doesn't remove the library items, it just removes the entities)
- Visit collections on Nexus Mods

Rework installing a collection

---

src/Games/NexusMods.Games.Generic/GameToolRunner.cs
src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Diagnostics/MissingProtontricksEmitter.cs
src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/Emitters/MissingProtontricksForRedModEmitter.cs
src/NexusMods.CrossPlatform/NexusMods.CrossPlatform.csproj
src/NexusMods.CrossPlatform/Process/AggregateExecutableRuntimeDependency.cs
src/NexusMods.CrossPlatform/Process/AggregateProtontricksDependency.cs
src/NexusMods.CrossPlatform/Process/IProtontricksDependency.cs
src/NexusMods.CrossPlatform/Process/ProtontricksFlatpakDependency.cs
src/NexusMods.CrossPlatform/Process/ProtontricksNativeDependency.cs
src/NexusMods.CrossPlatform/Services.cs
tests/NexusMods.CrossPlatform.Tests/AggregateExecutableRuntimeDependencyTests.cs
tests/NexusMods.CrossPlatform.Tests/ProtontricksTests.cs

This PR adds the following:
- An `AggregateExecutableRuntimeDependency`.
- This allows us to represent multiple of `ExecutableRuntimeDependency` as a simple runtime dependency.
- Practical usages include:
- Multiplexing (e.g. Flatpak & Native) as part of single dependency.
- Per-OS dependencies (e.g. Run separate command on Linux and OSX).
- `AggregateProtontricksDependency`, which executes on either `Flatpak protontricks` or `Native protontricks`, depending on which is available.
-------
Remarks: 
If the user's has custom library directories, they may need to run `flatpak override --user --filesystem=host com.github.Matoking.protontricks` (or similar) to give flatpak's version of `protontricks` access to alternate directories.

Added: Support for running Protontricks via Flatpak (and extra)

---

src/NexusMods.App.UI/Controls/Alerts/Alert.axaml.cs

Fixes https://github.com/Nexus-Mods/NexusMods.App/issues/2326
Better matches an Avalonia native control and provides ability to now bind Body and Text properties
`UpdateSeverity()` is there for completeness to update visuals and in case we need to use it elsewhere in the control. 
Basic premise is that both changing the property and when the template updates, both update the actual TextBlock where the text is displayed

Support bindings in Alert component

---

src/Abstractions/NexusMods.Abstractions.Collections/NexusCollectionLoadoutGroup.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
src/NexusMods.Collections/CollectionDownloader.cs
src/NexusMods.Collections/InstallCollectionJob.cs
src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs
tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=SDV.4_11_2024.rocksdb.zip.verified.txt
tests/NexusMods.DataModel.SchemaVersions.Tests/Schema.verified.md

- Install button will be disabled if you haven't downloaded all required mods or have already installed the collection
- Download button will be disabled if you have downloaded everything already or if you aren't premium
Part of #2254.

Better state checks for collections

---

src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionDownload.cs
src/Games/NexusMods.Games.StardewValley/Emitters/DependencyDiagnosticEmitter.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadDesignViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDownload/ICollectionDownloadViewModel.cs
src/NexusMods.Collections/CollectionDownloader.cs
src/NexusMods.Collections/Verbs.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionDownloadPage/CollectionDownloadPageStyles.axaml
tests/NexusMods.Collections.Tests/CollectionInstallTests.cs

Part of #2254. UI styling needs updating.

Move toolbar into tabs

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs

This allows for some control and predictability of the app while we don't have a proper conflict resolution system.

Temporarily resolve conflicts by newest installed wins

---

src/Abstractions/NexusMods.Abstractions.Collections/Json/ModSource.cs
src/Abstractions/NexusMods.Abstractions.Collections/Json/ModSourceType.cs
src/Abstractions/NexusMods.Abstractions.Collections/Json/UpdatePolicy.cs
src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.Collections.cs
src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadDesignViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDownload/ICollectionDownloadViewModel.cs
src/NexusMods.App.UI/Pages/ItemContentsFileTree/ItemContentsFileTreeViewModel.cs
src/NexusMods.App.UI/Pages/TextEdit/TextEditorPage.cs
src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageViewModel.cs
src/NexusMods.Collections/CollectionDownloader.cs
src/NexusMods.Collections/InstallCollectionJob.cs

Adds a menu item to open the collection JSON file in a text editor (read-only). Allows us to better debug collection issues.
Part of #2254.
Also documents and adds some more JSON properties.

Open collection JSON file in text editor

---

src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Diagnostics/Diagnostics.cs

Removing fields from health check `Title` as they are no longer needed now that `Summary` can be displayed in health check entries

Remove fields from bannerlord health check titles

---

src/NexusMods.SingleProcess/CliServer.cs

Should fix an infinite while loop in the `CliServer` that can happen when it gets disposed.

Prevent infinite while loop

---

Directory.Packages.props
src/Abstractions/NexusMods.Abstractions.Collections/Json/ModSourceType.cs
src/Networking/NexusMods.Networking.NexusWebApi/LoginManager.cs
tests/NexusMods.Collections.Tests/CollectionInstallTests.cs
tests/NexusMods.StandardGameLocators.TestHelpers/Services.cs

Updates Game Finder and MS test deps. Also fixes the following broken behavior on `main`
* The ModType used capital letters for the enum of `Browse` and `Direct` meaning that those collections were not parsable. This fixes that behavior. We really need to be running all the unit tests more often. 
* The LoginManager was borked, using a `CachedObject` but not changing `UserInfo` to point to this new cache, so depending on how logins were performed half the login manager wouldn't see the data. Also would have been caught by running the tests.

Upgrade deps, fix several broken tests on `main`

---

docs/users/SystemRequirements.md
src/NexusMods.App/com.nexusmods.app.metainfo.xml

just adding the missing dependency mentioned in #2419 and updating the url for faqs in the app metainfo xml. I *think* that was the source of the CI failure for build appimage in some of the more recent PRs.

doc and ci fix

---

src/NexusMods.Telemetry/EventDefinition.cs
src/NexusMods.Telemetry/EventMetadata.cs
src/NexusMods.Telemetry/EventSender.cs
tests/NexusMods.Telemetry.Tests/EventSenderTests.cs

Forgot to URL encode event names and values.

Fix URL encoding for events

---

src/NexusMods.App.UI/Controls/Spine/SpineViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/IWorkspaceController.cs
src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/WorkspaceController.cs

- Part of #2433 
Going through the Left Menu code I noticed that Left Menus and the entire workspaces were being leaked.
The cleanup code was simply never implemented after we added support for deleting loadouts.
This also has a couple of other changes:
- Fix workspaces not getting deleted when loadouts are removed
- Use SortAndBind when practical rather than Sort to avoid obsolete warning
- Store left menus in dictionary rather than ReadOnlyObservableCollection

Fix leaking workspaces and some code cleanup

---

src/Abstractions/NexusMods.Abstractions.NexusWebApi/DTOs/OAuth/JwtTokenReply.cs
src/Networking/NexusMods.Networking.NexusWebApi/Auth/JWTToken.cs

fixes #2442
I tested this on both Windows and Linux; should be fine.
Normally something like this you'd unit test with a DateTimeProvider, and mock that; however, time for test build is now, not later.

Fixed: Token Expiry Date Not using UTC Time

---

Directory.Packages.props
src/Abstractions/NexusMods.Abstractions.Cli/RendererExtensions.cs
src/Networking/NexusMods.Networking.NexusWebApi/NexusApiVerbs.cs
src/NexusMods.App.Cli/OptionParsers/LoadoutParser.cs
src/NexusMods.App.Cli/OptionParsers/MatcherParser.cs
src/NexusMods.App.Cli/Services.cs
src/NexusMods.App/ConsoleHelper.cs
src/NexusMods.App/NexusMods.App.csproj
src/NexusMods.App/Program.cs
src/NexusMods.DataModel/CommandLine/Verbs/LoadoutManagementVerbs.cs
src/NexusMods.DataModel/NexusMods.DataModel.csproj
src/NexusMods.Library/AddLibraryFileJob.cs
src/NexusMods.ProxyConsole.Abstractions/VerbDefinitions/ModuleDefinition.cs
src/NexusMods.ProxyConsole.Abstractions/VerbDefinitions/OptionAttribute.cs
src/NexusMods.ProxyConsole.Abstractions/VerbDefinitions/OptionDefinition.cs
src/NexusMods.ProxyConsole.Abstractions/VerbDefinitions/ServiceExtensions.cs
src/NexusMods.ProxyConsole.Abstractions/VerbDefinitions/VerbAttribute.cs
src/NexusMods.ProxyConsole.Abstractions/VerbDefinitions/VerbDefinition.cs
src/NexusMods.SingleProcess/CommandHandler.cs
src/NexusMods.SingleProcess/CommandLineConfigurator.cs
tests/NexusMods.CLI.Tests/VerbTests/AVerbTest.cs
tests/NexusMods.CLI.Tests/VerbTests/ModManagementVerbs.cs

This PR does the following
* Fixes consoles on Windows
* When compiling with WinExe the console isn't connected
* When compiling with Exe we always get a console, even when running in UI mode
* This is a windows issue. Fixed by compiling with WinExe mode and doing some P/Invoke magic to attach any existing consoles
* Changes up the Proxy Console code a bit so we can create paths of modules for verbs instead of prefixing verbs. For example instead of `nexus-login` we can have `nexus login`, `nexus verify` etc. This is opt-in and we can convert verbs over as time goes on. 
* Modules (verb prefixes) can have doc strings so we can do `nexus --help` to find out what console commands are available in that module
* Verb options can now be optional
* Verb options that are not optional are now …

Cli fixes and escape hatches

---

NexusMods.App.sln
src/Abstractions/NexusMods.Abstractions.Logging/IObservableExceptionSource.cs
src/Abstractions/NexusMods.Abstractions.Logging/LogMessage.cs
src/Abstractions/NexusMods.Abstractions.Logging/NexusMods.Abstractions.Logging.csproj
src/NexusMods.App.UI/LeftMenu/Items/ApplyControl/ApplyControlViewModel.cs
src/NexusMods.App.UI/LeftMenu/Items/ApplyControl/LaunchButtonViewModel.cs
src/NexusMods.App.UI/NexusMods.App.UI.csproj
src/NexusMods.App.UI/Overlays/Generic/MessageBox/Ok/IMessageBoxOkViewModel.cs
src/NexusMods.App.UI/Overlays/Generic/MessageBox/Ok/MessageBoxOkView.axaml
src/NexusMods.App.UI/Overlays/Generic/MessageBox/Ok/MessageBoxOkView.axaml.cs
src/NexusMods.App.UI/Overlays/Generic/MessageBox/Ok/MessageBoxOkViewModel.cs
src/NexusMods.App.UI/Windows/MainWindowViewModel.cs
src/NexusMods.App/NexusMods.App.csproj
src/NexusMods.App/ObservableLoggingTarget.cs
src/NexusMods.App/Program.cs

This PR makes the following changes: 
* Updates the OK Message box to accept an optional markdown renderer that can be used for "supporting documentation"
* Moved around a few of the parameters in the existing uses of this overlay to allow for the markdown VM to be pulled in.
* Adds a new logging target in `NexusMods.App/Program.cs` that logs to a implementation of `NexusMods.Abstractions.Logging.IObservableExceptionSource`
* MainWindowViewModel wires the IObservableExceptionSource up to the Message Box Ok dialog when exceptions come through. 
No exception spamming on my install so far. A few that we likely need to look at, like observable `null reference exceptions` and a json parse exception on loading the window settings. Overall I think this is good for pointing out where we have …

Basic exception overlay

---

src/NexusMods.App.UI/HighPerformanceLogging.cs
src/NexusMods.App/LogMessages.cs
src/NexusMods.App/Program.cs
src/NexusMods.App/Startup.cs

- Changes `Finding View for {viewModel}` from `Debug` to `Trace`
- Adds filter for `Avalonia.ReactiveUI` and a min level of `Warning`
- Logs unhandled exceptions in R3

Better log filters

---

src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Expander/ExpanderStyles.axaml

Added ScrollViewer for whole page as per @captainsandypants request. Added bottom border to expanders to visually separate when both are collapsed.

Fixes lack of Library scrolling

---

src/NexusMods.App.UI/LeftMenu/Items/ILeftMenuItemViewModel.cs
src/NexusMods.App.UI/LeftMenu/Items/LeftMenuItemDesignViewModel.cs
src/NexusMods.App.UI/LeftMenu/Items/LeftMenuItemView.axaml.cs
src/NexusMods.App.UI/LeftMenu/Items/LeftMenuItemViewModel.cs
src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuView.axaml
src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs

Should be final PR for Left Menu rework:
- Closes #2433 
Reorganized the ToolTips to use an optional StringComponent and fallback on Text if not set.

Use StringComponent for Left Menu Item ToolTips

---

Directory.Packages.props

Fixes some of the issues with installing collections with lots of mods. Exposes other performance issues with the creation of the `SyncTree` those will need to be fixed in another patch. 
This PR goes into more detail about the changes on the MnemonicDB side: https://github.com/Nexus-Mods/NexusMods.MnemonicDB/pull/117

Update to the new MnemonicDB

---

src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuView.axaml.cs

- part of #2433 
Following request from Design to only show the 'All' loadout left menu entry if there are multiple collections.

Hide Loadout "All" left menu entry if there is only the default collection

---

src/NexusMods.App.UI/Pages/TreeDataGridSharedResources.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/SharedStyles.axaml

Added placeholder elements back to TreeDataGrid thumbnails so something is shown when an image is null or transparent and not just empty space.

Re-added placeholder for mod thumbnails

---

src/Networking/NexusMods.Networking.NexusWebApi/GraphQL/CollectionRevisionNumbers.graphql
src/Networking/NexusMods.Networking.NexusWebApi/NexusMods.Networking.NexusWebApi.csproj
src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.Collections.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadDesignViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDownload/ICollectionDownloadViewModel.cs
src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs

- can delete individual revisions
- can fetch all or newer revision numbers
- library displays revisions instead of first revision of collections
Part of #391.

Preperations for collection updates

---

src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.Collections.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadDesignViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDownload/ICollectionDownloadViewModel.cs
src/NexusMods.Collections/CollectionDownloader.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionDownloadPage/CollectionDownloadPageStyles.axaml

Part of #391.
Fetches all revisions for a collection and shows the newest revision in the UI. Also adds a "Install Update" button that adds the newest revision to the app and navigates to the collection download page for that revision.
Nothing yet for dealing with the old revision.

Show and add newest revision to the app

---

tests/Games/NexusMods.Games.StardewValley.Tests/StardewValleyInstallersTests.CanInstallMod_filename=Portraits_for_Vendors.zip.verified.txt
tests/Games/NexusMods.Games.StardewValley.Tests/StardewValleyInstallersTests.cs

- Fixes #2532 
by ensuring the sorting of items is consistent
Before it was sorting just by file name, now it is sorting by the entire relative path.
There were files with the same filename, but inside different folders that could end up in different positions

Fix SDV installer flaky test 

---

src/NexusMods.Media/ImageDecoder.cs
src/NexusMods.Media/ImageEncoder.cs

There were two issues:
1) The transposing step was completely skipped as we always used the
pixels of the input bitmap. This is what resulted in the channels
being swapped, as the input bitmap was BGRA instead of RGBA.
2) The SRGB Linear color space was used even though we encode images
using the normal SRGB color space. This resulted in colors that were
noticeably off.

Fix blue thumbnails

---

src/Games/NexusMods.Games.StardewValley/Emitters/Helpers.cs
src/NexusMods.DataModel/Diagnostics/DiagnosticManager.cs

- fixes #2525 
I thought health checks weren't updating on collection enabled state changes, but they weren't updating at all.
Don't know how that went by for so long. I think it happened because we are no longer updating the Revision attribute on Loadouts when child items were edited or something.
Also fixed enabled state of ancestors not being considered during SDV health checks.

Fix health checks not refreshing on loaodut changes

---

src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridAdapter.cs
src/NexusMods.App.UI/Pages/LibraryPage/NexusModsModPageLibraryItemModel.cs

- Fixes #2529 
This `DisposeMany` seems to wreak havoc on items that are still in view or similar. I don't know if it is necessary to replace this with a different mechanism for disposing the items, but I think it should happen higher level to avoid items getting disposed before they are fully removed from view and other collections.

Fix `ApplyChanges` exceptions in the library/loadout

---

src/Abstractions/NexusMods.Abstractions.Loadouts/ISynchronizerService.cs
src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs

- Fixes #2563
Fix incorrect LastApplied states being returned due to long diff operation returning out of order.
Using R3 we can ensure that the async operations are executed sequentially, and longer operations don't override later results.

Fix Active loadout state bug

---

src/Networking/NexusMods.Networking.HttpDownloader/HttpDownloadJob.cs
src/Networking/NexusMods.Networking.NexusWebApi/NexusModsDownloadJob.cs

Resolves #2568.
At some point we want to put these values into settings...
It should be noted that the Polly Retry policy doesn't retry when `TaskCanceledException` is thrown from the HTTP client.

Increases HTTP client timeouts

---

src/Networking/NexusMods.Networking.NexusWebApi/NexusApiClient.cs
src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.cs
src/Networking/NexusMods.Networking.NexusWebApi/RunUpdateCheck.cs

So that we get more meaningful errors when request fails than null ref exception
- related to #2569

Add EnsureNoError to GraphQL calls

---

src/Abstractions/NexusMods.Abstractions.Collections/Json/CollectionInfo.cs
src/Abstractions/NexusMods.Abstractions.UI/ReactiveR3Object.cs
src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.Collections.cs
src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridAdapter.cs
src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridViewHelper.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadDesignViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDownload/ICollectionDownloadViewModel.cs

Adds the instruction tab to the collections download page without styling. The tab currently only shows collection instructions.
Resolves #2341.
Also fixes a bug when the entire TreeDataGrid gets detached from the visual tree.

Add instructions tab

---

src/Abstractions/NexusMods.Abstractions.Games/RunGameTool.cs

Demoted the log message about exit code to a warning since it games often return whatever, e.g. SDV always returns -1.
Showing an error dialog each time you close the game isn't great experience.

Fix error dialog when closing SDV

---

src/NexusMods.App.UI/Controls/TreeDataGrid/AValueComponent.cs
src/NexusMods.App.UI/Controls/TreeDataGrid/CompositeItemModel.cs
src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridAdapter.cs
src/NexusMods.App.UI/Extensions/EnumerableExtensions.cs
src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
src/NexusMods.App.UI/Pages/Downloads/ViewModels/DownloadTaskViewModel.cs
src/NexusMods.App.UI/Pages/ILibraryDataProvider.cs
src/NexusMods.App.UI/Pages/ILoadoutDataProvider.cs
src/NexusMods.App.UI/Pages/LibraryPage/LibraryComponents.cs
src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutComponents.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
src/NexusMods.DataModel/Diagnostics/DiagnosticManager.cs

- Depends on #2584 
- Fixed Loadout View multi-selection operations not working correctly (same dispose issue we fixed in the library)
- Fixed CanExecute command observables not executing on UI thread
- Rearranged a bunch of OnUI to decrease unnecessary operations happening on UI thread

Loadout and Library fixes

---

Directory.Packages.props

Tested changes locally.
TreeDataGrid actually seems faster, but still has the bug of the columns collapsing when using star size for the first column.

Bump Avalonia versions

---

src/NexusMods.App.UI/Controls/LoadoutBadge/LoadoutBadgeViewModel.cs

It wasn't showing if the loadout was the last applied one, but had changes to synchronize

Fix active loadout indicator on Loadout badge

---

src/NexusMods.App.UI/Pages/ObservableInfo/ObservableInfoPage.cs
src/NexusMods.App.UI/Pages/ObservableInfo/ObservableInfoPageView.axaml
src/NexusMods.App.UI/Pages/ObservableInfo/ObservableInfoPageView.axaml.cs
src/NexusMods.App.UI/Pages/ObservableInfo/ObservableInfoPageViewModel.cs
src/NexusMods.App.UI/Services.cs
src/NexusMods.App.UI/TypeFinder.cs

For devs only. The page taps into the R3 observable tracker system and allows us to visualize all active observables.

Add observable tracker page

---

src/NexusMods.App.UI/Pages/ILoadoutDataProvider.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutComponents.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutPage/TreeDataGridLoadoutResources.axaml
src/NexusMods.App.UI/Pages/LocalFileDataProvider.cs
src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs

Part of #2598.
- Adds the "Collections"-column for loadout items
- Adds the `IsLocked` state to `LoadoutComponents.IsEnabled`
- Adds a new component for the disabled state of the parent collection
I'll do the more difficult state stuff in another PR.

Updated states for loadout items

---

src/Abstractions/NexusMods.Abstractions.Games/AGame.cs
src/Games/NexusMods.Games.Larian/BaldursGate3/BaldursGate3.cs
src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Bannerlord.cs
src/Games/NexusMods.Games.StardewValley/Emitters/DependencyDiagnosticEmitter.cs
src/Games/NexusMods.Games.StardewValley/Emitters/SMAPIGameVersionDiagnosticEmitter.cs
src/Games/NexusMods.Games.StardewValley/Emitters/SMAPIModDatabaseCompatibilityDiagnosticEmitter.cs
src/Games/NexusMods.Games.StardewValley/Emitters/VersionDiagnosticEmitter.cs
src/Games/NexusMods.Games.StardewValley/StardewValley.cs

We want to use the same version that SMAPI uses for the diagnostics. 
I reused the existing GetVersion code and just adapted it enough to make it usable.
This is to fix all the exceptions we would otherwise get after any loadout operation for SDV due to diagnostics not having the correct version data.

Use correct version data for SDV diagnostics

---

src/NexusMods.App.UI/Pages/ItemContentsFileTree/IItemContentsFileTreeViewModel.cs
src/NexusMods.App.UI/Pages/ItemContentsFileTree/ItemContentsFileTreeView.axaml
src/NexusMods.App.UI/Pages/ItemContentsFileTree/ItemContentsFileTreeView.cs
src/NexusMods.App.UI/Pages/ItemContentsFileTree/ItemContentsFileTreeViewModel.cs

- Closes #2324
- Closes #2603 
Since the tree is static it doesn't react to changes, the only way to refresh the view is to recompute the tree from scratch, which resets the expanded states.
Functionality is there, experience isn't great. We need to move the file tree to new TreeDataGrid tech to make it dynamic and fix the performance/memory problems.

Add Delete button to mod contents File Tree view

---

src/NexusMods.Collections/CollectionDownloader.cs

Fixes #2626.
Before, the app would only check the loadout id, but never made sure the parent is the collection.

Check parent id for installation status

---

src/Abstractions/NexusMods.Abstractions.Collections/DirectDownloadLibraryFile.cs
src/Networking/NexusMods.Networking.NexusWebApi/ExternalDownloadJob.cs
src/NexusMods.Collections/CollectionDownloader.cs
src/NexusMods.DataModel.SchemaVersions/Migrations/_0006_DirectDownload.cs
src/NexusMods.DataModel.SchemaVersions/Services.cs
tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=Issue-2608.rocksdb.zip.verified.txt
tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=Migration-5.rocksdb.zip.verified.txt
tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=Migration-6.rocksdb.zip.verified.txt
tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=SDV.2_5_2025.rocksdb.zip.verified.txt
tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=SDV.4_11_2024.rocksdb.zip.verified.txt
tests/NexusMods.DataModel.SchemaVersions.Tests/MigrationSpecificTests/TestsFor_0006_DirectDownload.cs
tests/NexusMods.DataModel.SchemaVersions.Tests/Resources/Databases/Descriptions.md
tests/NexusMods.DataModel.SchemaVersions.Tests/Resources/Databases/Migration-6.rocksdb.zip

Fixes #2638.
- `DirectDownloadLibraryFile` entities now show up in the library
- `DirectDownloadLibraryFile` entities now have proper names

Fixes for `DirectDownloadLibraryFile`

---

src/NexusMods.App.UI/Controls/DevelopmentBuildBanner/DevelopmentBuildBannerView.axaml
src/NexusMods.App.UI/Controls/DevelopmentBuildBanner/DevelopmentBuildBannerView.axaml.cs

Text and color changes for bottom development banner
"Debug build" is replaced with version number on a release.
Closes #2546

Tweaks for development banner

---

src/NexusMods.App/ConsoleHelper.cs
src/NexusMods.App/NexusMods.App.csproj
src/NexusMods.App/Program.cs

fixes: [#2493](https://github.com/Nexus-Mods/NexusMods.App/issues/2493)
This will continue to be an issue in the future due to the utter jank way Windows handles CLI commands and compilation modes. But this work for now. 
Known issue: When you invoke a CLI command from the app, you instantly get a new prompt then the info from the app pops up afterwards. This is confusing and annoying but not required for our beta release. At least now the console doesn't pop up when you run the UI, and yet you can still use the CLI.

Don't show the console on windows

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ILoadoutSynchronizer.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/ISynchronizerService.cs
src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs
tests/Games/NexusMods.Games.TestFramework/AIsolatedGameTest.cs
tests/NexusMods.DataModel.Synchronizer.Tests/GeneralLoadoutManagementTests.SynchronizerIntegrationTests.verified.md
tests/NexusMods.DataModel.Synchronizer.Tests/GeneralLoadoutManagementTests.cs
tests/NexusMods.StandardGameLocators.TestHelpers/StubbedFileHasherService.cs

Preview view was showing wrong data, now it should show all the changes that will happen to the last analyzed disk state if the loadout is applied. 
This means that if something is on disk but not in the loadout it will appear as a normal entry in the preview, since it will not change. The preview will only show how the game folder will be affected by Apply, not how the loadout will be affected by apply.
I added a different method to determine whether Synchronize should be needed, since the previous one was ignoring a number of cases that still required a synchronize.
Also fixed exceptions that would happen due to missing LastAppliedLoadout data after switching lodouts.

Fix apply preview and exceptions when switching loadouts

---

src/NexusMods.Collections/InstallCollectionJob.cs

Fixes #2667.
In #2629 I removed the code that enabled collections after _any_ item has been installed. With this PR, collections will be enabled only if all required items have been installed.

Enable collection after is has been fully installed

---

src/NexusMods.Collections/CollectionDownloader.cs
src/NexusMods.Collections/InstallCollectionJob.cs

Fixes #2654.
We'd probably want to look at the UI again for this case later as it doesn't really make a lot of sense of you have no required mods. The tab for required mods is always visible and the text will say "All required mods downloaded/installed".

Allow installing collections with no required mods

---

src/NexusMods.App.UI/Extensions/EnumerableExtensions.cs
src/NexusMods.App.UI/NexusMods.App.UI.csproj
src/NexusMods.App.UI/Pages/BundledDataProvider.cs
src/NexusMods.App.UI/Pages/CollectionDataProvider.cs
src/NexusMods.App.UI/Pages/CollectionDownload/TreeDataGridCollectionResources.axaml
src/NexusMods.App.UI/Pages/ILoadoutDataProvider.cs
src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
src/NexusMods.App.UI/Services.cs

Resolves #2380 and fixes #2663.
Note that this messes up a lot of counts. The count for the `All (x)` left menu will be wrong since it counts the number of `LibraryLinkedLoadoutItem` entities in the loadout. The collection download page also shows the number of downloads (nexus mods or external) but bundled mods can't be downloaded, so the counts are a mess there too.
This would need a proper design pass later.

Show bundled mods in the loadout and collection download page

---

src/NexusMods.App.UI/Windows/WindowManager.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/WorkspaceController.cs

Fixes #2632.
Changing `if (data.Tabs.Length == 0)` to `if (_tabsList.Count == 0)`. Before we'd check if the data has no tabs, now we check if we created no tabs.
Also cleans up some code for restoring data, I'll probably do another pass on this at a later point.

Fix open panel with no tabs

---

src/NexusMods.Games.FileHashes/FileHashesService.cs

Moves the return statement into the if-statement, existing only if we loaded the DB, otherwise we get the latest DB.

Fix DB not getting loaded

---

src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDataProvider.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutDesignViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutView.axaml
src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutView.axaml.cs
src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutPage/ICollectionLoadoutViewModel.cs
src/NexusMods.Collections/InstallCollectionDownloadJob.cs
src/NexusMods.Collections/Services.cs
src/NexusMods.Collections/Verbs.cs
src/NexusMods.Icons/IconValues.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml

This is a start on getting the Collection Loadout Page up to date with [Figma](https://www.figma.com/design/5LmVL8YpgDHFSFA76fgCZA/%F0%9F%93%B1-Mod-library?node-id=2290-35931&m=dev) while @Al12rs and @erri120 are working on the functionality.
Elements that need wiring up:
- Read only pill `StackPanel#ReadOnlyPillStack` needs showing\hiding based on if the collection is read only or not. This StackPanel includes the dot seperator.
- Total mods `TextBlock#TotalModsTextBlock` needs to update based on how many mods are installed (both optional and required)
- 'View mod files' button `StandardButton#ViewModFilesButton` needs to work the same as it does on 'All', shows the file system contents of the mod
Part of #2598

Layout change for Collection Loadout Page

---

Directory.Packages.props
src/NexusMods.Games.FileHashes/FileHashesService.cs
src/NexusMods.StandardGameLocators/HeroicGogLocator.cs
src/NexusMods.StandardGameLocators/Services.cs
tests/NexusMods.StandardGameLocators.TestHelpers/Services.cs

Upgrade GameFinder to 4.5.0

---

NexusMods.App.sln
src/Abstractions/NexusMods.Abstractions.EventBus/IEventBus.cs
src/Abstractions/NexusMods.Abstractions.EventBus/IEventBusMessage.cs
src/Abstractions/NexusMods.Abstractions.EventBus/IEventBusRequest.cs
src/Abstractions/NexusMods.Abstractions.EventBus/IEventBusRequestHandler.cs
src/Abstractions/NexusMods.Abstractions.EventBus/NexusMods.Abstractions.EventBus.csproj
src/NexusMods.App.Cli/CliMessages.cs
src/NexusMods.App.Cli/NexusMods.App.Cli.csproj
src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs
src/NexusMods.App.UI/EventBus.cs
src/NexusMods.App.UI/NexusMods.App.UI.csproj
src/NexusMods.App.UI/Services.cs
src/NexusMods.App.UI/Settings/BehaviorSettings.cs
src/NexusMods.App.UI/Settings/ServiceExtensions.cs
src/NexusMods.App.UI/UiMessages.cs
src/NexusMods.App.UI/Windows/IWorkspaceWindow.cs
src/NexusMods.App.UI/Windows/MainWindow.axaml.cs
src/NexusMods.App.UI/Windows/MainWindowViewModel.cs

- Implements a simple event bus (Resolves #1537)
- Opens the collection download page when a collection gets added and brings the app window to the front (resolves #2548)
- Brings the app window to the front when a download is added (resolves #2689)
- Adds a setting for users to toggle the behavior of bringing the app window to the front

Event Bus and reacting to downloads

---

src/Games/NexusMods.Games.StardewValley/Emitters/Helpers.cs

The SMAPI API doesn't return any data if the `ISemanticVersion` we're passing on is "non-standard". Although the API type allows any `ISemanticVersion` implementation, it apparently doesn't like anything other than versions created using the `SemanticVersion(Version)` constructor.
This fix changes the behavior of how we create `SemanticVersion` to the old behavior of passing the `System.Version` we get from the Stardew Valley DLL to the `SemanticVersion` constructor.
Fixes #2705.

Fix `GetGameVersion` for Stardew Valley

---

src/Abstractions/NexusMods.Abstractions.GameLocators/IGameLocatorResultMetadata.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/LocatorId.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/Stores/EADesktop/EADesktopLocatorResultMetadata.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/Stores/EGS/EpicLocatorResultMetadata.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/Stores/GOG/GOGLocatorResultMetadata.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/Stores/Origin/OriginLocatorResultMetadata.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/Stores/Steam/SteamLocatorResultMetadata.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/Stores/Xbox/XboxLocatorResultMetadata.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/VanityVersion.cs
src/Abstractions/NexusMods.Abstractions.Games.FileHashes/IFileHashesService.cs
src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/Models/Loadout.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/NexusMods.Abstractions.Loadouts.csproj
src/Games/NexusMods.Games.StardewValley/Emitters/Helpers.cs
src/Games/NexusMods.Games.StardewValley/Installers/SMAPIInstaller.cs
src/NexusMods.App.UI/Controls/GameWidget/GameWidgetViewModel.cs
src/NexusMods.DataModel.SchemaVersions/Migrations/_0004_RemoveGameFiles.cs
src/NexusMods.DataModel/CommandLine/Verbs/LoadoutManagementVerbs.cs
src/NexusMods.Games.FileHashes/FileHashesService.cs
src/NexusMods.StandardGameLocators/ManuallyAddedGame.cs
src/NexusMods.StandardGameLocators/Unknown/UnknownLocatorResultMetadata.cs
tests/NexusMods.DataModel.Synchronizer.Tests/SynchronizerUnitTests.cs
tests/NexusMods.DataModel.Tests/LoadoutObservableTests.cs
tests/NexusMods.StandardGameLocators.TestHelpers/StubbedFileHasherService.cs

Cleanup PR. Functionality shouldn't be affected.
- Adds two new value types: `VanityVersion` and `LocatorId`
- Removes and updates many methods from `IFileHashesService`
- Refactors the implementations of `IFileHashesService`

Refactor `IFileHashesService` and implementations

---

src/NexusMods.Telemetry/EventSender.cs
tests/NexusMods.Telemetry.Tests/EventSenderTests.cs

Fixes: #2615
Fixes for other network related errors will come in future PRs. This logs a debug message on failed sends for telemetry events, for testing purposes, being a "debug" level it won't show up in most users logs.

Silence the event sender errors, but log them with a debug message

---

src/NexusMods.App.UI/LeftMenu/Items/HealthCheckLeftMenuItemViewModel.cs
src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
src/NexusMods.App.UI/Pages/Diagnostics/List/DiagnosticListViewModel.cs

Fixes #2720, also only displays the icons in the left menu when the diagnostics are not filtered by the severity settings.

Respect health check settings in the summaries and side menu

---

src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardView.axaml.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionCards/CollectionCardStyles.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionDownloadPage/CollectionDownloadPageStyles.axaml

Small PR that adds a `NoRating` class so we can style the success rating in grey if it's 0% instead of red. 0% isn't going to mean it's unsuccessful and so will do us for now.

Styling workaround for Success Rating

---

src/NexusMods.App.UI/WorkspaceSystem/Page/PageFactoryController.cs
src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/IWorkspaceController.cs
src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/WorkspaceController.cs

Fixes #2735 opening the default page. This should guarantee that we don't end up in a situation where the workspace is completely broken.

Use fallback page instead of breaking the workspace

---

src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardViewModel.cs
src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs

Doesn't do a lookup anymore and just passes the revision directly, fixes #2749.
The bug was caused because we'd observe all revisions and create cards out of them, the cards constructor would get passed an ID and do a lookup for the revision using LINQ `First()` which throws an exception if there are no items in the source enumerable. This can happen if the collection gets deleted, which sends the user to the library and then there's probably a race condition where the revision gets deleted while we try to create the collection card.
With this PR we won't get an exception, the card will disappear immediately.

Pass revision directly

---

src/Games/NexusMods.Games.StardewValley/Emitters/DependencyDiagnosticEmitter.cs
src/Games/NexusMods.Games.StardewValley/Emitters/MissingSMAPIEmitter.cs
tests/Games/NexusMods.Games.StardewValley.Tests/DependencyDiagnosticEmitterTests.Test_DisabledRequiredDependency_Collections.verified.txt
tests/Games/NexusMods.Games.StardewValley.Tests/DependencyDiagnosticEmitterTests.cs
tests/Games/NexusMods.Games.StardewValley.Tests/MissingSMAPIEmitterTests.cs
tests/Games/NexusMods.Games.TestFramework/AIsolatedGameTest.cs
tests/Games/NexusMods.Games.TestFramework/ALoadoutDiagnosticEmitterTest.cs

- Fixes parts of #2687
Fixed three bugs, each covered by new tests cases:
- RequiredDependencyIsOutdated
Appears when the dependency is disabled on the loadout - should only appear when enabled 
- SMAPIRequiredButDisabled
Does not appear when SMAPI is in a disabled collection.
- DisabledRequiredDependency
Appears if there is at least a disabled version of the dependency, even though there are enabled versions
I think remaining bugs listed on #2687 might be fixed by updating SMAPI submodule, but I haven't gotten around to looking into that yet.

SDV Health Check fixes

---

src/Games/NexusMods.Games.StardewValley/Emitters/SMAPIGameVersionDiagnosticEmitter.cs

As part of #2616 this PR changes the SMAPI metadata download errors from a `.LogError` to `.LogWarning`. The code was already resiliant (didn't cause crashes) but we were logging errors which caused the error popups. Verified that the dialog no longer shows up after this PR and that we don't spam the log with tons of errors, only one error per launch.

Log the SMAPI mapping errors as warnings so we don't get error popups

---

src/NexusMods.App.UI/Controls/TreeDataGrid/SizeComponent.cs
src/NexusMods.App.UI/Converters/SizeToStringTypeConverter.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardView.axaml.cs
src/NexusMods.App/Startup.cs

It's been a long time coming but here goes...
Size (`NexusMods.Paths.Size`) now has a ReactiveUI `IBindingTypeConverter` which is globally registered. Whenever a Size is bound to a UI control (normally a TextBlock's Text property) it automatically kicks in.
When SizeComponent is used in a TreeDataGrid, Humanize is directly used without the above converter.
Humanize returns either a single decimal point if 1 GB in size or greater, no decimal points if not.
Numbers can be formatted either by Humanize (if need it to say 1.1k instead of 1123) or by using "N0" format for it to have thousand separators. Generally applied in the code-behind in the OneWayBind's
Should we also be using Humanize if we just want thousand separators ?
Closes https://github.com/Nexus-Mods/NexusMods.App/issues/2372

Displaying Sizes and Numbers using Humanize

---

tests/Games/NexusMods.Games.StardewValley.Tests/DependencyDiagnosticEmitterTests.cs

`Test_RequiredDependencyIsOutdated` is failing due to some test code that was accidentally committed.
If an Outdated dep is disabled, you will get a `Disabled` or `Missing` dependency diagnostic instead, so it won't be empty.

Fix Test: remove leftover code

---

src/NexusMods.App.UI/Controls/TreeDataGrid/CompositeItemModel.cs

@Al12rs and I found another deadlock that happened because the DB event thread was calling `R3.BehaviorSubject.OnNext` which locked the subject and then triggered an activation on the UI thread which does a subscribe on the subject which is locked and thus we got a deadlock.
The subject in question was on the collection download page https://github.com/Nexus-Mods/NexusMods.App/blob/e18a22d31d51de5618f53facea31168bfb5f20eb/src/NexusMods.App.UI/Pages/CollectionDataProvider.cs#L140 the entire method needs some cleaning up later.
This PR should prevent any future deadlocks from happening in regards to subscriptions.

Fix deadlock for component subscriptions

---

src/NexusMods.App.UI/DiagnosticSystem/LoadoutItemGroupFormatter.cs
src/NexusMods.App.UI/DiagnosticSystem/LoadoutReferenceFormatter.cs

Fixes #2793, instead of throwing an exception we verify the entity and write an error message if it's invalid.

Verify entity before accessing name

---

src/NexusMods.Collections/CollectionDownloader.cs
src/NexusMods.Collections/DownloadCollectionJob.cs
src/NexusMods.Collections/Verbs.cs

Fixes #2766 
This PR provides hyperlinks to all mods that are missing for collections when a free user tries to install a collection through CLI. Instead of opening all mod URLs at once for free users, this also cancels out future jobs which would have otherwise made an more exceptions due to missing mods.
Original PR: *This PR gets the number of required downloads for a collection and checks if it passes the limit condition (in this case 10 or less) before opening the URLs (only for free users).*

[CLI] Hyperlinks for collection downloads for free users

---

src/NexusMods.App.UI/Pages/BundledDataProvider.cs
src/NexusMods.App.UI/Pages/ILoadoutDataProvider.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutComponents.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutPage/TreeDataGridLoadoutResources.axaml
src/NexusMods.App.UI/Pages/LocalFileDataProvider.cs
src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
src/NexusMods.Icons/IconValues.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml

- Part of #2782 
- And part of #2598 
The `IsEnabled` component contained the normal toggle, plus the `IsLocked` state plus the `LoadoutItemIds`.
To implement all the possible state combinations for parent and child items it is better to separate these.
This also includes the UI and icons changes by @insomnious from #2795
This shouldn't change the current behaviour much, except for showing the Toggle rather than parent items showing Toggle rather than Locked state if at least one child is Togglable.

Refactor and separate `IsEnabled` loadout column component into separate states

---

src/NexusMods.Collections/CollectionDownloader.cs
src/NexusMods.Collections/DownloadCollectionJob.cs

Resolves #2816.
`Parallel.ForAsync` will cancel all cancellation tokens if one loop iteration throws an exception. This means that if a download fails for some reason we'd stop downloading everything else as well. This PR adds a `try/catch` so that we keep downloading.

Continue downloading collection files after exception

---

src/NexusMods.App.UI/Controls/Spine/SpineViewModel.cs

- Fix #2780 
Ignore whitespace changes when reviewing since I fixed a bad indentation.
I think this is a regression caused by the changes we made to the Db, one of those assumptions about data being populated immediately no longer being valid.
I made it work regardless of that and cleaned up some of the old code a bit.

Fix spine active item at startup

---

src/Abstractions/NexusMods.Abstractions.Jobs/IJobMonitorExtensions.cs
src/NexusMods.Jobs/JobMonitor.cs

This is a small patch to the jobs system to stop the jobs from endlessly increasing in size as the user uses the App for longer periods of time. Because keeping jobs around also keeps info tied to them around, including Datoms and other resources.
There's a few places that listen to active jobs; I've checked all of them after adding the patch:
- Determining if collections are downloaded.
- Determining if a game (any game) is currently running
- Download button on spine showing download completion.
- Login service.
I have manually confirmed none of the services are affected by this change; they work as they have previously without the patch.

Improved: Remove Jobs after Completing Them

---

src/NexusMods.DataModel.SchemaVersions/Services.cs

We keep the migration service in memory all the time, but it's only ran once at startup; so we don't actually need to keep it around. This makes it transient such that we don't unnecessarily keep it around.

Changed: Set the to MigrationService Transient

---

src/Games/NexusMods.Games.StardewValley/WebAPI/SMAPIWebApi.cs

Switch SMAPI API failures to warnings to avoid spamming users with the Exception dialog.
- Closes #2821

Silence SMAPI API exceptions

---

src/NexusMods.App.UI/Controls/TreeDataGrid/CompositeItemModel.cs
src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridItemModel.cs
src/NexusMods.App.UI/Converters/IsNotNullConverter.cs
src/NexusMods.App.UI/Converters/IsNullConverter.cs
src/NexusMods.App.UI/Pages/BundledDataProvider.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionComponents.cs
src/NexusMods.App.UI/Pages/ILoadoutDataProvider.cs
src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutComponents.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutPage/TreeDataGridLoadoutResources.axaml
src/NexusMods.App.UI/Pages/LocalFileDataProvider.cs
src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridActionsColumnStyles.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/StylesIndex.axaml

- Closes #2782
- Part of #2598 
- Fixed a ObjectDisposedException in ITreeItemModel by marking item as disposed before removing child items
- Implemented Parent collection disabled state for page (parent) loadout entries
- Implement parent items toggling functionality in case of presence of Locked enabled child items
- Implemented item toggling functionality in the CollectionLoadoutPage
- Fix ToggleSwitch not updating correctly when being set to three state by showing a custom button with an icon instead
- Add `MixLockedParentDisabled` special collection indeterminate state in case all children are either locked or parent disabled
@insomnious

Add special Toggle states and behaviours for parent items in Loadout and Collection Views

---

src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridAdapter.cs
src/NexusMods.App.UI/Pages/LibraryPage/LibraryComponents.cs
src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutComponents.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs

- Closes #2801 
- Part of #2778 
- Part of #1229
- Tried implementing default sorting for TreeDataGrid views to mediocre results:
The sorting is applied while the tree is still being populated, and doesn't enforce sorting as new items come in, so it is only kinda sorted...
Edit: Removed since it was inconsistent
- Sorted Library Actions column as requested here https://github.com/Nexus-Mods/NexusMods.App/issues/2801#issuecomment-2710966531
- Sorted Library Version column as requested here: https://github.com/Nexus-Mods/NexusMods.App/issues/2801#issuecomment-2710977261
- Fixed bug in Collection and EnabledState column sorting, where same value was compared against itself

Tree views sorting: Actions, Version, EnabledState and Collection columns

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
tests/NexusMods.DataModel.Synchronizer.Tests/SynchronizerUnitTests.cs

- Fixes #2077 
- Added the empty directory cleanup code to the `DeactivateCurrentLoadout` path
- Implemented a regression test for cleaning up folders when switching profiles
- Fixed previous loadout being applied twice during loadout switch (`DeactivateCurrentLoadout` already applies previous loadout).
Before the switch to our new system handling game updates we used to have the concept of a Vanilla loadout.
During remove loadout or unamange game operations we would switch to the Vanilla loadout, so all synchronize operations could be seen as applying some loadout. Unamanging the game and switching a loadout were doing the same loadout switch operation.
The new system has the concept of Deactivating a loadout, which is used during loadout removal or during game unmanage operations. …

Cleanup empty directories when switching loadouts

---

src/NexusMods.App.UI/Controls/TreeDataGrid/ColumnContentControl.cs

Repro using the Library tree:
- Install a mod
- Uninstall the mod
- Install the mod again
- Get `InvalidOperationException`
The exception was thrown because we try to set a control as child of a new border while it was still a child of the old border. This only happens for fallback controls as they are only created once.
The PR properly detaches those controls before assigning them to something else.

Fix "control already has a parent"-exception

---

src/NexusMods.App.UI/Pages/Diagnostics/Details/DiagnosticDetailsPage.cs
src/NexusMods.App.UI/Pages/Diagnostics/List/DiagnosticListViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/Page/IPageFactoryContext.cs
src/NexusMods.App.UI/WorkspaceSystem/PanelTab/PanelTabViewModel.cs

Resolves #2682.
Ephemeral pages can now specify another page to be serialized instead. This allows the diagnostics details page to specify the diagnostics list page.

Allow pages to specify serializable page data

---

src/NexusMods.SingleProcess/CliServer.cs
src/NexusMods.SingleProcess/CliSettings.cs

Before, the CliServer would create a cancellation token source that cancels after 1 second inside a while loop and use that token for `AcceptTcpClientAsync`. This meant that every second we're creating new token sources and every second we'd throw an `OperationCanceledException`.
This seemed very unusual, I couldn't figure out why we'd want that, so I updated the code to just use the main cancellation token.

Remove timeout and cancel exception from CliServer

---

Directory.Packages.props

Currently to build the app you need both .NET 8 and .NET 9. This is because Strawberry Shake took awhile to upgrade to .NET 9. 
Build the app with only .NET 9 on a machine, you get a build error. 
Update to Strawberry Shake 15

Update Strawberry Shake (GraphQL Client)

---

src/NexusMods.Telemetry/TrackingDataSender.cs

We only want to see exceptions from releases.

Don't send exceptions in debug builds

---

src/NexusMods.App.UI/Controls/TreeDataGrid/AValueComponent.cs
src/NexusMods.App.UI/Controls/TreeDataGrid/CompositeItemModel.cs
src/NexusMods.App.UI/Controls/TreeDataGrid/ICompositeColumnDefinition.cs
src/NexusMods.App.UI/Controls/TreeDataGrid/IItemModelComponent.cs
src/NexusMods.App.UI/Converters/CompositeStyleFlagConverter.cs
src/NexusMods.App.UI/NexusMods.App.UI.csproj
src/NexusMods.App.UI/NexusMods.App.UI.csproj.DotSettings
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGrid/ILoadOrderDataProvider.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGrid/LoadOrderComponents.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGrid/LoadOrderDataProvider.cs

- Part of #2885
- Adds preliminary support for Row level `CompositeItemModel` styling through `StyleFlags` property
- Adds option to set ColumnHeader name at creation time (load order header name is game specific)
- Adds Components for Load Order items
- Adds LoadOrderDataProvider that converts `SortableItems` to `CompositeItemModels` (not yet in use)

Add Load Order `CompositeItemModel` components and DataProvider

---

src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGridLoadOrderResources.axaml

- Part of #2885 
Not used yet, will be integrated in future pr.

Load Order UI for `CompositeItemModel` based columns

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
tests/NexusMods.DataModel.Synchronizer.Tests/ExternalChangesTests.cs
tests/NexusMods.DataModel.Synchronizer.Tests/GeneralFileManagementTests.SynchronizerFileManagementTest.verified.md

Fixes issue-2908
We were not looking for and re-using existing external file records when ingesting changes. This would also cause the "duplicate key" exception on subsequent applies and in the "preview changes" dialogs

Don't re-insert files that change during ingestion

---

src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/MessageBox/MessageBoxStyles.axaml

Just a matter of updating the reference to the new semi version.
Happened by unfortunate timing, the PR for the new dialog didn't have the UI Styling refactor changes yet, and the refactor PR didn't have the dialog.

Fix `BodyMDBoldTheme` error

---

src/Abstractions/NexusMods.Abstractions.Games/ILoadoutSortableItemProvider.cs
src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/SortOrder/RedMod/RedModSortableItemProvider.cs
src/NexusMods.App.UI/Controls/TreeDataGrid/ICompositeColumnDefinition.cs
src/NexusMods.App.UI/Controls/TreeDataGrid/IItemModelComponent.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/ILoadOrderViewModel.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderItemModel.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderView.axaml.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderViewDesignViewModel.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderViewModel.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGridLoadOrderResources.axaml
src/NexusMods.App.UI/Pages/Sorting/SortingSelection/SortingSelectionViewModel.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridBaseStyles.axaml

- Part of #2885 
This actually moves the view over to using the new `CompositeItemModel` based tree items and updates all the functionality and bindings to work with the new system.
Some styling fixes work is going to be necessary, after which the leftover code from the previous approach can be cleaned up.
In particular, the `IsActive` styling has some issues due to `x:DataType` not being able to accept Types with type parameters correctly:
- https://github.com/AvaloniaUI/Avalonia/pull/18379
PR is merged but not released yet.

Load Order tree migration: integration into `LoadOrderViewModel` and `GridAdapter`

---

src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridItemModel.cs

- fixes #2804 
The access to the children is expected and not avoidable after they are cleared, so the assert can be removed.

Remove DebugAssert that checks for disposed item in TreeDataGridItemModel GetChildren

---

src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionMetadata.cs
src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/Models/CollectionRevisionMetadata.cs
src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/NexusModsFileMetadata.cs
src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/NexusModsModPageMetadata.cs
src/Abstractions/NexusMods.Abstractions.Telemetry/NexusModsURLBuilder.cs
src/Games/NexusMods.Games.Larian/BaldursGate3/BaldursGate3.cs
src/Games/NexusMods.Games.Larian/BaldursGate3/Emitters/DependencyDiagnosticEmitter.cs
src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Diagnostics/BannerlordDiagnosticEmitter.cs
src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/Cyberpunk2077Game.cs
src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/Emitters/PatternBasedDependencyEmitter.cs
src/Games/NexusMods.Games.StardewValley/Emitters/Helpers.cs
src/Games/NexusMods.Games.StardewValley/WebAPI/SMAPIWebApi.cs
src/Networking/NexusMods.Networking.NexusWebApi/NexusModsDownloadJob.cs
src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.cs
src/Networking/NexusMods.Networking.NexusWebApi/V1Interop/GameDomainToGameIdMappingCache.cs
src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDownload/ManualDownloadRequiredOverlay.cs
src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
src/NexusMods.Collections/CollectionDownloader.cs
src/NexusMods.Collections/Verbs.cs
tests/NexusMods.Telemetry.Tests/NexusModsURLBuilderTests.cs

Resolves #2951.
Every link going to Nexus Mods is now created in the `NexusModsUrlBuilder`. I did a full solution search for links and I updated every hardcoded link to use the builder.
I've also updated our campaigns, many links previously didn't had any tracking campaigns but now they do.

Update outgoing Nexus Mods links

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/NexusMods.StandardGameLocators/Unknown/UnknownLocatorResultMetadata.cs
tests/NexusMods.DataModel.Synchronizer.Tests/ExternalChangesTests.cs
tests/NexusMods.StandardGameLocators.TestHelpers/UniversalStubbedGameLocator.cs

Part of #2887.
Before, the method would find a matching vanity version based on the current disk state. This approach was flawed and resulted in the bug shown in #2887. This PR changes the behavior to re-query the game locator IDs directly from the game locator.

Update `ReprocessGameUpdates` to re-query game locators for IDs

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs

Forgot to stage and commit this change in #2973. This logs files that the app doesn't have hash data for.

Log falling back to doing a full hash

---

Directory.Packages.props
src/Abstractions/NexusMods.Abstractions.Library.Models/LibraryItem.cs
src/Abstractions/NexusMods.Abstractions.Loadouts/Models/DiskStateExtensions.cs
src/Abstractions/NexusMods.Abstractions.Resources.DB/PersistedDbResourceLoader.cs
src/NexusMods.DataModel.SchemaVersions/Migrations/_0005_MD5Hashes.cs

This updates to the latest MnemonicDB. A few things had to change in this PR to remain compatible:
* Some `.Datoms` calls now return specific index types. For example `EntitySegment` is a much smaller version of `IndexSegment` that only stores the `A` and `V` parts of the datom resulting in a fairly substantial reduction in memory usage
* Some of our iterations over entities now use `.TryGetValue` which is much faster as internally it's setup to use .NET's SIMD operations over `Span<AttributeId>` 
Aside from the below changes, the rest of the API is hasn't changed, it uses less memory and is quite a bit faster

Upgrade to the latest mnemonicdb and fix associated bugs

---

tests/Games/NexusMods.Games.StardewValley.Tests/DependencyDiagnosticEmitterTests.Test_MissingRequiredDependency.verified.txt
tests/Games/NexusMods.Games.StardewValley.Tests/DependencyDiagnosticEmitterTests.Test_RequiredDependencyIsOutdated.verified.txt
tests/Games/NexusMods.Games.StardewValley.Tests/MissingSMAPIEmitterTests.Test_SMAPIRequiredButNotInstalled.verified.txt
tests/Games/NexusMods.Games.StardewValley.Tests/SMAPIModDatabaseCompatibilityDiagnosticEmitterTests.Test_ModCompatabilityAssumeBroken.verified.txt

Fix Stardew diagnostic verify tests failing due to URL changes with the added campaign

Fix SDV diagnostic Verify test due to changes in URLs

---

Directory.Packages.props
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderViewModel.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGrid/LoadOrderComponents.cs
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridBaseStyles.axaml

- Fixes #2941 
Upgrade several Avalonia packages to their latest versions and add IsActive styling to Load Order now that x:DataType supports type parameters.
NOTE: Rider still gives an error for the type parameter, but building and running works fine.
Upgrade packages:
- Avalonia
- AvaloniaEdit
- R3
- ObservableCollections
And other packages related to them

Upgrade Avalonia packages and add Load Order "IsActive" styling

---

src/Abstractions/NexusMods.Abstractions.Library.Installers/ALibraryArchiveInstaller.cs
src/Abstractions/NexusMods.Abstractions.Library.Installers/ALibraryFileInstaller.cs
src/Abstractions/NexusMods.Abstractions.Library.Installers/InstallerResult.cs
src/Games/NexusMods.Games.AdvancedInstaller.UI/AdvancedManualInstallerUI.cs
src/Games/NexusMods.Games.AdvancedInstaller/AdvancedManualInstaller.cs
src/Games/NexusMods.Games.FOMOD/FomodXmlInstaller.cs
src/Games/NexusMods.Games.StardewValley/Installers/GenericInstaller.cs
src/Games/NexusMods.Games.StardewValley/Installers/SMAPIInstaller.cs
src/NexusMods.Library/InstallLoadoutItemJob.cs
tests/Games/NexusMods.Games.StardewValley.Tests/GenericInstallerTests.cs

Providing more debug information for us, currently just set to log level `Trace`.

Adds a reason to installer returning `NotSupported`

---

.github/workflows/networking_tests.yaml
src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridAdapter.cs
src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridViewHelper.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderView.axaml
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderView.axaml.cs

- Part of #2276
This adds a `enableDragAndDrop` parameter to the setup of the `TreeDataGridAdapter`.
This enables drag and drop support on the tree and provides two subjects for `RowDragStarted` and `RowDrop` events.
Added code to extract the source and target models from the event data.
The original eventArgs are still passed to the subject since they can contain useful data like drop position, or can allow altering the state of the Drag indicator (can drop, can't drop etc).   
I checked with breakpoints that the extraction of the `sourceModels` and `targetModel` worked fine.

TreeDataGrid Adapter support for drag/drop events

---

src/Abstractions/NexusMods.Abstractions.Games/ILoadoutSortableItemProvider.cs
src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/SortOrder/RedMod/RedModSortableItemProvider.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderView.axaml.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderViewModel.cs

- Part of #2276 
- Added stubbed `MoveIitems` method to `ILoadoutSortableItemProvider` that will contain the main moving logic for RedMods.
- Normalized the drag/drop event data in the `LoadOrderViewModel` depending on the `SortDirectionCurrent`.
- Made Drop position `Inside` result in either `Before` or `After` to avoid dropped items not moving due to drop position being too central.
- Enabled drag and drop in the UI for testing. Items won't move but it is possible to drag them and see the effects.
Next step is to implement the main logic inside `MoveItems`

Load Order: Drag and Drop Setup and prepare data 

---

src/Abstractions/NexusMods.Abstractions.Games/ISortableItemProviderFactory.cs
src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/SortOrder/RedMod/RedModSortableItemProviderFactory.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderViewDesignViewModel.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderViewModel.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGrid/LoadOrderComponents.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGrid/LoadOrderDataProvider.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGridLoadOrderResources.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/Sorting/LoadOrderStyles.axaml

Not entirely happy with the naming, the column heading is "Parent mod" in Figma, but elsewhere in the codebase we just call it ModName, with the main Name column becoming DisplayName. I'd appreciate your thoughts.
Waiting on #3020 to be merged

Adds Parent Mod column to Load Order UI

---

src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridBaseStyles.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridSortOrderStyles.axaml

- Part of #2276
Adds an extra Border so we can have a visual gap between rows but the load order drag and drop treats it as no gaps.
https://github.com/user-attachments/assets/eacdb5ed-afbe-49e2-8f79-6fd12cb03ad0

Fixes UI issue with Row spacing when dragging/dropping 

---

src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs
tests/NexusMods.FileExtractor.Tests/SevenZipExtractionTests.cs

Fix extraction of archives that contain `.` or `..`

---

src/NexusMods.App.UI/Pages/Sorting/LoadOrdersWIPPage.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrdersWipPageViewModel.cs

The actual files are still called WIP since the load order view will still eventually be moved to some other place instead of the dedicated page.

Remove WIP from Load Order tab name

---

src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridAdapter.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderViewModel.cs

- fixes #3043
Support setting a custom root sorter to `TreeDataGridAdapter`, and manually resort the list when it changes. This isn't very efficient at all if there are many unbatched changes, but it should be much more reliable than the previous code.

Fix Load Order sorting no longer working with higher item counts

---

src/ArchiveManagement/NexusMods.FileExtractor/Extractors/ManagedZipExtractor.cs
src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs
src/ArchiveManagement/NexusMods.FileExtractor/PathsHelper.cs
src/ArchiveManagement/NexusMods.FileExtractor/Services.cs
tests/NexusMods.FileExtractor.Tests/PathsHelperTests.cs
tests/NexusMods.FileExtractor.Tests/SevenZipExtractionTests.cs

Adds a new extractor using `System.IO.Compression.ZipArchive` to extract ZIP archives instead of using 7zip. Some quick benchmarks show a 29-36% performance increase when using the new extractor over 7z:
https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=21567&game_id=3333
- SevenZip: 21198 ms
- ManagedZip: 13642 ms
https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=32406&game_id=3333
- SevenZip: 19671 ms
- ManagedZip: 13995 ms

Add managed ZIP extractor

---

Directory.Packages.props

Fixes an objected disposed exception when closing the app on Linux.

Upgrade `LinuxDesktopUtils` from `1.0.0` to `1.0.2`

---

src/ArchiveManagement/NexusMods.FileExtractor/Extractors/ManagedZipExtractor.cs
src/ArchiveManagement/NexusMods.FileExtractor/PathsHelper.cs
tests/NexusMods.FileExtractor.Tests/PathsHelperTests.cs

Instead of being fancy by first fixing the directories and then the files, this just fixes all paths in one pass.
Should resolve issues we've seen with the new ZIP extractor.

Fix all parts of a path when extracting ZIP files

---

tests/Games/NexusMods.Games.RedEngine.Tests/RedModDeployToolTests.cs

Made some changes to make the tests more resilient to stalling. I wasn't able to make them fail after the changes, potentially by chance.
With these changes we should at least have the tests fail early and give us more context on where the failure happened.

Make tests more resilient to stalling

---

tests/Games/NexusMods.Games.RedEngine.Tests/RedModDeployToolTests.cs

The tests appear to be too unreliable.
The main complication is knowing when the `sortableItemProvider` has finished processing the addition of the mods, or the move changes.
Will be looking at options to improve what `SortableItemProvider` exposes and if some of the issues here can be resolved.

Disable Flaky LoadOrder related tests

---

src/Games/NexusMods.Games.FOMOD.UI/Step/GuidedInstallerStepViewModel.cs
src/NexusMods.App.UI/ImagePipelines.cs
src/NexusMods.App/Startup.cs

Fixes #3056.
The issue came from our use of the scoped cache and the interaction between disposed lifetimes and bitmaps. Removing the scoped cache and having better handling of disposing the image fixes the issue.

Fix app crashing on disposed bitmaps in the guided installer

---

src/Abstractions/NexusMods.Abstractions.Library.Installers/InstallerResult.cs
src/Games/NexusMods.Games.Generic/Installers/GenericPatternMatchInstaller.cs
src/Games/NexusMods.Games.Larian/BaldursGate3/Installers/BG3SEInstaller.cs
src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Installers/BLSEInstaller.cs
src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Installers/BannerlordModInstaller.cs
src/Games/NexusMods.Games.RedEngine/ModInstallers/AppearancePresetInstaller.cs
src/Games/NexusMods.Games.RedEngine/ModInstallers/FolderlessModInstaller.cs
src/Games/NexusMods.Games.RedEngine/ModInstallers/RedModInstaller.cs
src/Games/NexusMods.Games.RedEngine/ModInstallers/SimpleOverlayModInstaller.cs
src/NexusMods.Library/InstallLoadoutItemJob.cs
tests/NexusMods.StandardGameLocators.TestHelpers/StubbedGames/StubbedGameInstaller.cs

Makes it obsolete to not provide a reason when an installer returns `NotSupported`. I've also updated all existing installers to return a reason.

Update not supported reasons for installers

---

src/Abstractions/NexusMods.Abstractions.GameLocators/IGameLocatorResultMetadata.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/ILinuxCompatibilityDataProvider.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/Stores/EADesktop/EADesktopLocatorResultMetadata.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/Stores/EGS/EpicLocatorResultMetadata.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/Stores/GOG/GOGLocatorResultMetadata.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/Stores/Origin/OriginLocatorResultMetadata.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/Stores/Steam/SteamLocatorResultMetadata.cs
src/Abstractions/NexusMods.Abstractions.GameLocators/Stores/Xbox/XboxLocatorResultMetadata.cs
src/Games/NexusMods.Games.Generic/WineDiagnosticHelper.cs
src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/Emitters/WinePrefixRequirementsEmitter.cs
src/NexusMods.StandardGameLocators/BaseLinuxCompatibilityDataProvider.cs
src/NexusMods.StandardGameLocators/HeroicGogLocator.cs
src/NexusMods.StandardGameLocators/ManuallyAddedGame.cs
src/NexusMods.StandardGameLocators/SteamLocator.cs
src/NexusMods.StandardGameLocators/Unknown/UnknownLocatorResultMetadata.cs

Moves some code around to unify how we can get Linux compatibility data for a game locator result.
Required for #3066.
Fixes #3079.

Simplify getting linux compatibility data

---

src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs
src/Games/NexusMods.Games.Generic/GameToolRunner.cs
src/NexusMods.CrossPlatform/Process/FakeProcessFactory.cs
src/NexusMods.CrossPlatform/Process/IProcessFactory.cs
src/NexusMods.CrossPlatform/Process/OSInteropWindows.cs
src/NexusMods.CrossPlatform/Process/ProcessFactory.cs
src/NexusMods.CrossPlatform/Process/XDGSettingsDependency.cs
tests/NexusMods.CrossPlatform.Tests/OSInteropTests.cs

Exit code validation is questionable at best and unreasonable to have as a default set to true. This PR changes the default behavior to not have exit code validation. Any consumer of the API that cares about non-zero exit codes can set the option to have validation.
Resolves #3087.

Don't validate exit code by default

---

src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs

Should prevent duplicates when copying the same Loadout multiple times.
Fixes #2977.

Generate new Loadout name as late as possible

---

src/Abstractions/NexusMods.Abstractions.Games/ISortableItem.cs
src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/SortOrder/RedMod/RedModSortableItem.cs
src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/SortOrder/RedMod/RedModSortableItemProvider.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGrid/LoadOrderComponents.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGrid/LoadOrderDataProvider.cs
src/NexusMods.App.UI/Pages/Sorting/LoadOrder/TreeDataGridLoadOrderResources.axaml
src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/Sorting/LoadOrderStyles.axaml

- Closes #3096
- Closes #2277 
Please wait for @insomnious to fix some styling for the images before merging

Load Order: add support for thumbnail images

---

src/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs

- Fix #3113
Support installing collections in cases where there is no last applied loadout

Fix "No game installed with active loadout" error when downloading collections

---

src/NexusMods.App.UI/WorkspaceSystem/PanelTabHeader/PanelTabHeaderView.axaml.cs

Repost of #3122 to add changes
- Closes #1755.
This only closes tabs if the pointer is inside the bounds of the tab header at the time of both pressing and releasing, similar to how it works in popular web browsers.
Credits to @JonathanFeenstra

Close tabs on middle click

---

src/NexusMods.App.UI/Controls/Divider.cs
src/NexusMods.Themes.NexusFluentDark/Resources/ControlThemes/DividerControlTheme.axaml
src/NexusMods.Themes.NexusFluentDark/Resources/ControlThemes/StatusbarControlTheme.axaml
src/NexusMods.Themes.NexusFluentDark/Resources/ResourceIndex.axaml
src/NexusMods.Themes.NexusFluentDark/Styles/UserControls/Statusbar/StatusbarStyles.axaml

Closes #3130 
- Created simple `<Divider />` control (a bit like Separator) as it's used in loads of places and visually like a bullet point.
- Reworked styles to match Figma

Expanded Statusbar control

---

src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml
src/NexusMods.App.UI/WorkspaceSystem/PanelResizer/PanelResizerView.axaml
src/NexusMods.Themes.NexusFluentDark/Styles/UserControls/WorkspaceSystem/PanelViewStyles.axaml

We have an ongoing UI thing in Avalonia with how Backgrounds/CornerRadius/BorderBrush work together. It's not a bug but more just needing to know what happens and the best way to work with it so it feels intuitive.
Child elements are drawn after the parent and so if the parent has a rounded border, and ClipToBounds is set to true, the child background (which is a default rectangle the size of the bounds) corners are clipped by the parent. If the parent has a  BorderBrush (which is an inner border), then the child background is drawn over the parent border as this border is drawn before and within the bounds.
A background is going to be drawn rectangular unless the specific control has a CornerRadius value set and so if we wanted to solve the problem of the child background being drawn …

Fixes workspace panel corner issues

---

src/NexusMods.Networking.HttpDownloader/HttpDownloadJob.cs

Should resolve some download issues we had when using range requests.

Always use normal GET request when downloading an entire file

---

src/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/LeftMenuNavButtonStyles.axaml

A simple fix (I hope) of adding a transparent surface to it's background. This allows the mouse events to register correctly.
Fixes #3021

Fixed left nav button pointerover and clickable

---

src/NexusMods.App.UI/WorkspaceSystem/PanelResizer/IPanelResizerViewModel.cs
src/NexusMods.App.UI/WorkspaceSystem/PanelResizer/PanelResizerView.axaml.cs
src/NexusMods.App.UI/WorkspaceSystem/PanelResizer/PanelResizerViewModel.cs

- Fixes #3137
View was reacting to changes to `ActualStartPoint` before `ActualEndPoint` was set, causing inconsistent state

Fix exeption when resizing to full-screen with 4 panels

---

src/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/NexusMods.Abstractions.Loadouts.Synchronizers/ILoadoutSynchronizer.cs
src/NexusMods.Abstractions.Loadouts.Synchronizers/Rules/ActionMapping.cs
src/NexusMods.DataModel/CommandLine/Verbs/LoadoutManagementVerbs.cs
src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs

If a loadout has never been applied (and neither has the game), then there's no "previously applied state" and the loadout/tx state is set to `default` we later on in the synchronizer filter out any default states. 
TL;DR - in some rare cases where a user has *only* ever installed a collection, they may not see an apply button, this fixes that issue.
--
This also does the following: 
* Handles a case in Cyberpunk where there's two files that collide on the minimal hash. If we detect one or more possible hash files for a given minimal hash we bail out and hash the slow way
* Changes a broken mapping that was backing up files for no reason (leftover from when we had ignore paths)
* Adds a verb for manually reindexing a loadout's disk state, for testing

Fix for no apply button

---

Directory.Packages.props
src/NexusMods.App/Program.cs
src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs

Updates to the newest version of MnemonicDB which reworks how the application exits. Hard-exits the app after 15 seconds if it doesn't properly shutdown. Fix a but with crashing if the last scanned transaction datom wasn't set, we don't need it anyways, so we just use `.DiskEntries` on the game object instead

Fix for the app never exiting

---

src/NexusMods.Collections/CollectionDownloader.cs
src/NexusMods.Collections/DownloadCollectionJob.cs
src/NexusMods.Collections/DownloadSettings.cs
src/NexusMods.Collections/Services.cs
src/NexusMods.Networking.HttpDownloader/HttpDownloadJob.cs
src/NexusMods.Networking.HttpDownloader/Services.cs
src/NexusMods.Networking.NexusWebApi/ExternalDownloadJob.cs

- Use default HTTP client config
- Add retry on network exceptions
- Add setting to control max parallel download count for collections

More http download fixes

---

Directory.Packages.props
src/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/NexusMods.Abstractions.Loadouts.Synchronizers/ILoadoutSynchronizer.cs
src/NexusMods.Abstractions.Loadouts.Synchronizers/Rules/ActionMapping.cs
src/NexusMods.Abstractions.NexusWebApi/ILoginManager.cs
src/NexusMods.App/Program.cs
src/NexusMods.Collections/CollectionDownloader.cs
src/NexusMods.Collections/DownloadCollectionJob.cs
src/NexusMods.Collections/DownloadSettings.cs
src/NexusMods.Collections/Services.cs
src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationLinux.cs
src/NexusMods.DataModel/CommandLine/Verbs/LoadoutManagementVerbs.cs
src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs
src/NexusMods.Networking.HttpDownloader/HttpDownloadJob.cs
src/NexusMods.Networking.HttpDownloader/Services.cs
src/NexusMods.Networking.NexusWebApi/ExternalDownloadJob.cs
src/NexusMods.Networking.NexusWebApi/LoginManager.cs
tests/NexusMods.DataModel.Tests/Startup.cs

I'm pretty sure most of these fixes need backporting and/or we want these in 0.11.1, will verify after the PR builds

Backport fixes from main

---

src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardViewModel.cs

Some API endpoints return values between 0 and 100, others between 0 and 1. We previously used the latter which didn't work when switching to the former that resulted in always showing 100%.
Resolves #2370.

Fix collection rating parsing

---

src/NexusMods.App.UI/Windows/MainWindowViewModel.cs

We want to open the workspace of the active loadout for the game instead of the first workspace of the game.
Fixes #3188.

Open correct workspace when adding a collection

---

src/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/NexusMods.Abstractions.Loadouts.Synchronizers/ILoadoutSynchronizer.cs
src/NexusMods.Abstractions.Loadouts.Synchronizers/Jobs/SynchronizeLoadoutJob.cs
src/NexusMods.App.UI/LeftMenu/Items/ApplyControl/ApplyControlView.axaml.cs
src/NexusMods.App.UI/LeftMenu/Items/ApplyControl/ApplyControlViewModel.cs
src/NexusMods.App.UI/LeftMenu/Items/ApplyControl/IApplyControlViewModel.cs
src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs
src/NexusMods.Jobs/JobContext.cs

Makes the Applying indicator in the left menu accurately show when there is an apply operation in process, such as when managing the game for the first time.
- Added a job for the Synchronize operation so we can track it
- Fixed a bug with the HasActiveJob method not returning notifications due to missing initial State values 
- Fixed a bug with a rare path in create loadout that was applying the wrong lodout
- Use the SynchronizerService Synchronize method inside CreateLoadout to have tracking
- Some comments and readability cleanup

Fix Applying indicator and jobMonitor notifications

---

src/NexusMods.Abstractions.Games/RunGameTool.cs
src/NexusMods.Abstractions.Loadouts/Models/DiskStateExtensions.cs
src/NexusMods.Games.RedEngine/Cyberpunk2077/RunCyberpunk2077Game.cs
src/NexusMods.Games.RedEngine/RedModDeployTool.cs
src/NexusMods.Games.RedEngine/Resources/Cyberpunk2077/deploy_redmod.bat
src/NexusMods.Games.RedEngine/Services.cs

This does a few things:
* adds `-modded` to Cyberpunk when launching (always adds it)
* makes sure we provide the proper CLI commands to `redmod.exe` when we run it
* use `-modlist` instead of `--modlist` when calling redmod
* use `-force` so it always redeploys
* update the redmod `.bat` file so we can pass in arguments to the script 
NOTE: this also removes the `BulkCache` call from the app during the synchronizer runs. This was an optimization from the past that was breaking some things in the app. It's a long story, but with the recent bloom filter changes to MnemonicDB the bulk cache function would sometimes load partial entities, resulting in the `Missing attribute` errors we've been seeing. The loading features of MnemonicDB are so much faster now (and will get faster in the …

Fix the redmod deploy order

---

src/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/NexusMods.App.UI/Controls/TreeDataGrid/FileEntryComponent.cs
src/NexusMods.App.UI/Controls/TreeDataGrid/SharedColumns.cs
src/NexusMods.App.UI/Pages/LoadoutGroupFilesPage/LoadoutGroupFilesProvider.cs
src/NexusMods.App.UI/Pages/LoadoutGroupFilesPage/LoadoutGroupFilesViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutGroupFilesPage/LoadoutItemGroupHelpers.cs
src/NexusMods.App.UI/Pages/TreeDataGridSharedResources.axaml
src/NexusMods.Themes.NexusFluentDark/Styles/Controls/TextBlock/TextBlockStyles.axaml

The recent updates to the LoadoutGroup page didn't take deleted files into account. This change fixes this issue by changing `LoadoutFile` to `LoadoutItemWithTargetedPath` and conditionally loading `Size`. It also updates the `Pending Changes` page to show `WarnOfUnableToExtract`, so we actually see deleted files even if we don't have a source for them. 
* Create a game loadout
* Add a mod
* Go to the game folder and delete a game file
* Apply changes
* Verify that there is a `0` sized entry in the `External Changes` pane
* Delete the `0` sized file
* Verify that a warning appears in Health Check about a file not being found for the base game
* Verify that the file deleted shows up as a green entry in the `Pending Changes` dialog
We can improve this UX in the future, but at least for now …

Fixes for the loadout group page

---

tests/Games/NexusMods.Games.TestFramework/AIsolatedGameTest.cs

- Forcing non-graceful host shutdown
- Explicitly call `DisposeAsync` for tests
- Force complete disposing within 10 seconds

Force test disposal with timeout

---

src/NexusMods.Abstractions.GameLocators/WineParser.cs
tests/NexusMods.StandardGameLocators.Tests/WineParserTests.cs

Properly parses the section even if there are no quotes.
Fixes #3334.

Fix wine overrides section parser

---

src/NexusMods.Networking.NexusWebApi/NexusModsLibrary.Collections.cs

When uploading a collection revision, we can either create a new revision or update an existing revision. The latter causes issues in our data model because we previously assumed that revisions are mutable.
This "fix" is more of a hack and will remove all the previous downloads before adding the new ones. It will throw an exception if any of the previous download entities are referenced by anything.
Part of #3118.

Fix duplicate collection downloads on upload

---

src/NexusMods.StandardGameLocators/HeroicGogLocator.cs

Fixes #3336 
Fixed by passing the actual wine prefix directory to LinuxCompatibilityDataProvider, instead of heroic's wine context root.
I have very little experience with .NET/C#, so feedback is definitely welcome.

fixed problem where gog games installed with heroic would give a false positive on missing winetricks requirements

---

src/NexusMods.Games.RedEngine/RedModDeployTool.cs

Replaces Aggregate with string.Join to handle empty collections gracefully.
Previously, calling Aggregate on an empty collection would throw an exception, causing the Synchronizer to fail when no redmods were enabled.
I wasn't able to test this, so if someone wants to check please do.
- Ensure you have RedMod DLC installed
- Install a redmod mod but disable it (you should have no other enabled remods)
- Apply
- No exceptions should happen

Fix exception when writing empty RedMod loadorder file

---

src/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs

- Fixes #3417 
Retracting and Adding LocatorIds was resulting in no addition, manning that the game locator Id would be removed from the loadout, resulting in the entire game being put in External Changes and being backed up.

Fix app backing up entire game when DLC list changes

---

src/NexusMods.Abstractions.Collections/ManagedCollectionLoadoutGroup.cs
src/NexusMods.App.UI/Controls/Spine/SpineViewModel.cs
src/NexusMods.App.UI/LeftMenu/Items/NewCollectionViewModel.cs
src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutPage/ILoadoutViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutPage.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutTreeDataGridAdapter.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
src/NexusMods.App.UI/Pages/MyLoadouts/GameLoadoutsSectionEntry/GameLoadoutsSectionEntryViewModel.cs
src/NexusMods.App.UI/Pages/Sorting/SortingSelection/SortingSelectionViewModel.cs
src/NexusMods.Collections/CollectionCreator.cs
src/NexusMods.Networking.NexusWebApi/GraphQL/CollectionRevisionNumbers.graphql
src/NexusMods.Networking.NexusWebApi/GraphQL/CommonFragments.graphql
src/NexusMods.Networking.NexusWebApi/NexusModsLibrary.Collections.cs
tests/NexusMods.DataModel.SchemaVersions.Tests/Schema.verified.md

Requires #3502, part of #3493.
Cleans up `ILoadoutViewModel` to move to R3 bindings instead of ReactiveUI.
Fetches the current collection status from Nexus Mods on page loads and exposes the data in the VM. UI updates to follow soon :tm:.

Fetch collection status on page load and use R3 bindings

---

src/NexusMods.App.UI/Pages/ILibraryDataProvider.cs
src/NexusMods.App.UI/Pages/LibraryPage/LibraryComponents.cs
src/NexusMods.App.UI/Pages/LibraryPage/TreeDataGridLibraryResources.axaml
src/NexusMods.App.UI/Pages/LocalFileDataProvider.cs
src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs

This addresses:
- #3494
- Local Files: Always have the `Hide Update` button hidden.
- Nexus Files: The `Hide Update` button is hidden if the latest update is already in the library.

Improved: Hiding of Updates when No Updates Are Available

---

src/NexusMods.Abstractions.Loadouts/Models/Loadout.cs
src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuView.axaml.cs
src/NexusMods.App.UI/Pages/LoadoutPage/ILoadoutViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
src/NexusMods.App.UI/Settings/ExperimentalSettings.cs
src/NexusMods.App/Program.cs
src/NexusMods.App/Services.cs
src/NexusMods.Collections/CollectionCreator.cs
src/NexusMods.Collections/NexusMods.Collections.csproj
src/NexusMods.Telemetry/EventMetadata.cs
src/NexusMods.Telemetry/Events.cs

Enables collection creation for everyone, but collection sharing is now locked behind a setting. Also adds tracking events so we know how many people are using this feature.

Enable collection creation and add events

---

src/NexusMods.Abstractions.Jobs/IJob.cs
src/NexusMods.Abstractions.Jobs/IJobContext.cs
src/NexusMods.Abstractions.Jobs/IJobGroup.cs
src/NexusMods.Abstractions.Jobs/IJobMonitor.cs
src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
src/NexusMods.Games.AdvancedInstaller.UI/AdvancedManualInstallerUI.cs
src/NexusMods.Jobs/JobContext.cs
src/NexusMods.Jobs/JobGroup.cs
src/NexusMods.Jobs/JobMonitor.cs
src/NexusMods.Library/InstallLoadoutItemJob.cs

This adds the basic primitives for cancelling jobs, including handling for the special case of the Advanced Installer in a graceful (enough) way.
By request, I split this into just a small PR with the code.
I also wrote some docs, and found some things to patch up, those will be a separate PR later.
Related:
- #2727
fixes #2727
fixes #2723

Added: Job Cancellation Basics, including Advanced Installer Handler

---

src/NexusMods.App.UI/Pages/LoadoutPage/ILoadoutViewModel.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml.cs
src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
src/NexusMods.Collections/CollectionCreator.cs

Uses custom deletion code for the entities as `tx.Delete(recursive: true)` is too dangerous.

Implement group deletion

---

Directory.Packages.props
src/NexusMods.Abstractions.GameLocators/Stores/GOG/GOGLocatorResultMetadata.cs
src/NexusMods.DataModel/MissingArchiveException.cs
src/NexusMods.DataModel/NxFileStore.cs
src/NexusMods.Games.FileHashes/FileHashesServiceSettings.cs
src/NexusMods.Games.RedEngine/Cyberpunk2077/Cyberpunk2077Game.cs
src/NexusMods.Games.RedEngine/NexusMods.Games.RedEngine.csproj
src/NexusMods.Networking.EpicGameStore/EgDataClient.cs
src/NexusMods.StandardGameLocators/AGameLocator.cs
src/NexusMods.StandardGameLocators/EADesktopLocator.cs
src/NexusMods.StandardGameLocators/EpicLocator.cs
src/NexusMods.StandardGameLocators/GogLocator.cs
src/NexusMods.StandardGameLocators/HeroicGogLocator.cs
src/NexusMods.StandardGameLocators/OriginLocator.cs
src/NexusMods.StandardGameLocators/Services.cs
src/NexusMods.StandardGameLocators/SteamLocator.cs
src/NexusMods.StandardGameLocators/XboxLocator.cs

Fixes for several issues found in my testing: 
* Update to the latest version of GameFinder
* Make sure the GOG code correctly locates DLC
* Check for game hash DBs more often (lazily every 30min right now)
* Fixes to how we index files for Epic, the API we were calling has changed a bit, so this brings the indexing code in line with those changes
* Adds an optional path to the `MissingHashException` class so that the file extractor can state where it was planning to extract the file to, should help a bit with debugging

Various Small Fixes

---

src/NexusMods.Games.FileHashes/FileHashesService.cs
src/NexusMods.Games.FileHashes/NexusMods.Games.FileHashes.csproj
src/NexusMods.Games.FileHashes/Verbs.cs

Resolves #3561.
Improves the startup time and reliability of the games hashes update code. The embedded database will be used as a default, however we still need to check if GitHub has a newer release. This check is sadly unavoidable, otherwise first time users might start with an outdated database.

Add embedded games hashes database

---

src/NexusMods.CrossPlatform/Process/AOSInterop.cs
src/NexusMods.CrossPlatform/Process/IOSInterop.cs
src/NexusMods.CrossPlatform/Process/OSInteropLinux.cs
src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationLinux.cs

fixes #3668 , while preserving functional compatibility for all valid Linux file paths.
Originally reported in:  https://discord.com/channels/1134149061080002713/1134149062589960215/1400174190627389491

Fixed: Unrecognised AppImage environment variable after handler fix.

---

src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridAdapter.cs

- Fix #3631 
I wasn't able to reproduce the issue, but I added explicit `IsDisposed` checks to the locations where the exception would trigger.
This should fix the issue for now.

Add isDisposed checks to `TreeDataGridAdapter`

---

src/NexusMods.Telemetry/ExceptionData.cs
tests/NexusMods.Telemetry.Tests/TrackingDataSenderTests.cs

Changes the telemetry data for exceptions to use the first location of the stacktrace as the message. Matomo groups by exception message for some ungodly reason, so this will help with organizing exceptions.

Update exception message being send

---

src/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/NexusMods.Abstractions.Loadouts.Synchronizers/ILoadoutSynchronizer.cs
src/NexusMods.DataModel/Diagnostics/DiagnosticManager.cs

- Fix #3682 
Running Cyberpunk with a redmod installed would trigger a file in use exception.
This was caused by the diagnostic manger attempting to reindex the disk state while RedMod would still be writing data to disk.
This fixes the problem by using the latest DB stored DiskState rather than reindexing it, same approach as what `ShouldSynchronize` is using.

Fix "File in use" exception when applying Cyberpunk

---

NexusMods.App.sln.DotSettings
src/NexusMods.Abstractions.GameLocators/GameInstallation.cs
src/NexusMods.Abstractions.GameLocators/GameLocatorResult.cs
src/NexusMods.Abstractions.GameLocators/GameTargetInfo.cs
src/NexusMods.Abstractions.GameLocators/IGameLocatorResultMetadata.cs
src/NexusMods.Abstractions.Games/AGame.cs
src/NexusMods.Abstractions.Games/IGame.cs
src/NexusMods.Abstractions.Games/RunGameTool.cs
src/NexusMods.Abstractions.Library.Installers/ILibraryArchiveInstaller.cs
src/NexusMods.Collections/FallbackCollectionDownloadInstaller.cs
src/NexusMods.Collections/InstallCollectionJob.cs
src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs
src/NexusMods.Games.CreationEngine/SkyrimSE/SkyrimSE.cs
src/NexusMods.Games.Larian/BaldursGate3/BaldursGate3.cs
src/NexusMods.Games.MountAndBlade2Bannerlord/Bannerlord.cs
src/NexusMods.Games.RedEngine/Cyberpunk2077/Cyberpunk2077Game.cs
src/NexusMods.Games.StardewValley/Emitters/Helpers.cs
src/NexusMods.Games.StardewValley/Installers/SMAPIInstaller.cs
src/NexusMods.Games.StardewValley/StardewValley.cs
src/NexusMods.StandardGameLocators/AGameLocator.cs
src/NexusMods.StandardGameLocators/HeroicGogLocator.cs
src/NexusMods.StandardGameLocators/ManuallyAddedLocator.cs
src/NexusMods.StandardGameLocators/Services.cs
tests/NexusMods.StandardGameLocators.TestHelpers/StubbedGames/StubbedGame.cs
tests/NexusMods.StandardGameLocators.TestHelpers/UniversalStubbedGameLocator.cs

Fixes how we handle OS specific operations for games targeting OS versions different to the host machine. A Windows game running in WINE will now report the target OS as being Windows.
- On Linux install the Windows build of Stardew Valley
- Install SMAPI 
- Game should run with SMAPI loaded and working
Prior to this PR SMAPI would not work correctly in that scenario, as the App installer would install the Linux binaries rather than the windows binaries.

Provide Game Target Info (store + OS)

---

src/Examples/Jobs/README.md
src/NexusMods.Abstractions.Jobs/IJob.cs
src/NexusMods.Abstractions.Jobs/IJobDefinition.cs
src/NexusMods.Abstractions.Jobs/IPublicJobStateData.cs
src/NexusMods.Abstractions.Jobs/IReadOnlyJobState.cs
src/NexusMods.Networking.HttpDownloader/HttpDownloadJob.cs
tests/NexusMods.Jobs.Tests/Examples/BestPractices/JobStateManagementExample.cs

***Looking for feedback here***; curious if anyone has other ideas for approaches.
I'm down for a brainstorm.
Trying to do two things here; in a way where they harmonize with each other:
- Group mutable state of jobs which gets reused across pause/resume cycles.
- (This is also a step towards job persistence)
- Expose internal job state for querying by external code.
More info below.
This design boils down into two items.
- Mutable state is grouped into a struct.
- *ReadOnly state is a slice of that mutable state* which you wish to make world readable.
```csharp
// Public readonly interface for external access
public interface IReadOnlyHttpDownloadState : IReadOnlyJobState
{
Optional<Size> ContentLength { get; }
Size TotalBytesDownloaded { get; }
}
// Internal mutable state with …
```

[Feedback Wanted!] Proposal/Prototype for Standardised way to represent both Internal Job Mutable state and Externally Visible State

---

Directory.Packages.props
src/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
src/NexusMods.Abstractions.Loadouts.Synchronizers/ILoadoutSynchronizer.cs
src/NexusMods.Abstractions.Loadouts.Synchronizers/NexusMods.Abstractions.Loadouts.Synchronizers.csproj
src/NexusMods.Abstractions.Loadouts/Models/DiskStateExtensions.cs
src/NexusMods.Abstractions.Loadouts/NexusMods.Abstractions.Loadouts.csproj
src/NexusMods.DataModel/Diagnostics/DiagnosticManager.cs
src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs
tests/Games/NexusMods.Games.TestFramework/AIsolatedGameTest.cs

This code optimizes the performance of loading DiskStateEntries in ALoadoutSychronizer.cs. 
- Introduces a string pool for caching the contents of the RelativePaths. DiskStates don't have a lot of churn in these names, so I'm not concerned about GC'ing these values
- Implements a sorted merge join for loading entries. 
- Updates the existing code to use these new methods. 
Old Behavior: 
- Find a list of all entries
- Load them one at a time, doing a "lookup by Id" for each, this is *very* expensive since each entity being loaded has to do a search into the RocksDB structures from the top, and each involves about 50 datom comparisons
- Convert the DiskStateEntries into C# structures, doing UTF8->UTF16 on every path
New Behavior:
- Create a iterator for the list of entities to load
- …

Performance Improvements for loading disk state entries

---

src/NexusMods.Abstractions.NexusWebApi/ILoginManager.cs
src/NexusMods.App.UI/Windows/MainWindowViewModel.cs
src/NexusMods.Networking.NexusWebApi/LoginManager.cs

Fixes 2 main things:
1. Premium users losing access to premium features due to UserInfo cache expiring after 1 hour.
2. Users buying premium and not immediately seeing it in the App due to UserInfo not being refreshed.
- **Periodic refresh system**: Automatically refreshes UserInfo every 59 minutes to prevent cache expiration during active use
- **Window focus refresh**: Refreshes UserInfo when app window gains focus. The rationale is that if the user opens a browser window to buy premium, we can check it when they return to the App.
- **Retry logic**: Added basic exponential backoff for network failures (3 retries with increasing delays)
- **Misc**: All refreshes only occur when user is logged in, with comprehensive error handling and logging
- …

Added: Initial implementation of Login Fixes.

---

src/NexusMods.SingleProcess/Services.cs

Fixes #3833. `CliClient` has to be available for the Cleanup method to work. I'm surprised we only got issues for this now since the cleanup code has been in the app for a while now...

Register `CliClient` for all modes

---

src/NexusMods.StandardGameLocators/AGameLocator.cs

Adds a small amount of bloat to the logs, but aids quite a bit in game detection debugging. Logs out the games discovered as `Information` and the discovered locator ids.

Log game discovery information

---

src/NexusMods.Games.FileHashes/FileHashesService.cs
src/NexusMods.Games.FileHashes/Services.cs

Fixes a few issues in the existing file hashes service
* Makes the service a IHostedService so we can get async startup routines. This is required because if there's a connection error
in an existing DB there's no way to force the app startup to halt until we get a fixed DB. This means that something else in the app could call `.Current` causing an error. Now, if the service starts, we'll have an up-to-date db.
* Catches errors connecting to the existing DB, downloads a new DB if the most recent one fails. 
This code helps in the cases where DBs are not forwards compatible. That is a new version of the app, can't work with a old version of the hash db.

Fix hashed service startup issues

---

src/NexusMods.App.UI/Controls/Search/SearchControl.axaml.cs
src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridAdapter.cs

Fixes #3900.
Fixes various issues we've had with not getting notifications on
the `SelectionChanged`.

Fix TreeDataGrid selection on source reset events

---

Directory.Packages.props

- Fixes #3890
This update also fixes the behaviour of `mdb_datoms()` table, to correctly return all the datoms in the database. 
This has significant performance implications, specifically for `RevisionsWithChildUpdates` subscriptions, currently used in:
- `SynchronizerService` to trigger the `ShouldSynchronize` check
- `DiagnosticManager` to trigger health checks
- `LoadoutViewModel` to set value to `HasOutstandingChanges` property
We should keep these monitored

Upgrade MnemonicDb to 0.27.3 and fix collection cloning

---

src/NexusMods.Library/InstallLoadoutItemJob.cs

Use SubTransaction during mod installation to fix leftover empty groups 
